import type { LadderTheme } from './types';

// Sayilabilen / sayilamayan isimler konusma merdiveni icerigi (elle yazildi).
// some/any, much/many, a lot of, a few/a little, How much/How many ve olcu
// ifadeleri (a bottle of, a kilo of, a glass of...).
export const COUNTABLE_UNCOUNTABLE_THEMES: LadderTheme[] = [
  {
    id: 'quant-shopping-list',
    title: 'Alışveriş listesi',
    icon: 'list-outline',
    sentences: [
      { key: 's1', en: 'We need a few things from the supermarket.', tr: 'Marketten birkaç şey almamız lazım.' },
      { key: 's2', en: "There isn't any milk in the fridge.", tr: 'Buzdolabında hiç süt yok.' },
      { key: 's3', en: 'We need two liters of milk.', tr: 'İki litre süt lazım.' },
      { key: 's4', en: 'How many eggs do we have?', tr: 'Kaç tane yumurtamız var?', alts: ['How many eggs are there?'] },
      { key: 's5', en: 'There are only a few eggs left.', tr: 'Sadece birkaç yumurta kalmış.' },
      { key: 's6', en: "There's only a little sugar in the cupboard.", tr: 'Dolapta sadece biraz şeker var.' },
      { key: 's7', en: 'Put a kilo of sugar on the list.', tr: 'Listeye bir kilo şeker yaz.' },
      { key: 's8', en: 'We also need some bread and a bag of rice.', tr: 'Ekmek ve bir paket pirinç de lazım.' },
      { key: 's9', en: 'How much cheese do we have?', tr: 'Ne kadar peynirimiz var?', alts: ['How much cheese is there?'] },
      { key: 's10', en: "There isn't much cheese, so get half a kilo.", tr: 'Fazla peynir yok, yarım kilo al.' },
      { key: 's11', en: 'Get a few apples and some grapes too.', tr: 'Birkaç elma ve biraz üzüm de al.' },
      { key: 's12', en: 'Finally, we need a jar of coffee.', tr: 'Son olarak bir kavanoz kahve lazım.' },
    ],
  },
  {
    id: 'quant-cooking',
    title: 'Menemen yapıyorum',
    icon: 'flame-outline',
    sentences: [
      { key: 's1', en: "I'm making menemen for breakfast today.", tr: 'Bugün kahvaltıya menemen yapıyorum.' },
      { key: 's2', en: 'I need a few tomatoes and two green peppers.', tr: 'Birkaç domates ve iki yeşil biber lazım.' },
      { key: 's3', en: 'I also need three eggs and a little butter.', tr: 'Üç yumurta ve biraz tereyağı da lazım.' },
      { key: 's4', en: "There isn't any butter in the fridge!", tr: 'Buzdolabında hiç tereyağı yok!' },
      { key: 's5', en: "So I'm using a little olive oil instead.", tr: 'Ben de onun yerine biraz zeytinyağı kullanıyorum.' },
      { key: 's6', en: "I'm cutting the tomatoes into small pieces.", tr: 'Domatesleri küçük küçük doğruyorum.' },
      { key: 's7', en: 'How much salt do you put in menemen?', tr: 'Sen menemene ne kadar tuz koyarsın?' },
      { key: 's8', en: 'I only add a pinch of salt.', tr: 'Ben sadece bir tutam tuz koyarım.' },
      { key: 's9', en: "Some people put onions in it, but I don't.", tr: 'Bazıları içine soğan koyar ama ben koymam.' },
      { key: 's10', en: 'We eat it with a lot of fresh bread.', tr: 'Menemeni bol taze ekmekle yeriz.', alts: ['We eat it with lots of fresh bread.'] },
      { key: 's11', en: 'My father always drinks two glasses of tea with it.', tr: 'Babam yanında hep iki bardak çay içer.' },
      { key: 's12', en: 'Do you want some too?', tr: 'Sen de biraz ister misin?' },
    ],
  },
  {
    id: 'quant-market',
    title: 'Semt pazarı',
    icon: 'basket-outline',
    sentences: [
      { key: 's1', en: 'Every Saturday, I go to the local market.', tr: 'Her cumartesi semt pazarına giderim.' },
      { key: 's2', en: 'There are a lot of people there in the morning.', tr: 'Sabahları orada çok insan olur.', alts: ['There are many people there in the morning.'] },
      { key: 's3', en: 'I usually buy a lot of fruit there.', tr: 'Orada genellikle bol meyve alırım.' },
      { key: 's4', en: 'I ask for two kilos of tomatoes.', tr: 'İki kilo domates isterim.' },
      { key: 's5', en: 'The seller always gives me a few extra.', tr: 'Satıcı bana hep birkaç tane fazla verir.' },
      { key: 's6', en: "I don't need many potatoes this week.", tr: 'Bu hafta çok patatese ihtiyacım yok.' },
      { key: 's7', en: 'I also get some cheese and a bag of olives.', tr: 'Biraz peynir ve bir poşet zeytin de alırım.' },
      { key: 's8', en: 'How much cheese do you usually buy?', tr: 'Sen genellikle ne kadar peynir alırsın?' },
      { key: 's9', en: 'I buy half a kilo every week.', tr: 'Ben her hafta yarım kilo alırım.' },
      { key: 's10', en: 'I never take much money with me.', tr: 'Yanıma asla çok para almam.' },
      { key: 's11', en: 'But I always carry a lot of bags home.', tr: 'Ama eve hep bir sürü poşet taşırım.', alts: ['But I always carry lots of bags home.'] },
      { key: 's12', en: 'The market is cheaper than the supermarket.', tr: 'Pazar, marketten daha ucuz.' },
    ],
  },
  {
    id: 'quant-breakfast',
    title: 'Kahvaltı sofrası',
    icon: 'egg-outline',
    sentences: [
      { key: 's1', en: "It's Sunday, and I'm preparing breakfast.", tr: 'Bugün pazar, kahvaltıyı ben hazırlıyorum.' },
      { key: 's2', en: "There's some white cheese and a few olives on the table.", tr: 'Masada biraz beyaz peynir ve birkaç zeytin var.' },
      { key: 's3', en: "I'm making a big pot of tea.", tr: 'Büyük bir demlik çay demliyorum.' },
      { key: 's4', en: 'Is there any honey in the cupboard?', tr: 'Dolapta bal var mı?', alts: ['Do we have any honey?'] },
      { key: 's5', en: "There's only a little honey, but there's a lot of jam.", tr: 'Sadece biraz bal var ama bol reçel var.' },
      { key: 's6', en: 'My son eats a lot of bread in the morning.', tr: 'Oğlum sabahları çok ekmek yer.' },
      { key: 's7', en: 'So I always buy two loaves of bread.', tr: 'Bu yüzden hep iki ekmek alırım.' },
      { key: 's8', en: 'How many eggs do you want?', tr: 'Sen kaç yumurta istersin?' },
      { key: 's9', en: "My father doesn't eat many eggs.", tr: 'Babam fazla yumurta yemez.', alts: ["My father doesn't eat a lot of eggs."] },
      { key: 's10', en: 'He only has a boiled egg and a glass of tea.', tr: 'Sadece bir haşlanmış yumurta yer, bir bardak da çay içer.' },
      { key: 's11', en: "I don't put much sugar in my tea.", tr: 'Çayıma fazla şeker koymam.' },
      { key: 's12', en: 'We sit at the table for a few hours.', tr: 'Birkaç saat sofrada otururuz.' },
    ],
  },
  {
    id: 'quant-party',
    title: 'Parti hazırlığı',
    icon: 'balloon-outline',
    sentences: [
      { key: 's1', en: "It's my daughter's birthday today.", tr: 'Bugün kızımın doğum günü.', alts: ["Today is my daughter's birthday."] },
      { key: 's2', en: "I'm preparing a lot of food for the party.", tr: 'Parti için bol yemek hazırlıyorum.', alts: ["I'm making a lot of food for the party."] },
      { key: 's3', en: 'How many guests do we have?', tr: 'Kaç misafirimiz var?' },
      { key: 's4', en: 'There are fifteen children and a few parents.', tr: 'On beş çocuk ve birkaç anne baba var.' },
      { key: 's5', en: 'We need a lot of juice and some water.', tr: 'Bol meyve suyu ve biraz su lazım.' },
      { key: 's6', en: 'There are ten bottles of juice in the fridge.', tr: 'Buzdolabında on şişe meyve suyu var.' },
      { key: 's7', en: 'My mother is baking a cake with a lot of chocolate.', tr: 'Annem bol çikolatalı bir pasta yapıyor.' },
      { key: 's8', en: "We don't have many plates.", tr: 'Pek fazla tabağımız yok.' },
      { key: 's9', en: 'So my neighbor gave us a few more.', tr: 'O yüzden komşumuz bize birkaç tane daha verdi.' },
      { key: 's10', en: 'How much time do we have?', tr: 'Ne kadar vaktimiz var?' },
      { key: 's11', en: "There isn't much time because the guests arrive at four.", tr: 'Fazla vakit yok çünkü misafirler dörtte geliyor.' },
      { key: 's12', en: 'Now I only need a few balloons.', tr: 'Şimdi sadece birkaç balon eksik.' },
    ],
  },
  {
    id: 'quant-healthy-eating',
    title: 'Sağlıklı beslenme',
    icon: 'nutrition-outline',
    sentences: [
      { key: 's1', en: "I'm trying to eat healthy food these days.", tr: 'Bu aralar sağlıklı beslenmeye çalışıyorum.' },
      { key: 's2', en: 'I drink eight glasses of water a day.', tr: 'Günde sekiz bardak su içiyorum.', alts: ['I drink eight glasses of water every day.'] },
      { key: 's3', en: "I don't eat much bread anymore.", tr: 'Artık fazla ekmek yemiyorum.' },
      { key: 's4', en: 'I eat a lot of vegetables instead.', tr: 'Onun yerine bol sebze yiyorum.' },
      { key: 's5', en: 'For breakfast, I have some yogurt and a few walnuts.', tr: 'Kahvaltıda biraz yoğurt ve birkaç ceviz yiyorum.' },
      { key: 's6', en: "I don't drink any cola.", tr: 'Hiç kola içmiyorum.' },
      { key: 's7', en: 'How much coffee do you drink a day?', tr: 'Sen günde ne kadar kahve içiyorsun?' },
      { key: 's8', en: 'I only have a cup of coffee after lunch.', tr: 'Ben sadece öğle yemeğinden sonra bir fincan kahve içiyorum.' },
      { key: 's9', en: 'My brother eats a lot of junk food.', tr: 'Kardeşim çok abur cubur yer.', alts: ['My brother eats lots of junk food.'] },
      { key: 's10', en: 'He eats a few bars of chocolate every day.', tr: 'Her gün birkaç tane çikolata yer.' },
      { key: 's11', en: 'How many meals do you eat a day?', tr: 'Sen günde kaç öğün yemek yersin?' },
      { key: 's12', en: 'I eat three small meals and a few snacks.', tr: 'Ben üç küçük öğün ve birkaç ara öğün yiyorum.' },
    ],
  },
];
