import type { LadderTheme } from './types';

// "Be going to" konusma merdiveni icerigi (elle yazildi). Planlar, niyetler ve
// gorulen bir isarete dayanan tahminler ("Look at the clouds, it's going to rain").
export const GOING_TO_THEMES: LadderTheme[] = [
  {
    id: 'goingto-weekend-plans',
    title: 'Hafta sonu planlarım',
    icon: 'calendar-outline',
    sentences: [
      { key: 's1', en: "I'm going to have a busy weekend.", tr: 'Hafta sonum yoğun geçecek.' },
      { key: 's2', en: "On Saturday morning, I'm going to clean the house.", tr: 'Cumartesi sabahı evi temizleyeceğim.' },
      { key: 's3', en: "Then I'm going to do the shopping with my mother.", tr: 'Sonra annemle alışveriş yapacağım.', alts: ["Then I'm going to go shopping with my mother."] },
      { key: 's4', en: "In the evening, we're going to watch a film.", tr: 'Akşam da bir film izleyeceğiz.', alts: ["In the evening, we're going to watch a movie."] },
      { key: 's5', en: "On Sunday, I'm going to meet my friends for breakfast.", tr: 'Pazar günü arkadaşlarımla kahvaltıda buluşacağım.' },
      { key: 's6', en: "We're going to try a new coffee shop by the sea.", tr: 'Deniz kenarında yeni bir kafeyi deneyeceğiz.' },
      { key: 's7', en: "I'm not going to open my laptop on Sunday.", tr: 'Pazar günü bilgisayarımı açmayacağım.' },
      { key: 's8', en: "I'm going to relax and read a book.", tr: 'Dinlenip kitap okuyacağım.' },
      { key: 's9', en: 'My sister is going to cook dinner for us.', tr: 'Kız kardeşim bize akşam yemeği yapacak.' },
      { key: 's10', en: "She isn't going to make pasta this time.", tr: 'Bu sefer makarna yapmayacak.' },
      { key: 's11', en: 'What are you going to do this weekend?', tr: 'Sen bu hafta sonu ne yapacaksın?' },
      { key: 's12', en: 'Are you going to stay at home?', tr: 'Evde mi kalacaksın?' },
    ],
  },
  {
    id: 'goingto-summer-holiday',
    title: 'Yaz tatili planı',
    icon: 'airplane-outline',
    sentences: [
      { key: 's1', en: "This summer, we're going to visit Antalya.", tr: "Bu yaz Antalya'ya tatile gideceğiz.", alts: ["This summer, we're going to go to Antalya."] },
      { key: 's2', en: "We're going to stay there for ten days.", tr: 'Orada on gün kalacağız.' },
      { key: 's3', en: "Tonight, I'm going to book a hotel near the beach.", tr: 'Bu akşam plaja yakın bir otelde yer ayırtacağım.' },
      { key: 's4', en: "We aren't going to fly because tickets are expensive.", tr: 'Uçakla gitmeyeceğiz çünkü biletler pahalı.' },
      { key: 's5', en: "We're going to drive there instead.", tr: 'Onun yerine arabayla gideceğiz.' },
      { key: 's6', en: 'The journey is going to take about eight hours.', tr: 'Yolculuk yaklaşık sekiz saat sürecek.' },
      { key: 's7', en: "I'm going to swim in the sea every morning.", tr: 'Her sabah denizde yüzeceğim.' },
      { key: 's8', en: 'My kids are going to play on the beach all day.', tr: 'Çocuklarım bütün gün kumsalda oynayacak.' },
      { key: 's9', en: "I'm not going to check my work emails at all.", tr: 'İş e-postalarıma hiç bakmayacağım.' },
      { key: 's10', en: "We're going to eat fresh fish every evening.", tr: 'Her akşam taze balık yiyeceğiz.' },
      { key: 's11', en: 'Where are you going to spend your holiday?', tr: 'Sen tatilini nerede geçireceksin?', alts: ['Where are you going to spend your vacation?'] },
      { key: 's12', en: "I'm going to take a lot of photos.", tr: 'Bir sürü fotoğraf çekeceğim.' },
    ],
  },
  {
    id: 'goingto-new-year-goals',
    title: 'Yeni yıl hedeflerim',
    icon: 'flag-outline',
    sentences: [
      { key: 's1', en: "This year, I'm going to change a lot of things.", tr: 'Bu yıl birçok şeyi değiştireceğim.' },
      { key: 's2', en: "First, I'm going to learn English properly.", tr: 'Önce İngilizceyi doğru dürüst öğreneceğim.' },
      { key: 's3', en: "I'm going to study for thirty minutes every day.", tr: 'Her gün otuz dakika çalışacağım.' },
      { key: 's4', en: "I'm going to watch films in English.", tr: 'Filmleri İngilizce izleyeceğim.', alts: ["I'm going to watch movies in English."] },
      { key: 's5', en: "I'm also going to join a gym near my house.", tr: 'Evimin yakınındaki bir spor salonuna da yazılacağım.' },
      { key: 's6', en: "I'm going to go there three times a week.", tr: 'Haftada üç kez gideceğim.' },
      { key: 's7', en: "I'm not going to eat so much sugar.", tr: 'Artık o kadar çok şeker yemeyeceğim.' },
      { key: 's8', en: "I'm going to stop smoking too.", tr: 'Sigarayı da bırakacağım.', alts: ["I'm going to quit smoking too."] },
      { key: 's9', en: 'My friend and I are going to run together on Sundays.', tr: 'Arkadaşımla pazarları birlikte koşacağız.' },
      { key: 's10', en: "I'm going to save some money every month.", tr: 'Her ay biraz para biriktireceğim.' },
      { key: 's11', en: "I'm not going to buy so many clothes.", tr: 'O kadar çok kıyafet almayacağım.' },
      { key: 's12', en: 'What are you going to change this year?', tr: 'Sen bu yıl neyi değiştireceksin?' },
    ],
  },
  {
    id: 'goingto-weather',
    title: 'Hava bozuyor',
    icon: 'rainy-outline',
    sentences: [
      { key: 's1', en: 'Look at those dark clouds.', tr: 'Şu kara bulutlara bak.' },
      { key: 's2', en: "It's going to rain soon.", tr: 'Birazdan yağmur yağacak.' },
      { key: 's3', en: "It's going to be a cold evening.", tr: 'Soğuk bir akşam olacak.' },
      { key: 's4', en: "I'm not going to hang the washing outside.", tr: 'Çamaşırları dışarı asmayacağım.', alts: ["I'm not going to hang the laundry outside."] },
      { key: 's5', en: "Take an umbrella, or you're going to get wet.", tr: 'Şemsiye al, yoksa ıslanacaksın.' },
      { key: 's6', en: "The bus is very late, so we're going to take a taxi.", tr: 'Otobüs çok gecikti, o yüzden taksiye bineceğiz.' },
      { key: 's7', en: "With this traffic, we're going to be late.", tr: 'Bu trafikle geç kalacağız.' },
      { key: 's8', en: 'The streets are going to be full of water.', tr: 'Sokaklar suyla dolacak.' },
      { key: 's9', en: 'Is it going to snow tonight?', tr: 'Bu gece kar yağacak mı?' },
      { key: 's10', en: "It's very cold, so I think it's going to snow.", tr: 'Hava çok soğuk, bence kar yağacak.' },
      { key: 's11', en: 'The children are going to be so happy.', tr: 'Çocuklar çok mutlu olacak.' },
      { key: 's12', en: "They aren't going to go to school tomorrow!", tr: 'Yarın okula gitmeyecekler!' },
    ],
  },
  {
    id: 'goingto-moving-house',
    title: 'Yeni eve taşınıyoruz',
    icon: 'cube-outline',
    sentences: [
      { key: 's1', en: "We're going to move to a new flat next month.", tr: 'Gelecek ay yeni bir daireye taşınacağız.', alts: ["We're going to move to a new apartment next month."] },
      { key: 's2', en: 'My kids are going to have their own rooms.', tr: 'Çocuklarımın kendi odaları olacak.' },
      { key: 's3', en: "We're going to pack everything this weekend.", tr: 'Bu hafta sonu bütün eşyaları toplayacağız.' },
      { key: 's4', en: "We're going to need a lot of boxes.", tr: 'Bir sürü koliye ihtiyacımız olacak.' },
      { key: 's5', en: 'My brother is going to help us with the heavy things.', tr: 'Ağır eşyalarda abim bize yardım edecek.' },
      { key: 's6', en: "We aren't going to take the old sofa.", tr: 'Eski kanepeyi götürmeyeceğiz.' },
      { key: 's7', en: "We're going to buy a new one.", tr: 'Yenisini alacağız.' },
      { key: 's8', en: 'Packing the books is going to take hours.', tr: 'Kitapları toplamak saatler sürecek.' },
      { key: 's9', en: "I'm going to paint my son's room blue.", tr: 'Oğlumun odasını maviye boyayacağım.' },
      { key: 's10', en: 'Are you going to help us on Saturday?', tr: 'Cumartesi bize yardım edecek misin?' },
      { key: 's11', en: "I'm going to miss this street.", tr: 'Bu sokağı özleyeceğim.' },
      { key: 's12', en: "But I'm not going to miss the noisy neighbors!", tr: 'Ama gürültücü komşuları hiç özlemeyeceğim!' },
    ],
  },
  {
    id: 'goingto-busy-morning',
    title: 'Telaşlı bir sabah',
    icon: 'alarm-outline',
    sentences: [
      { key: 's1', en: "Oh no, it's already eight o'clock!", tr: 'Eyvah, saat sekiz olmuş bile!' },
      { key: 's2', en: "I'm going to be late for work.", tr: 'İşe geç kalacağım.' },
      { key: 's3', en: "Hurry up, or we're going to miss the bus.", tr: 'Acele et, yoksa otobüsü kaçıracağız.' },
      { key: 's4', en: "I'm not going to have breakfast today.", tr: 'Bugün kahvaltı yapmayacağım.', alts: ["I'm not going to eat breakfast today."] },
      { key: 's5', en: "I'm going to buy a simit on the way.", tr: 'Yolda bir simit alacağım.' },
      { key: 's6', en: 'My phone is going to die soon.', tr: 'Telefonumun şarjı birazdan bitecek.' },
      { key: 's7', en: "Be careful, you're going to spill your tea!", tr: 'Dikkat et, çayını dökeceksin!' },
      { key: 's8', en: 'Is the boss going to be angry?', tr: 'Patron kızacak mı?' },
      { key: 's9', en: "I'm going to call my boss from the bus.", tr: 'Otobüsten patronumu arayacağım.' },
      { key: 's10', en: "I'm not going to miss the meeting.", tr: 'Toplantıyı kaçırmayacağım.' },
      { key: 's11', en: "Tonight, I'm going to set two alarms.", tr: 'Bu akşam iki alarm kuracağım.' },
      { key: 's12', en: "And I'm going to go to bed early!", tr: 'Bir de erken yatacağım!' },
    ],
  },
];
