import type { LadderTheme } from './types';

// If Type 2 konusma merdiveni icerigi (elle yazildi). If + past simple, would + V1:
// hayali simdi/gelecek. Her tema 12 cumlelik bir konusma akisidir.
export const IF_TYPE2_THEMES: LadderTheme[] = [
  {
    id: 'if2-lottery',
    title: 'Piyango bana çıksaydı',
    icon: 'ticket-outline',
    sentences: [
      { key: 's1', en: 'If I won the lottery, I would quit my job.', tr: 'Piyango bana çıksaydı, işimi bırakırdım.', alts: ['If I won the lottery, I would leave my job.'] },
      { key: 's2', en: 'I would buy a big house by the sea.', tr: 'Deniz kenarında büyük bir ev alırdım.' },
      { key: 's3', en: 'My parents would live there with me.', tr: 'Annemle babam da orada benimle yaşardı.' },
      { key: 's4', en: "My father wouldn't have to work anymore.", tr: 'Babamın artık çalışması gerekmezdi.' },
      { key: 's5', en: 'If I had that much money, I would travel a lot.', tr: 'O kadar param olsaydı, çok seyahat ederdim.' },
      { key: 's6', en: 'I would go to Japan first.', tr: "Önce Japonya'ya giderdim." },
      { key: 's7', en: "I wouldn't buy an expensive car.", tr: 'Pahalı bir araba almazdım.' },
      { key: 's8', en: 'I would save the rest of the money.', tr: 'Paranın geri kalanını biriktirirdim.' },
      { key: 's9', en: 'I would also help poor children in my city.', tr: 'Şehrimdeki yoksul çocuklara da yardım ederdim.' },
      { key: 's10', en: "If I were rich, I wouldn't forget my old friends.", tr: 'Zengin olsaydım, eski arkadaşlarımı unutmazdım.' },
      { key: 's11', en: "But I don't even buy lottery tickets!", tr: 'Ama ben piyango bileti bile almam!' },
      { key: 's12', en: 'What would you do if you won the lottery?', tr: 'Piyango sana çıksaydı ne yapardın?' },
    ],
  },
  {
    id: 'if2-abroad',
    title: 'Yurt dışında yaşasaydım',
    icon: 'airplane-outline',
    sentences: [
      { key: 's1', en: 'If I moved abroad, I would go to Italy.', tr: "Yurt dışına taşınsaydım, İtalya'ya giderdim." },
      { key: 's2', en: 'I would learn Italian in a few months.', tr: 'Birkaç ayda İtalyanca öğrenirdim.' },
      { key: 's3', en: 'I would eat pasta and pizza every day.', tr: 'Her gün makarna ve pizza yerdim.' },
      { key: 's4', en: 'If I lived there, I would ride a bike to work.', tr: 'Orada yaşasaydım, işe bisikletle giderdim.', alts: ['If I lived there, I would go to work by bike.'] },
      { key: 's5', en: 'But I would miss my family a lot.', tr: 'Ama ailemi çok özlerdim.' },
      { key: 's6', en: 'I would call my mother every evening.', tr: 'Annemi her akşam arardım.' },
      { key: 's7', en: "It wouldn't be easy to find good Turkish tea.", tr: 'İyi Türk çayı bulmak kolay olmazdı.' },
      { key: 's8', en: 'If I felt lonely, I would come back home for a week.', tr: 'Kendimi yalnız hissetseydim, bir haftalığına eve dönerdim.' },
      { key: 's9', en: 'My friends would visit me in the summer.', tr: 'Arkadaşlarım yazın beni ziyarete gelirdi.', alts: ['My friends would come to see me in the summer.'] },
      { key: 's10', en: 'We would travel around Europe together.', tr: "Birlikte Avrupa'yı gezerdik." },
      { key: 's11', en: "If life were too expensive, I wouldn't stay long.", tr: 'Hayat çok pahalı olsaydı, uzun kalmazdım.' },
      { key: 's12', en: 'Would you ever live in another country?', tr: 'Sen hiç başka bir ülkede yaşar mıydın?' },
    ],
  },
  {
    id: 'if2-mayor',
    title: 'Belediye başkanı olsaydım',
    icon: 'flag-outline',
    sentences: [
      { key: 's1', en: 'If I were the mayor, I would change a lot of things.', tr: 'Belediye başkanı olsaydım, birçok şeyi değiştirirdim.' },
      { key: 's2', en: 'First, I would build more parks for children.', tr: 'Önce çocuklar için daha fazla park yapardım.' },
      { key: 's3', en: 'I would plant trees on every street.', tr: 'Her sokağa ağaç dikerdim.', alts: ['I would plant trees in every street.'] },
      { key: 's4', en: 'The city would be greener and quieter.', tr: 'Şehir daha yeşil ve daha sessiz olurdu.' },
      { key: 's5', en: 'If the buses were free, more people would use them.', tr: 'Otobüsler ücretsiz olsaydı, daha çok insan otobüsleri kullanırdı.' },
      { key: 's6', en: "There wouldn't be so much traffic in the center.", tr: 'Merkezde bu kadar trafik olmazdı.' },
      { key: 's7', en: 'I would open more bike lanes too.', tr: 'Daha fazla bisiklet yolu da açardım.' },
      { key: 's8', en: "People wouldn't need their cars every day.", tr: 'İnsanların her gün arabaya ihtiyacı olmazdı.' },
      { key: 's9', en: 'I would also help street animals.', tr: 'Sokak hayvanlarına da yardım ederdim.' },
      { key: 's10', en: 'If the city had enough money, I would open a big library.', tr: 'Belediyenin yeterli parası olsaydı, büyük bir kütüphane açardım.' },
      { key: 's11', en: "Of course, it wouldn't be easy.", tr: 'Tabii ki bu kolay olmazdı.' },
      { key: 's12', en: 'What would you change if you were the mayor?', tr: 'Belediye başkanı olsaydın neyi değiştirirdin?' },
    ],
  },
  {
    id: 'if2-dream-job',
    title: 'Hayalimdeki iş',
    icon: 'rocket-outline',
    sentences: [
      { key: 's1', en: 'If I could choose any job, I would be a chef.', tr: 'İstediğim işi seçebilseydim, aşçı olurdum.', alts: ['If I could choose any job, I would become a chef.'] },
      { key: 's2', en: 'I would open a small restaurant in Izmir.', tr: "İzmir'de küçük bir restoran açardım." },
      { key: 's3', en: 'I would cook traditional Turkish food.', tr: 'Geleneksel Türk yemekleri pişirirdim.' },
      { key: 's4', en: 'My grandmother would teach me her old recipes.', tr: 'Büyükannem bana eski tariflerini öğretirdi.' },
      { key: 's5', en: 'If I worked in a kitchen, I would be tired every night.', tr: 'Mutfakta çalışsaydım, her akşam yorgun olurdum.' },
      { key: 's6', en: 'But I would be happy, because I love cooking.', tr: 'Ama mutlu olurdum çünkü yemek yapmayı çok severim.' },
      { key: 's7', en: "I wouldn't sit at a desk all day.", tr: 'Bütün gün bir masada oturmazdım.' },
      { key: 's8', en: "I wouldn't look at a computer screen for hours.", tr: 'Saatlerce bilgisayar ekranına bakmazdım.' },
      { key: 's9', en: 'If my restaurant were successful, I would open another one.', tr: 'Restoranım başarılı olsaydı, bir tane daha açardım.' },
      { key: 's10', en: 'My friends would come and eat for free.', tr: 'Arkadaşlarım gelip bedava yemek yerdi.' },
      { key: 's11', en: 'Right now, I work in an office.', tr: 'Şu an bir ofiste çalışıyorum.' },
      { key: 's12', en: 'What would your dream job be?', tr: 'Senin hayalindeki iş ne olurdu?' },
    ],
  },
  {
    id: 'if2-free-week',
    title: 'Boş bir haftam olsaydı',
    icon: 'calendar-outline',
    sentences: [
      { key: 's1', en: 'If I had a free week, I would go to the Black Sea.', tr: "Boş bir haftam olsaydı, Karadeniz'e giderdim." },
      { key: 's2', en: 'I would stay in a small wooden house.', tr: 'Küçük, ahşap bir evde kalırdım.' },
      { key: 's3', en: 'I would wake up late every morning.', tr: 'Her sabah geç uyanırdım.', alts: ['I would get up late every morning.'] },
      { key: 's4', en: "I wouldn't check my work emails at all.", tr: 'İş e-postalarıma hiç bakmazdım.' },
      { key: 's5', en: 'If the weather were nice, I would walk in the mountains.', tr: 'Hava güzel olsaydı, dağlarda yürüyüş yapardım.' },
      { key: 's6', en: 'I would drink tea and look at the green hills.', tr: 'Çay içip yeşil tepeleri seyrederdim.' },
      { key: 's7', en: 'I would eat fish and corn bread every day.', tr: 'Her gün balık ve mısır ekmeği yerdim.' },
      { key: 's8', en: 'If it rained, I would read a book by the window.', tr: 'Yağmur yağsaydı, pencere kenarında kitap okurdum.' },
      { key: 's9', en: "I wouldn't watch TV or use social media.", tr: 'Televizyon izlemezdim, sosyal medyaya da girmezdim.' },
      { key: 's10', en: 'My phone would stay in my bag all week.', tr: 'Telefonum bütün hafta çantamda dururdu.' },
      { key: 's11', en: 'After a week like that, I would feel like a new person.', tr: 'Böyle bir haftadan sonra kendimi yeni biri gibi hissederdim.' },
      { key: 's12', en: 'Where would you go if you had a free week?', tr: 'Boş bir haftan olsaydı nereye giderdin?' },
    ],
  },
  {
    id: 'if2-advice',
    title: 'Arkadaşıma tavsiyeler',
    icon: 'bulb-outline',
    sentences: [
      { key: 's1', en: 'You look very tired these days, my friend.', tr: 'Bu aralar çok yorgun görünüyorsun, dostum.' },
      { key: 's2', en: 'If I were you, I would talk to your boss.', tr: 'Senin yerinde olsaydım, patronunla konuşurdum.', alts: ['If I were you, I would speak to your boss.'] },
      { key: 's3', en: "I wouldn't stay at the office until nine.", tr: 'Ben olsam ofiste dokuza kadar kalmazdım.' },
      { key: 's4', en: 'If you slept more, you would feel better.', tr: 'Daha çok uyusaydın, kendini daha iyi hissederdin.' },
      { key: 's5', en: 'You also drink too much coffee.', tr: 'Ayrıca çok fazla kahve içiyorsun.' },
      { key: 's6', en: 'If I were you, I would drink more water.', tr: 'Senin yerinde olsaydım, daha çok su içerdim.' },
      { key: 's7', en: "I wouldn't eat fast food every day.", tr: 'Ben olsam her gün hazır yemek yemezdim.' },
      { key: 's8', en: 'A short walk after work would help you a lot.', tr: 'İşten sonra kısa bir yürüyüş sana çok iyi gelirdi.' },
      { key: 's9', en: 'If you had a hobby, you would relax more.', tr: 'Bir hobin olsaydı, daha çok rahatlardın.' },
      { key: 's10', en: 'For example, I would start guitar lessons.', tr: 'Mesela ben gitar derslerine başlardım.' },
      { key: 's11', en: 'If you took a holiday, you would come back happier.', tr: 'Tatile çıksaydın, daha mutlu dönerdin.' },
      { key: 's12', en: 'Would you feel better if you left that job?', tr: 'O işten ayrılsaydın kendini daha iyi hisseder miydin?' },
    ],
  },
];
