import type { LadderTheme } from './types';

// First conditional (if + present simple, will/won't) konusma merdiveni icerigi
// (elle yazildi). Her tema, o konuda art arda anlatilabilecek 12 cumlelik bir
// konusma akisidir. if cumlesi bazen basta, bazen sonda; unless en fazla iki kez.
export const IF_TYPE1_THEMES: LadderTheme[] = [
  {
    id: 'if1-weather',
    title: 'Hava ve planlar',
    icon: 'partly-sunny-outline',
    sentences: [
      { key: 's1', en: "If the weather is nice tomorrow, we'll go to the beach.", tr: 'Yarın hava güzel olursa denize gideceğiz.' },
      { key: 's2', en: "If it rains, we'll stay at home.", tr: 'Yağmur yağarsa evde kalacağız.' },
      { key: 's3', en: "We'll watch a film if we stay in.", tr: 'Evde kalırsak film izleriz.', alts: ["We'll watch a movie if we stay in."] },
      { key: 's4', en: "If it's too hot, the kids will get tired quickly.", tr: 'Hava çok sıcak olursa çocuklar çabuk yorulur.' },
      { key: 's5', en: "If we leave early, we'll find a good place.", tr: 'Erken çıkarsak iyi bir yer buluruz.' },
      { key: 's6', en: "We won't find a parking space if we're late.", tr: 'Geç kalırsak park yeri bulamayız.' },
      { key: 's7', en: "If you bring the watermelon, I'll bring the bread.", tr: 'Sen karpuzu getirirsen ben de ekmeği getiririm.' },
      { key: 's8', en: "If you don't wear a hat, you'll get a headache.", tr: 'Şapka takmazsan başın ağrır.' },
      { key: 's9', en: "If the wind is strong, we won't swim.", tr: 'Rüzgâr sert olursa denize girmeyiz.' },
      { key: 's10', en: "If we can't swim, we'll walk by the sea.", tr: 'Denize giremezsek sahilde yürürüz.' },
      { key: 's11', en: 'What will you do if it rains all weekend?', tr: 'Bütün hafta sonu yağmur yağarsa ne yapacaksın?' },
      { key: 's12', en: "I'll call you tonight if the forecast changes.", tr: 'Hava tahmini değişirse bu akşam seni ararım.' },
    ],
  },
  {
    id: 'if1-exam',
    title: 'Sınav haftası',
    icon: 'school-outline',
    sentences: [
      { key: 's1', en: 'My final exams start next week.', tr: 'Final sınavlarım haftaya başlıyor.' },
      { key: 's2', en: "If I study hard, I'll pass all of them.", tr: 'Sıkı çalışırsam hepsini geçerim.' },
      { key: 's3', en: "If I fail math, I'll have to take it again.", tr: 'Matematikten kalırsam dersi tekrar almak zorunda kalacağım.' },
      { key: 's4', en: 'My parents will be angry if my grades are low.', tr: 'Notlarım düşük olursa ailem kızar.' },
      { key: 's5', en: "If I go to the library, I'll study better.", tr: 'Kütüphaneye gidersem daha iyi çalışırım.' },
      { key: 's6', en: "If I look at my phone, I won't finish anything.", tr: 'Telefonuma bakarsam hiçbir şeyi bitiremem.' },
      { key: 's7', en: "If my friends call, I won't answer.", tr: 'Arkadaşlarım ararsa açmayacağım.' },
      { key: 's8', en: "I'll call them back if I finish early.", tr: 'Erken bitirirsem onları geri ararım.' },
      { key: 's9', en: "If I don't sleep enough, I won't remember anything.", tr: 'Yeterince uyumazsam hiçbir şey aklımda kalmaz.' },
      { key: 's10', en: "I'll drink a lot of tea if I study at night.", tr: 'Gece çalışırsam bol çay içerim.' },
      { key: 's11', en: "Will you help me if I don't understand something?", tr: 'Bir şeyi anlamazsam bana yardım eder misin?' },
      { key: 's12', en: "If I pass everything, we'll celebrate together!", tr: 'Her şeyi geçersem birlikte kutlarız!' },
    ],
  },
  {
    id: 'if1-traffic',
    title: 'Trafik ve gecikme',
    icon: 'time-outline',
    sentences: [
      { key: 's1', en: 'The traffic in Istanbul is terrible in the evening.', tr: "İstanbul'da akşamları trafik berbat." },
      { key: 's2', en: "If I leave at six, I'll be home at eight.", tr: 'Altıda çıkarsam sekizde evde olurum.' },
      { key: 's3', en: "If I leave at five, I'll get home in an hour.", tr: 'Beşte çıkarsam bir saatte eve varırım.' },
      { key: 's4', en: "I'll take the metro if the roads are busy.", tr: 'Yollar tıkalıysa metroya binerim.' },
      { key: 's5', en: "If I take the ferry, I'll see the sea.", tr: 'Vapura binersem denizi görürüm.' },
      { key: 's6', en: "But the ferries won't run if there's a storm.", tr: 'Ama fırtına çıkarsa vapurlar sefer yapmaz.' },
      { key: 's7', en: "If I'm late again, my boss won't be happy.", tr: 'Yine geç kalırsam patronum hiç memnun olmaz.' },
      { key: 's8', en: "I'll call him if I'm stuck in traffic.", tr: 'Trafiğe takılırsam onu ararım.' },
      { key: 's9', en: "Unless the bus comes soon, I'll take a taxi.", tr: 'Otobüs birazdan gelmezse taksiye binerim.', alts: ["If the bus doesn't come soon, I'll take a taxi."] },
      { key: 's10', en: 'A taxi will be expensive if the traffic is heavy.', tr: 'Trafik yoğunsa taksi pahalıya patlar.' },
      { key: 's11', en: 'What will you do if you miss the last metro?', tr: 'Son metroyu kaçırırsan ne yapacaksın?' },
      { key: 's12', en: "If I miss it, I'll stay at my friend's house.", tr: 'Kaçırırsam arkadaşımda kalırım.' },
    ],
  },
  {
    id: 'if1-saving',
    title: 'Para biriktiriyorum',
    icon: 'wallet-outline',
    sentences: [
      { key: 's1', en: "I'm saving money for a new car.", tr: 'Yeni bir araba için para biriktiriyorum.' },
      { key: 's2', en: "If I save every month, I'll buy it next year.", tr: 'Her ay biriktirirsem seneye alırım.' },
      { key: 's3', en: "If I eat out less, I'll save more money.", tr: 'Dışarıda daha az yersem daha çok para biriktiririm.' },
      { key: 's4', en: "If I make coffee at home, I won't spend much.", tr: 'Kahveyi evde yaparsam fazla para harcamam.' },
      { key: 's5', en: "If I walk to work, I won't pay for the bus.", tr: 'İşe yürüyerek gidersem otobüse para vermem.' },
      { key: 's6', en: "If I go shopping when I'm hungry, I'll spend too much.", tr: 'Aç karnına alışverişe gidersem çok fazla harcarım.' },
      { key: 's7', en: "I'll get a better price if I pay in cash.", tr: 'Peşin ödersem daha iyi fiyat alırım.' },
      { key: 's8', en: "If I use my credit card too much, I'll get into debt.", tr: 'Kredi kartımı çok kullanırsam borca girerim.' },
      { key: 's9', en: "If my brother asks for money, I'll say no.", tr: 'Kardeşim borç isterse hayır diyeceğim.' },
      { key: 's10', en: "I won't buy anything unless I really need it.", tr: 'Gerçekten ihtiyacım olmadıkça hiçbir şey almayacağım.', alts: ["I won't buy anything if I don't really need it."] },
      { key: 's11', en: 'How much will you save if you cook at home?', tr: 'Evde yemek yaparsan ne kadar biriktirirsin?' },
      { key: 's12', en: "If everything goes well, I'll drive my new car next summer.", tr: 'Her şey yolunda giderse gelecek yaz yeni arabamı süreceğim.' },
    ],
  },
  {
    id: 'if1-health',
    title: 'Nezle oldum',
    icon: 'thermometer-outline',
    sentences: [
      { key: 's1', en: 'I have a bad cold this week.', tr: 'Bu hafta fena nezle oldum.' },
      { key: 's2', en: "If I rest, I'll feel better in a few days.", tr: 'Dinlenirsem birkaç güne iyileşirim.' },
      { key: 's3', en: 'If I go to work, my colleagues will get sick too.', tr: 'İşe gidersem iş arkadaşlarım da hastalanır.' },
      { key: 's4', en: "I'll work from home if my boss agrees.", tr: 'Patronum kabul ederse evden çalışacağım.' },
      { key: 's5', en: 'If I drink hot soup, my throat will feel better.', tr: 'Sıcak çorba içersem boğazım rahatlar.' },
      { key: 's6', en: "I'll go to the doctor if my fever doesn't go down.", tr: 'Ateşim düşmezse doktora giderim.' },
      { key: 's7', en: "If I don't take my medicine, I won't get better.", tr: 'İlacımı almazsam iyileşmem.' },
      { key: 's8', en: "If I call my mother, she'll come right away.", tr: 'Annemi ararsam hemen gelir.' },
      { key: 's9', en: "If I go to bed early, I'll have more energy tomorrow.", tr: 'Erken yatarsam yarın daha enerjik olurum.' },
      { key: 's10', en: "I won't go to the gym if I'm still sick.", tr: 'Hâlâ hastaysam spor salonuna gitmeyeceğim.' },
      { key: 's11', en: 'Will you bring me some oranges if you come?', tr: 'Gelirsen bana biraz portakal getirir misin?' },
      { key: 's12', en: "If I feel better on Monday, I'll go back to work.", tr: 'Pazartesi daha iyi hissedersem işe dönerim.' },
    ],
  },
  {
    id: 'if1-weekend',
    title: 'Hafta sonu planları',
    icon: 'calendar-outline',
    sentences: [
      { key: 's1', en: "I don't have any plans for Saturday yet.", tr: 'Cumartesi için henüz bir planım yok.' },
      { key: 's2', en: "If my friends are free, we'll have breakfast together.", tr: 'Arkadaşlarım müsaitse birlikte kahvaltı yaparız.' },
      { key: 's3', en: "If it's sunny, we'll sit by the sea.", tr: 'Hava güneşliyse deniz kenarında otururuz.' },
      { key: 's4', en: "I'll clean the house if they're busy.", tr: 'Onlar meşgulse evi temizlerim.' },
      { key: 's5', en: "If I'm not tired, I'll call my cousin.", tr: 'Yorgun değilsem kuzenimi ararım.' },
      { key: 's6', en: "We'll go to the cinema if there's a good film.", tr: 'İyi bir film varsa sinemaya gideriz.', alts: ["We'll go to the cinema if there's a good movie."] },
      { key: 's7', en: "If the tickets are expensive, we won't go.", tr: 'Biletler pahalıysa gitmeyiz.' },
      { key: 's8', en: "We'll order pizza if we don't go out.", tr: 'Dışarı çıkmazsak pizza söyleriz.' },
      { key: 's9', en: "On Sunday, I'll visit my grandmother if she feels well.", tr: 'Pazar günü büyükannem iyiyse onu ziyaret edeceğim.' },
      { key: 's10', en: "She'll be sad if I don't visit her.", tr: 'Onu ziyaret etmezsem üzülür.' },
      { key: 's11', en: "What will you do if you're free on Sunday?", tr: 'Pazar günü boşsan ne yapacaksın?' },
      { key: 's12', en: "If you come with me, you'll love her food!", tr: 'Benimle gelirsen onun yemeklerine bayılacaksın!' },
    ],
  },
];
