import type { LadderTheme } from './types';

// must / have to konusma merdiveni icerigi (elle yazildi). Her tema, o konuda art
// arda anlatilabilecek 12 cumlelik bir konusma akisidir. mustn't (yasak) ile
// don't have to (gerek yok) farki temalarda yan yana gorunur.
export const MUST_HAVE_TO_THEMES: LadderTheme[] = [
  {
    id: 'must-airport',
    title: 'Havalimanında',
    icon: 'airplane-outline',
    sentences: [
      { key: 's1', en: 'We have to be at the airport two hours early.', tr: 'Havalimanında iki saat önceden olmamız gerekiyor.', alts: ['We must be at the airport two hours early.'] },
      { key: 's2', en: 'First, we need to check in our bags.', tr: 'Önce bagajlarımızı vermemiz lazım.' },
      { key: 's3', en: 'You must show your passport at the desk.', tr: 'Bankoda pasaportunu göstermelisin.' },
      { key: 's4', en: "You don't have to print your ticket.", tr: 'Biletini yazdırmana gerek yok.' },
      { key: 's5', en: 'Then we have to go through security.', tr: 'Sonra güvenlikten geçmek zorundayız.' },
      { key: 's6', en: 'You have to take off your jacket and belt.', tr: 'Ceketini ve kemerini çıkarman gerekiyor.' },
      { key: 's7', en: "You mustn't carry liquids in your hand luggage.", tr: 'El bagajında sıvı taşımak yasak.' },
      { key: 's8', en: "But you don't have to take off your shoes.", tr: 'Ama ayakkabılarını çıkarmak zorunda değilsin.' },
      { key: 's9', en: 'Last time, I had to throw away my perfume.', tr: 'Geçen sefer parfümümü atmak zorunda kaldım.' },
      { key: 's10', en: 'On the plane, you must wear your seat belt.', tr: 'Uçakta emniyet kemerini takmalısın.' },
      { key: 's11', en: 'Do we have to pay for food on this flight?', tr: 'Bu uçuşta yemek için para ödememiz gerekiyor mu?' },
      { key: 's12', en: "Luckily, we don't have to change planes.", tr: 'Neyse ki aktarma yapmak zorunda değiliz.' },
    ],
  },
  {
    id: 'must-hospital',
    title: 'Hastanede',
    icon: 'medkit-outline',
    sentences: [
      { key: 's1', en: 'I have to go to the hospital today.', tr: 'Bugün hastaneye gitmem gerekiyor.', alts: ['I need to go to the hospital today.'] },
      { key: 's2', en: "I've had a bad cough for two weeks.", tr: 'İki haftadır kötü bir öksürüğüm var.' },
      { key: 's3', en: 'First, I have to take a number at the entrance.', tr: 'Önce girişte sıra numarası almam lazım.' },
      { key: 's4', en: 'Then I need to wait for about an hour.', tr: 'Sonra yaklaşık bir saat beklemem gerekiyor.' },
      { key: 's5', en: 'In the waiting room, you must be quiet.', tr: 'Bekleme salonunda sessiz olmalısın.' },
      { key: 's6', en: "You mustn't talk loudly on the phone.", tr: 'Telefonda yüksek sesle konuşmamalısın.' },
      { key: 's7', en: 'The doctor says I need to rest for a few days.', tr: 'Doktor birkaç gün dinlenmem gerektiğini söylüyor.' },
      { key: 's8', en: 'I have to take this medicine three times a day.', tr: 'Bu ilacı günde üç kez almam gerekiyor.' },
      { key: 's9', en: "I mustn't drink cold drinks this week.", tr: 'Bu hafta soğuk içecek içmemeliyim.' },
      { key: 's10', en: "Luckily, I don't have to stay in the hospital.", tr: 'Neyse ki hastanede yatmak zorunda değilim.' },
      { key: 's11', en: 'Do I have to come back next week?', tr: 'Gelecek hafta tekrar gelmem gerekiyor mu?' },
      { key: 's12', en: 'I had to take a day off work for this.', tr: 'Bunun için işten bir gün izin almak zorunda kaldım.' },
    ],
  },
  {
    id: 'must-driving',
    title: 'Trafik kuralları',
    icon: 'car-outline',
    sentences: [
      { key: 's1', en: "I've been driving for ten years.", tr: 'On yıldır araba kullanıyorum.' },
      { key: 's2', en: "You have to be eighteen to get a driver's license.", tr: 'Ehliyet almak için on sekiz yaşında olman gerekiyor.' },
      { key: 's3', en: 'You must always have your license with you.', tr: 'Ehliyetin her zaman yanında olmalı.' },
      { key: 's4', en: 'Children must sit in the back seat.', tr: 'Çocuklar arka koltukta oturmalı.' },
      { key: 's5', en: "You mustn't talk on the phone while you're driving.", tr: 'Araba kullanırken telefonla konuşmamalısın.' },
      { key: 's6', en: "You mustn't drive faster than fifty in the city.", tr: 'Şehir içinde elliden hızlı gitmemelisin.' },
      { key: 's7', en: 'Last month, I had to pay a big fine.', tr: 'Geçen ay yüklü bir ceza ödemek zorunda kaldım.' },
      { key: 's8', en: 'I parked in the wrong place.', tr: 'Yanlış yere park etmiştim.' },
      { key: 's9', en: 'On long trips, you need to stop every two hours.', tr: 'Uzun yolda iki saatte bir mola vermen lazım.' },
      { key: 's10', en: "In Turkey, you don't have to fill the tank yourself.", tr: "Türkiye'de depoyu kendin doldurmak zorunda değilsin." },
      { key: 's11', en: 'Do you have to drive to work every day?', tr: 'Her gün işe arabayla gitmek zorunda mısın?' },
      { key: 's12', en: 'My brother has to take his driving test again.', tr: 'Kardeşim ehliyet sınavına yeniden girmek zorunda.' },
    ],
  },
  {
    id: 'must-new-job',
    title: 'Yeni işimde ilk hafta',
    icon: 'id-card-outline',
    sentences: [
      { key: 's1', en: 'I started a new job this week.', tr: 'Bu hafta yeni bir işe başladım.' },
      { key: 's2', en: 'I have to get up at six every morning.', tr: 'Her sabah altıda kalkmam gerekiyor.', alts: ['I have to wake up at six every morning.'] },
      { key: 's3', en: 'We must be at the office by eight.', tr: 'En geç sekizde ofiste olmalıyız.' },
      { key: 's4', en: "We don't have to wear a suit on Fridays.", tr: 'Cuma günleri takım elbise giymek zorunda değiliz.' },
      { key: 's5', en: 'We have to wear our ID cards all the time.', tr: 'Kimlik kartımızı her zaman takmak zorundayız.' },
      { key: 's6', en: "You mustn't share your password with anyone.", tr: 'Şifreni kimseyle paylaşmamalısın.' },
      { key: 's7', en: 'I need to learn a lot of new things.', tr: 'Pek çok yeni şey öğrenmem gerekiyor.' },
      { key: 's8', en: 'Yesterday, I had to stay until seven.', tr: 'Dün yediye kadar kalmak zorunda kaldım.' },
      { key: 's9', en: 'My manager has to check my work this month.', tr: 'Müdürüm bu ay işlerimi kontrol etmek zorunda.' },
      { key: 's10', en: "She says I don't have to worry.", tr: 'Endişelenmeme gerek olmadığını söylüyor.' },
      { key: 's11', en: 'Do you have to wear a uniform at work?', tr: 'İş yerinde üniforma giymek zorunda mısın?' },
      { key: 's12', en: 'I have to say, I really like this job.', tr: 'Şunu söylemeliyim, bu işi gerçekten seviyorum.' },
    ],
  },
  {
    id: 'must-guest-visit',
    title: 'Misafirliğe gidiyoruz',
    icon: 'gift-outline',
    sentences: [
      { key: 's1', en: "We're visiting my aunt tonight.", tr: 'Bu akşam teyzemlere gidiyoruz.' },
      { key: 's2', en: "We mustn't go empty-handed.", tr: 'Eli boş gitmemeliyiz.' },
      { key: 's3', en: "But we don't have to buy an expensive gift.", tr: 'Ama pahalı bir hediye almak zorunda değiliz.' },
      { key: 's4', en: 'We just need to stop at a pastry shop.', tr: 'Sadece bir pastaneye uğramamız lazım.' },
      { key: 's5', en: 'At the door, you have to take off your shoes.', tr: 'Kapıda ayakkabılarını çıkarman gerekiyor.', alts: ['At the door, you must take off your shoes.'] },
      { key: 's6', en: "You don't have to bring slippers.", tr: 'Terlik getirmene gerek yok.' },
      { key: 's7', en: 'My aunt always has slippers for guests.', tr: 'Teyzemde misafirler için her zaman terlik vardır.' },
      { key: 's8', en: "You must kiss my grandmother's hand.", tr: 'Büyükannemin elini öpmelisin.' },
      { key: 's9', en: 'You have to eat a lot, or my aunt gets sad.', tr: 'Çok yemen lazım, yoksa teyzem üzülür.' },
      { key: 's10', en: "You mustn't say no to a second glass of tea.", tr: 'İkinci bardak çaya hayır dememelisin.' },
      { key: 's11', en: 'Do we have to stay late?', tr: 'Geç saate kadar kalmamız gerekiyor mu?' },
      { key: 's12', en: 'Last time, we had to stay until midnight!', tr: 'Geçen sefer gece yarısına kadar kalmak zorunda kaldık!' },
    ],
  },
  {
    id: 'must-home-rules',
    title: 'Evdeki kurallar',
    icon: 'clipboard-outline',
    sentences: [
      { key: 's1', en: 'We have a few rules in our house.', tr: 'Evimizde birkaç kural var.' },
      { key: 's2', en: 'My kids have to make their beds every morning.', tr: 'Çocuklarım her sabah yataklarını toplamak zorunda.' },
      { key: 's3', en: 'They must do their homework before dinner.', tr: 'Akşam yemeğinden önce ödevlerini yapmalılar.' },
      { key: 's4', en: "They mustn't play computer games on weekdays.", tr: 'Hafta içi bilgisayar oyunu oynamaları yasak.' },
      { key: 's5', en: "But they don't have to go to bed early on Saturdays.", tr: 'Ama cumartesileri erken yatmak zorunda değiller.' },
      { key: 's6', en: 'Everyone has to take their plate to the kitchen.', tr: 'Herkes kendi tabağını mutfağa götürmek zorunda.' },
      { key: 's7', en: 'My husband has to take out the rubbish.', tr: 'Eşim çöpü çıkarmak zorunda.', alts: ['My husband has to take out the trash.'] },
      { key: 's8', en: 'On Sundays, nobody has to cook.', tr: 'Pazarları kimse yemek yapmak zorunda değil.' },
      { key: 's9', en: 'As a child, I had to help my mother a lot.', tr: 'Çocukken anneme çok yardım etmek zorundaydım.' },
      { key: 's10', en: 'I had to wash the dishes after every meal.', tr: 'Her yemekten sonra bulaşıkları yıkamak zorundaydım.' },
      { key: 's11', en: 'Did you have to help at home as a child?', tr: 'Çocukken evde yardım etmek zorunda mıydın?' },
      { key: 's12', en: "My kids don't know how lucky they are!", tr: 'Çocuklarım ne kadar şanslı olduklarını bilmiyor!' },
    ],
  },
];
