import type { LadderTheme } from './types';

// Passive konusma merdiveni icerigi (elle yazildi). Agirlikla is/are + V3 ve
// was/were + V3, birkac cumlede "by". Her tema 12 cumlelik bir konusma akisidir.
export const PASSIVE_THEMES: LadderTheme[] = [
  {
    id: 'passive-simit-tea',
    title: 'Simit ve çay',
    icon: 'leaf-outline',
    sentences: [
      { key: 's1', en: "Simit isn't only sold in bakeries.", tr: 'Simit sadece fırınlarda satılmaz.' },
      { key: 's2', en: 'It is also sold on the street every morning.', tr: 'Her sabah sokaklarda da satılır.' },
      { key: 's3', en: 'The dough is made with flour, water and salt.', tr: 'Hamuru un, su ve tuzla yapılır.' },
      { key: 's4', en: 'Then it is shaped into rings.', tr: 'Sonra halka şekline getirilir.' },
      { key: 's5', en: 'The rings are covered with sesame seeds.', tr: 'Halkaların üzeri susamla kaplanır.' },
      { key: 's6', en: 'Then they are baked in a hot oven.', tr: 'Sonra sıcak bir fırında pişirilir.' },
      { key: 's7', en: 'Simit is usually eaten with cheese and tea.', tr: 'Simit genellikle peynir ve çayla yenir.' },
      { key: 's8', en: 'Turkish tea is grown near the Black Sea.', tr: 'Türk çayı Karadeniz kıyısında yetiştirilir.' },
      { key: 's9', en: 'The leaves are dried and packed in factories.', tr: 'Yapraklar fabrikalarda kurutulur ve paketlenir.' },
      { key: 's10', en: 'At home, tea is made in a double teapot.', tr: 'Evde çay, çaydanlıkta demlenir.', alts: ['At home, tea is brewed in a double teapot.'] },
      { key: 's11', en: "It isn't usually drunk with milk.", tr: 'Genellikle sütle içilmez.' },
      { key: 's12', en: 'How is tea made in your home?', tr: 'Sizin evde çay nasıl demlenir?' },
    ],
  },
  {
    id: 'passive-city-history',
    title: 'Şehrimin tarihi',
    icon: 'library-outline',
    sentences: [
      { key: 's1', en: 'Istanbul is a very old city.', tr: 'İstanbul çok eski bir şehir.' },
      { key: 's2', en: 'It was called Constantinople for a long time.', tr: 'Uzun süre ona Konstantinopolis denildi.' },
      { key: 's3', en: 'The city was conquered by the Ottomans in 1453.', tr: "Şehir 1453'te Osmanlılar tarafından fethedildi.", alts: ['The city was taken by the Ottomans in 1453.'] },
      { key: 's4', en: 'Hagia Sophia was built long before that.', tr: 'Ayasofya bundan çok önce inşa edildi.' },
      { key: 's5', en: 'Galata Tower was built in 1348.', tr: "Galata Kulesi 1348'de inşa edildi." },
      { key: 's6', en: 'It was used as a fire tower for many years.', tr: 'Uzun yıllar yangın gözetleme kulesi olarak kullanıldı.' },
      { key: 's7', en: "It isn't used for that anymore.", tr: 'Artık bu amaçla kullanılmıyor.' },
      { key: 's8', en: 'Today it is visited by thousands of tourists.', tr: 'Bugün binlerce turist tarafından ziyaret ediliyor.' },
      { key: 's9', en: 'The first bridge over the Bosphorus was opened in 1973.', tr: "Boğaz'daki ilk köprü 1973'te açıldı." },
      { key: 's10', en: "Before that, the two sides weren't connected by a bridge.", tr: 'Ondan önce iki yaka birbirine bir köprüyle bağlanmamıştı.' },
      { key: 's11', en: 'People and cars were carried by ferries.', tr: 'İnsanlar ve arabalar vapurlarla taşınırdı.' },
      { key: 's12', en: 'When was your city founded?', tr: 'Senin şehrin ne zaman kuruldu?' },
    ],
  },
  {
    id: 'passive-package',
    title: 'Kargom geldi',
    icon: 'cube-outline',
    sentences: [
      { key: 's1', en: 'I ordered new headphones online last week.', tr: 'Geçen hafta internetten yeni bir kulaklık sipariş ettim.', alts: ['I bought new headphones online last week.'] },
      { key: 's2', en: 'The order was confirmed the same day.', tr: 'Sipariş aynı gün onaylandı.' },
      { key: 's3', en: 'The package was sent from Istanbul on Monday.', tr: "Paket pazartesi günü İstanbul'dan gönderildi." },
      { key: 's4', en: 'Packages are usually delivered in two days.', tr: 'Kargolar genellikle iki günde teslim edilir.' },
      { key: 's5', en: "But mine wasn't delivered until Friday.", tr: 'Ama benimki cumaya kadar teslim edilmedi.' },
      { key: 's6', en: "I wasn't at home, so it was left with my neighbor.", tr: 'Evde değildim, bu yüzden komşuma bırakıldı.' },
      { key: 's7', en: 'It was given to me in the evening.', tr: 'Paket akşam bana verildi.' },
      { key: 's8', en: 'But the box was damaged on the way.', tr: 'Ama kutu yolda hasar görmüştü.' },
      { key: 's9', en: "Luckily, the headphones weren't broken.", tr: 'Neyse ki kulaklık kırılmamıştı.' },
      { key: 's10', en: 'A photo of the box was sent to the seller.', tr: 'Kutunun fotoğrafı satıcıya gönderildi.' },
      { key: 's11', en: 'I was given a small discount.', tr: 'Bana küçük bir indirim yapıldı.' },
      { key: 's12', en: 'Are your packages delivered on time?', tr: 'Senin kargoların zamanında teslim edilir mi?' },
    ],
  },
  {
    id: 'passive-match',
    title: 'Maç özeti',
    icon: 'trophy-outline',
    sentences: [
      { key: 's1', en: 'The big match was played on Sunday night.', tr: 'Büyük maç pazar akşamı oynandı.' },
      { key: 's2', en: 'All the tickets were sold in one day.', tr: 'Bütün biletler bir günde satıldı.' },
      { key: 's3', en: 'It was watched by millions of people on TV.', tr: 'Maç televizyonda milyonlarca kişi tarafından izlendi.' },
      { key: 's4', en: 'The first goal was scored by our captain.', tr: 'İlk gol kaptanımız tarafından atıldı.' },
      { key: 's5', en: 'Then one of our players was hurt.', tr: 'Sonra oyuncularımızdan biri sakatlandı.' },
      { key: 's6', en: 'A penalty was given to the other team.', tr: 'Rakip takıma penaltı verildi.' },
      { key: 's7', en: 'The penalty was saved by our goalkeeper.', tr: 'Penaltı kalecimiz tarafından kurtarıldı.' },
      { key: 's8', en: 'No red cards were shown in the match.', tr: 'Maçta hiç kırmızı kart gösterilmedi.' },
      { key: 's9', en: "Our second goal wasn't allowed because of offside.", tr: 'İkinci golümüz ofsayt yüzünden geçerli sayılmadı.' },
      { key: 's10', en: 'In the end, our team won the match.', tr: 'Sonunda maçı bizim takım kazandı.' },
      { key: 's11', en: 'Our captain was chosen as the best player.', tr: 'Kaptanımız maçın en iyi oyuncusu seçildi.' },
      { key: 's12', en: 'Was the match watched in your house too?', tr: 'Sizin evde de maç izlendi mi?', alts: ['Was the match watched at your house too?'] },
    ],
  },
  {
    id: 'passive-phone',
    title: 'Telefonumun yolculuğu',
    icon: 'phone-portrait-outline',
    sentences: [
      { key: 's1', en: 'My phone was designed in America.', tr: "Telefonum Amerika'da tasarlandı." },
      { key: 's2', en: "But it wasn't made there.", tr: 'Ama orada üretilmedi.' },
      { key: 's3', en: 'It was made in China.', tr: "Çin'de üretildi." },
      { key: 's4', en: 'Its parts are made in many different countries.', tr: 'Parçaları birçok farklı ülkede üretilir.' },
      { key: 's5', en: 'They are put together in one big factory.', tr: 'Büyük bir fabrikada birleştirilir.', alts: ['They are assembled in one big factory.'] },
      { key: 's6', en: 'Every phone is tested before it leaves the factory.', tr: 'Her telefon fabrikadan çıkmadan önce test edilir.' },
      { key: 's7', en: 'Then the phones are sent all over the world.', tr: 'Sonra telefonlar dünyanın her yerine gönderilir.', alts: ['Then the phones are shipped all over the world.'] },
      { key: 's8', en: 'Mine was given to me as a birthday present.', tr: 'Benimki bana doğum günü hediyesi olarak verildi.' },
      { key: 's9', en: 'The screen was broken last month.', tr: 'Geçen ay ekranı kırıldı.' },
      { key: 's10', en: 'It was repaired in a small shop near my house.', tr: 'Evimin yakınındaki küçük bir dükkânda tamir edildi.' },
      { key: 's11', en: "Old phones aren't thrown away in my family.", tr: 'Bizim ailede eski telefonlar atılmaz.' },
      { key: 's12', en: 'Where was your phone made?', tr: 'Senin telefonun nerede üretildi?' },
    ],
  },
  {
    id: 'passive-work',
    title: 'İşte tuhaf bir gün',
    icon: 'clipboard-outline',
    sentences: [
      { key: 's1', en: 'Yesterday was a strange day at work.', tr: 'Dün işte tuhaf bir gün geçti.' },
      { key: 's2', en: 'The morning meeting was canceled at the last minute.', tr: 'Sabah toplantısı son dakikada iptal edildi.', alts: ['The morning meeting was cancelled at the last minute.'] },
      { key: 's3', en: 'Nobody was told why.', tr: 'Kimseye nedeni söylenmedi.' },
      { key: 's4', en: 'Then a new manager was introduced to us.', tr: 'Sonra bize yeni bir müdür tanıtıldı.' },
      { key: 's5', en: 'She was hired from another company.', tr: 'Başka bir şirketten işe alındı.' },
      { key: 's6', en: 'At noon, lunch was brought to the office.', tr: 'Öğlen ofise yemek getirildi.' },
      { key: 's7', en: 'It was paid for by the company.', tr: 'Parası şirket tarafından ödendi.' },
      { key: 's8', en: 'In the afternoon, the internet was cut off for two hours.', tr: 'Öğleden sonra internet iki saat boyunca kesildi.' },
      { key: 's9', en: 'No emails were sent all afternoon.', tr: 'Bütün öğleden sonra hiç e-posta gönderilmedi.' },
      { key: 's10', en: "The problem was fixed at four o'clock.", tr: 'Sorun saat dörtte çözüldü.' },
      { key: 's11', en: 'At five, we were all sent home early.', tr: 'Saat beşte hepimiz erken eve gönderildik.' },
      { key: 's12', en: 'Are meetings often canceled at your company?', tr: 'Senin şirketinde toplantılar sık sık iptal edilir mi?', alts: ['Are meetings often cancelled at your company?'] },
    ],
  },
];
