import type { LadderTheme } from './types';

// Past Simple konusma merdiveni icerigi (elle yazildi). Bitmis gecmis olaylar,
// zaman ifadeleriyle; her tema 12 cumlelik bir konusma akisidir.
export const PAST_SIMPLE_THEMES: LadderTheme[] = [
  {
    id: 'past-last-weekend',
    title: 'Geçen hafta sonu',
    icon: 'bicycle-outline',
    sentences: [
      { key: 's1', en: 'Last weekend was really nice.', tr: 'Geçen hafta sonu gerçekten güzeldi.' },
      { key: 's2', en: 'On Saturday, I got up late.', tr: 'Cumartesi geç kalktım.', alts: ['On Saturday, I woke up late.'] },
      { key: 's3', en: 'I had breakfast with my family at eleven.', tr: 'On birde ailemle kahvaltı yaptım.' },
      { key: 's4', en: 'Then I cleaned my room and did the laundry.', tr: 'Sonra odamı temizledim ve çamaşırları yıkadım.' },
      { key: 's5', en: 'In the afternoon, I met my friends in the city center.', tr: 'Öğleden sonra arkadaşlarımla şehir merkezinde buluştum.' },
      { key: 's6', en: 'We walked by the sea and ate ice cream.', tr: 'Deniz kenarında yürüdük ve dondurma yedik.' },
      { key: 's7', en: "We didn't stay out late.", tr: 'Çok geç saate kadar dışarıda kalmadık.' },
      { key: 's8', en: 'I got home at nine and watched a film.', tr: 'Dokuzda eve geldim ve bir film izledim.', alts: ['I got home at nine and watched a movie.'] },
      { key: 's9', en: 'On Sunday, we visited my aunt in Bursa.', tr: "Pazar günü Bursa'daki teyzemi ziyaret ettik." },
      { key: 's10', en: 'She cooked a big lunch for us.', tr: 'Bize kocaman bir öğle yemeği pişirdi.' },
      { key: 's11', en: "We didn't take the car, we went by bus.", tr: 'Arabayla gitmedik, otobüsle gittik.' },
      { key: 's12', en: 'What did you do last weekend?', tr: 'Sen geçen hafta sonu ne yaptın?' },
    ],
  },
  {
    id: 'past-yesterday',
    title: 'Dünkü günüm',
    icon: 'time-outline',
    sentences: [
      { key: 's1', en: 'Yesterday was a very long day.', tr: 'Dün çok uzun bir gündü.' },
      { key: 's2', en: "My alarm didn't ring in the morning.", tr: 'Sabah alarmım çalmadı.' },
      { key: 's3', en: 'I woke up at eight and jumped out of bed.', tr: 'Sekizde uyandım ve yataktan fırladım.' },
      { key: 's4', en: "I didn't have time for breakfast.", tr: 'Kahvaltıya vaktim olmadı.', alts: ['I had no time for breakfast.'] },
      { key: 's5', en: 'I ran to the bus stop, but I missed the bus.', tr: 'Durağa koştum ama otobüsü kaçırdım.' },
      { key: 's6', en: 'So I took a taxi to work.', tr: 'Bu yüzden işe taksiyle gittim.', alts: ['So I went to work by taxi.'] },
      { key: 's7', en: 'I arrived at the office twenty minutes late.', tr: 'Ofise yirmi dakika geç vardım.' },
      { key: 's8', en: "Luckily, my boss didn't say anything.", tr: 'Neyse ki patronum bir şey demedi.' },
      { key: 's9', en: 'I worked hard all day and forgot about lunch.', tr: 'Bütün gün çok çalıştım ve öğle yemeğini unuttum.' },
      { key: 's10', en: 'In the evening, I made pasta at home.', tr: 'Akşam evde makarna yaptım.' },
      { key: 's11', en: 'I went to bed at ten because I was very tired.', tr: 'Çok yorgun olduğum için onda yattım.' },
      { key: 's12', en: 'How was your day yesterday?', tr: 'Senin dünün nasıl geçti?' },
    ],
  },
  {
    id: 'past-summer-holiday',
    title: 'Geçen yazki tatil',
    icon: 'airplane-outline',
    sentences: [
      { key: 's1', en: 'Last summer, we went to Antalya for a week.', tr: "Geçen yaz bir haftalığına Antalya'ya gittik." },
      { key: 's2', en: 'We flew there from Istanbul in the morning.', tr: "Sabah İstanbul'dan uçakla gittik." },
      { key: 's3', en: 'The flight took only one hour.', tr: 'Uçuş sadece bir saat sürdü.' },
      { key: 's4', en: 'We stayed in a small hotel near the beach.', tr: 'Plajın yakınındaki küçük bir otelde kaldık.', alts: ['We stayed at a small hotel near the beach.'] },
      { key: 's5', en: 'We swam in the sea every day.', tr: 'Her gün denizde yüzdük.' },
      { key: 's6', en: 'My kids played in the sand all day.', tr: 'Çocuklarım bütün gün kumda oynadı.', alts: ['My children played in the sand all day.'] },
      { key: 's7', en: 'One day, we visited the old town.', tr: 'Bir gün eski şehri gezdik.' },
      { key: 's8', en: "It was very hot, so we didn't walk much.", tr: 'Hava çok sıcaktı, bu yüzden pek yürümedik.' },
      { key: 's9', en: 'We ate fresh fish at a restaurant by the sea.', tr: 'Deniz kenarındaki bir restoranda taze balık yedik.' },
      { key: 's10', en: "The food was great, but it wasn't cheap.", tr: 'Yemekler harikaydı ama ucuz değildi.' },
      { key: 's11', en: "I didn't want to come back home.", tr: 'Eve dönmek istemedim.' },
      { key: 's12', en: 'Where did you go last summer?', tr: 'Sen geçen yaz nereye gittin?' },
    ],
  },
  {
    id: 'past-shopping-day',
    title: 'Alışverişe çıktım',
    icon: 'bag-handle-outline',
    sentences: [
      { key: 's1', en: 'Last Saturday, I went to a big shopping mall.', tr: 'Geçen cumartesi büyük bir alışveriş merkezine gittim.' },
      { key: 's2', en: 'I needed new shoes for work.', tr: 'İş için yeni ayakkabıya ihtiyacım vardı.' },
      { key: 's3', en: 'I looked in five or six shops.', tr: 'Beş altı mağazaya baktım.', alts: ['I went into five or six shops.'] },
      { key: 's4', en: 'I tried on a lot of shoes.', tr: 'Bir sürü ayakkabı denedim.' },
      { key: 's5', en: 'Then I found a nice black pair.', tr: 'Sonra güzel bir siyah ayakkabı buldum.' },
      { key: 's6', en: 'They were comfortable, but very expensive.', tr: 'Rahattı ama çok pahalıydı.' },
      { key: 's7', en: "I asked for a discount, but they didn't give me one.", tr: 'İndirim istedim ama yapmadılar.' },
      { key: 's8', en: 'In the end, I bought them anyway.', tr: 'Sonunda yine de aldım.' },
      { key: 's9', en: 'I also bought a shirt for my brother.', tr: 'Kardeşime de bir gömlek aldım.' },
      { key: 's10', en: 'After that, I had lunch at the food court.', tr: 'Ondan sonra yemek katında öğle yemeği yedim.' },
      { key: 's11', en: "I didn't spend much money on food.", tr: 'Yemeğe çok para harcamadım.' },
      { key: 's12', en: 'Did you buy anything last weekend?', tr: 'Sen geçen hafta sonu bir şey aldın mı?' },
    ],
  },
  {
    id: 'past-first-job',
    title: 'İlk işim',
    icon: 'briefcase-outline',
    sentences: [
      { key: 's1', en: 'I started my first job in 2019.', tr: "İlk işime 2019'da başladım." },
      { key: 's2', en: 'I worked at a small company in Izmir.', tr: "İzmir'de küçük bir şirkette çalıştım.", alts: ['I worked for a small company in Izmir.'] },
      { key: 's3', en: 'On my first day, I felt very nervous.', tr: 'İlk günümde çok heyecanlıydım.' },
      { key: 's4', en: "I didn't know anyone in the office.", tr: 'Ofiste kimseyi tanımıyordum.' },
      { key: 's5', en: 'My manager showed me my desk.', tr: 'Müdürüm bana masamı gösterdi.' },
      { key: 's6', en: 'A colleague took me to lunch.', tr: 'Bir iş arkadaşım beni öğle yemeğine götürdü.' },
      { key: 's7', en: 'She helped me a lot in my first month.', tr: 'İlk ayımda bana çok yardım etti.' },
      { key: 's8', en: "The salary wasn't very high.", tr: 'Maaş pek yüksek değildi.' },
      { key: 's9', en: 'But I learned a lot of new things.', tr: 'Ama bir sürü yeni şey öğrendim.' },
      { key: 's10', en: 'I stayed there for two years.', tr: 'Orada iki yıl kaldım.', alts: ['I worked there for two years.'] },
      { key: 's11', en: 'Then I moved to Istanbul and found a new job.', tr: "Sonra İstanbul'a taşındım ve yeni bir iş buldum." },
      { key: 's12', en: 'When did you start your first job?', tr: 'Sen ilk işine ne zaman başladın?' },
    ],
  },
  {
    id: 'past-birthday-surprise',
    title: 'Doğum günü sürprizi',
    icon: 'gift-outline',
    sentences: [
      { key: 's1', en: "Last Friday was my sister's birthday.", tr: 'Geçen cuma kız kardeşimin doğum günüydü.' },
      { key: 's2', en: 'We planned a surprise party for her.', tr: 'Onun için sürpriz bir parti planladık.' },
      { key: 's3', en: 'My mother made a big chocolate cake.', tr: 'Annem büyük bir çikolatalı pasta yaptı.' },
      { key: 's4', en: 'I bought balloons and decorated the living room.', tr: 'Balon aldım ve oturma odasını süsledim.' },
      { key: 's5', en: 'We invited ten of her friends.', tr: 'On arkadaşını davet ettik.' },
      { key: 's6', en: 'They came at seven and waited in the dark.', tr: 'Yedide geldiler ve karanlıkta beklediler.' },
      { key: 's7', en: 'My sister came home at eight.', tr: 'Kız kardeşim sekizde eve geldi.', alts: ['My sister got home at eight.'] },
      { key: 's8', en: "She didn't know anything about the party.", tr: 'Partiden hiç haberi yoktu.' },
      { key: 's9', en: 'When she turned on the light, she saw everyone.', tr: 'Işığı açınca herkesi gördü.' },
      { key: 's10', en: 'She was very surprised and started to cry.', tr: 'Çok şaşırdı ve ağlamaya başladı.', alts: ['She was very surprised and started crying.'] },
      { key: 's11', en: "We didn't go to bed until two.", tr: 'Gece ikiye kadar yatmadık.' },
      { key: 's12', en: 'Did you have a party on your last birthday?', tr: 'Son doğum gününde parti yaptın mı?' },
    ],
  },
];
