import type { LadderTheme } from './types';

// Past Continuous konusma merdiveni icerigi (elle yazildi). Gecmiste suren bir
// is ve onu kesen olay (when / while); her tema 12 cumlelik bir anlatidir.
export const PAST_CONTINUOUS_THEMES: LadderTheme[] = [
  {
    id: 'pastc-caught-in-rain',
    title: 'Yağmura yakalandım',
    icon: 'rainy-outline',
    sentences: [
      { key: 's1', en: 'Yesterday, I was walking home from work.', tr: 'Dün işten eve yürüyordum.' },
      { key: 's2', en: 'The sun was shining, and I was listening to music.', tr: 'Güneş parlıyordu ve müzik dinliyordum.' },
      { key: 's3', en: "I wasn't carrying an umbrella.", tr: 'Yanımda şemsiye yoktu.', alts: ["I didn't have an umbrella."] },
      { key: 's4', en: 'Suddenly, it started to rain very hard.', tr: 'Birden çok şiddetli yağmur başladı.', alts: ['Suddenly, it started raining very hard.'] },
      { key: 's5', en: 'People were running to the bus stops.', tr: 'İnsanlar otobüs duraklarına koşuyordu.' },
      { key: 's6', en: 'A man was selling umbrellas on the corner.', tr: 'Köşede bir adam şemsiye satıyordu.' },
      { key: 's7', en: 'I bought one, but the wind was blowing very hard.', tr: 'Bir tane aldım ama rüzgâr çok sert esiyordu.' },
      { key: 's8', en: 'While I was crossing the street, the umbrella broke.', tr: 'Karşıdan karşıya geçerken şemsiye kırıldı.' },
      { key: 's9', en: 'When I got home, I was shaking with cold.', tr: 'Eve vardığımda soğuktan titriyordum.' },
      { key: 's10', en: 'Water was dripping from my hair.', tr: 'Saçlarımdan su damlıyordu.' },
      { key: 's11', en: "My mother wasn't laughing, but my brother was.", tr: 'Annem gülmüyordu ama kardeşim gülüyordu.' },
      { key: 's12', en: 'What were you doing when the rain started?', tr: 'Yağmur başladığında sen ne yapıyordun?' },
    ],
  },
  {
    id: 'pastc-power-cut',
    title: 'Elektrikler kesildiğinde',
    icon: 'flash-off-outline',
    sentences: [
      { key: 's1', en: 'Last night, the power went off at nine.', tr: 'Dün akşam dokuzda elektrikler kesildi.', alts: ['Last night, the electricity went off at nine.'] },
      { key: 's2', en: 'At that moment, I was taking a shower.', tr: 'O sırada duş alıyordum.', alts: ['At that moment, I was having a shower.'] },
      { key: 's3', en: 'My father was watching a football match.', tr: 'Babam futbol maçı izliyordu.' },
      { key: 's4', en: 'My mother was talking to my aunt on the phone.', tr: 'Annem telefonda teyzemle konuşuyordu.' },
      { key: 's5', en: 'My little brother was playing a computer game.', tr: 'Küçük kardeşim bilgisayar oyunu oynuyordu.' },
      { key: 's6', en: 'He was winning, so he got very angry.', tr: 'Kazanıyordu, bu yüzden çok sinirlendi.' },
      { key: 's7', en: "We weren't expecting it at all.", tr: 'Bunu hiç beklemiyorduk.' },
      { key: 's8', en: 'We were sitting in the living room with candles.', tr: 'Oturma odasında mum ışığında oturuyorduk.' },
      { key: 's9', en: 'Our neighbors were looking out of their windows.', tr: 'Komşularımız pencerelerinden dışarı bakıyordu.' },
      { key: 's10', en: 'Nobody was complaining, we were just talking.', tr: 'Kimse şikâyet etmiyordu, sadece sohbet ediyorduk.' },
      { key: 's11', en: 'When the power came back, we were playing cards.', tr: 'Elektrikler geldiğinde iskambil oynuyorduk.' },
      { key: 's12', en: 'What were you doing during the power cut?', tr: 'Elektrik kesintisi sırasında sen ne yapıyordun?' },
    ],
  },
  {
    id: 'pastc-small-accident',
    title: 'Küçük bir kaza',
    icon: 'bandage-outline',
    sentences: [
      { key: 's1', en: 'Did I tell you about my accident?', tr: 'Sana kazamı anlattım mı?' },
      { key: 's2', en: 'Last week, I was riding my bike to work.', tr: 'Geçen hafta bisikletle işe gidiyordum.', alts: ['Last week, I was cycling to work.'] },
      { key: 's3', en: 'It was raining, and the road was wet.', tr: 'Yağmur yağıyordu ve yol ıslaktı.' },
      { key: 's4', en: "I wasn't going very fast.", tr: 'Çok hızlı gitmiyordum.' },
      { key: 's5', en: 'A car was coming out of a side street.', tr: 'Ara sokaktan bir araba çıkıyordu.' },
      { key: 's6', en: "The driver wasn't looking at the road.", tr: 'Sürücü yola bakmıyordu.' },
      { key: 's7', en: 'He was looking at his phone.', tr: 'Telefonuna bakıyordu.' },
      { key: 's8', en: 'I stopped suddenly and fell off my bike.', tr: 'Birden durdum ve bisikletten düştüm.' },
      { key: 's9', en: 'Some people were waiting at the bus stop.', tr: 'Durakta birkaç kişi bekliyordu.' },
      { key: 's10', en: 'They ran to me while I was lying on the ground.', tr: 'Ben yerde yatarken bana koştular.' },
      { key: 's11', en: 'My knee was bleeding a little.', tr: 'Dizim biraz kanıyordu.' },
      { key: 's12', en: 'Luckily, I was wearing a helmet.', tr: 'Neyse ki kask takıyordum.' },
    ],
  },
  {
    id: 'pastc-phone-ringing',
    title: 'Telefonum hiç susmadı',
    icon: 'phone-portrait-outline',
    sentences: [
      { key: 's1', en: "Yesterday, my phone didn't stop ringing.", tr: 'Dün telefonum hiç susmadı.' },
      { key: 's2', en: 'It first rang while I was sleeping.', tr: 'İlk kez ben uyurken çaldı.' },
      { key: 's3', en: 'My boss was calling about a meeting.', tr: 'Patronum bir toplantı için arıyordu.' },
      { key: 's4', en: 'Then it rang again while I was having a shower.', tr: 'Sonra ben duş alırken yine çaldı.', alts: ['Then it rang again while I was taking a shower.'] },
      { key: 's5', en: 'At lunch, it rang while I was eating soup.', tr: 'Öğle yemeğinde ben çorba içerken yine çaldı.' },
      { key: 's6', en: 'My mother was calling to ask about dinner.', tr: 'Annem akşam yemeğini sormak için arıyordu.' },
      { key: 's7', en: 'In the afternoon, I was driving to a meeting.', tr: 'Öğleden sonra arabayla bir toplantıya gidiyordum.' },
      { key: 's8', en: "It rang again, but I wasn't wearing my headphones.", tr: 'Yine çaldı ama kulaklığım takılı değildi.' },
      { key: 's9', en: 'In the evening, I was finally relaxing on the sofa.', tr: 'Akşam sonunda kanepede dinleniyordum.' },
      { key: 's10', en: 'My best friend was calling to chat.', tr: 'En yakın arkadaşım sohbet etmek için arıyordu.' },
      { key: 's11', en: 'We were talking when my battery died.', tr: 'Konuşurken şarjım bitti.' },
      { key: 's12', en: 'Were you trying to call me yesterday too?', tr: 'Dün sen de mi beni aramaya çalışıyordun?' },
    ],
  },
  {
    id: 'pastc-old-friend',
    title: 'Eski bir arkadaşa rastladım',
    icon: 'walk-outline',
    sentences: [
      { key: 's1', en: 'Last Sunday, I was shopping at the market.', tr: 'Geçen pazar semt pazarında alışveriş yapıyordum.' },
      { key: 's2', en: 'I was buying tomatoes when someone called my name.', tr: 'Domates alırken biri bana adımla seslendi.' },
      { key: 's3', en: 'It was Mert, my old friend from school.', tr: "Seslenen, eski okul arkadaşım Mert'ti." },
      { key: 's4', en: 'He was carrying two big bags of fruit.', tr: 'Elinde iki büyük poşet meyve vardı.' },
      { key: 's5', en: "We weren't expecting to see each other.", tr: 'Birbirimizi görmeyi hiç beklemiyorduk.' },
      { key: 's6', en: 'While we were talking, his wife arrived.', tr: 'Biz konuşurken eşi geldi.' },
      { key: 's7', en: 'She was holding their baby.', tr: 'Bebeklerini kucağında tutuyordu.' },
      { key: 's8', en: "The baby wasn't crying, he was smiling at me.", tr: 'Bebek ağlamıyordu, bana gülümsüyordu.' },
      { key: 's9', en: 'We went to a coffee shop and talked for an hour.', tr: 'Bir kafeye gittik ve bir saat sohbet ettik.' },
      { key: 's10', en: 'While we were drinking tea, he told me about his job.', tr: 'Çay içerken bana işini anlattı.' },
      { key: 's11', en: 'When I got home, my mother was waiting for the tomatoes.', tr: 'Eve vardığımda annem domatesleri bekliyordu.' },
      { key: 's12', en: 'What were you doing on Sunday morning?', tr: 'Sen pazar sabahı ne yapıyordun?' },
    ],
  },
  {
    id: 'pastc-airport-delay',
    title: 'Havalimanında rötar',
    icon: 'hourglass-outline',
    sentences: [
      { key: 's1', en: 'Last month, I was waiting for a flight to Izmir.', tr: 'Geçen ay İzmir uçağını bekliyordum.' },
      { key: 's2', en: 'Hundreds of people were sitting at the gates.', tr: 'Kapıların önünde yüzlerce kişi oturuyordu.' },
      { key: 's3', en: 'I was reading a book and drinking coffee.', tr: 'Kitap okuyor, kahve içiyordum.' },
      { key: 's4', en: 'Suddenly, the screen showed a two-hour delay.', tr: 'Birden ekranda iki saatlik rötar çıktı.' },
      { key: 's5', en: 'Some passengers were complaining to the staff.', tr: 'Bazı yolcular görevlilere şikâyet ediyordu.' },
      { key: 's6', en: 'A little boy was running between the seats.', tr: 'Küçük bir çocuk koltukların arasında koşuyordu.' },
      { key: 's7', en: "His mother wasn't watching him, she was sleeping.", tr: 'Annesi ona bakmıyordu, uyuyordu.' },
      { key: 's8', en: 'While I was waiting, I tried to call you.', tr: 'Beklerken seni aramaya çalıştım.' },
      { key: 's9', en: "You weren't answering your phone.", tr: 'Telefonunu açmıyordun.' },
      { key: 's10', en: 'What were you doing at that time?', tr: 'O sırada ne yapıyordun?', alts: ['What were you doing then?'] },
      { key: 's11', en: 'We finally took off at nine in the evening.', tr: 'Sonunda akşam dokuzda havalandık.' },
      { key: 's12', en: 'When we landed, it was raining in Izmir.', tr: "İndiğimizde İzmir'de yağmur yağıyordu." },
    ],
  },
];
