import type { LadderTheme } from './types';

// Present Perfect konusma merdiveni icerigi (elle yazildi): deneyimler
// (ever/never), yeni haberler (just/already/yet), bitmemis zaman (today, this
// week) ve for/since. Her tema 12 cumlelik bir konusma akisidir.
export const PRESENT_PERFECT_THEMES: LadderTheme[] = [
  {
    id: 'pp-travel-experiences',
    title: 'Gezdiğim yerler',
    icon: 'globe-outline',
    sentences: [
      { key: 's1', en: "I've seen a lot of places in Turkey.", tr: "Türkiye'de pek çok yer gördüm." },
      { key: 's2', en: "I've been to Ankara many times.", tr: "Ankara'ya defalarca gittim." },
      { key: 's3', en: "I've visited Antalya twice.", tr: "Antalya'ya iki kez gittim.", alts: ["I've been to Antalya twice."] },
      { key: 's4', en: "But I've never seen the Black Sea.", tr: "Ama Karadeniz'i hiç görmedim." },
      { key: 's5', en: 'Have you ever been to Trabzon?', tr: "Hiç Trabzon'a gittin mi?" },
      { key: 's6', en: 'My brother has lived there for three years.', tr: 'Kardeşim üç yıldır orada yaşıyor.' },
      { key: 's7', en: 'He has invited me many times.', tr: 'Beni birçok kez davet etti.' },
      { key: 's8', en: "I haven't visited him yet.", tr: 'Onu henüz ziyaret etmedim.' },
      { key: 's9', en: "I've only been abroad once.", tr: 'Yurt dışına sadece bir kez çıktım.' },
      { key: 's10', en: 'We went to Greece last summer.', tr: "Geçen yaz Yunanistan'a gittik." },
      { key: 's11', en: "I've already planned my next trip.", tr: 'Bir sonraki gezimi şimdiden planladım.' },
      { key: 's12', en: 'Which cities have you visited?', tr: 'Sen hangi şehirleri gezdin?' },
    ],
  },
  {
    id: 'pp-good-news',
    title: 'Güzel haberler',
    icon: 'megaphone-outline',
    sentences: [
      { key: 's1', en: 'I have some great news today.', tr: 'Bugün çok güzel haberlerim var.' },
      { key: 's2', en: "I've finally found a new job.", tr: 'Sonunda yeni bir iş buldum.' },
      { key: 's3', en: 'The company has just called me.', tr: 'Şirket az önce beni aradı.' },
      { key: 's4', en: "I've already told my parents.", tr: 'Aileme haber verdim bile.' },
      { key: 's5', en: "But I haven't told my boss yet.", tr: 'Ama patronuma henüz söylemedim.' },
      { key: 's6', en: 'My sister has also passed her driving test.', tr: 'Kız kardeşim de ehliyet sınavını geçti.' },
      { key: 's7', en: "She hasn't bought a car yet.", tr: 'Henüz araba almadı.' },
      { key: 's8', en: 'She has saved some money for it.', tr: 'Bunun için biraz para biriktirdi.' },
      { key: 's9', en: 'And my best friend has just had a baby!', tr: 'Bir de en yakın arkadaşımın daha yeni bebeği oldu!' },
      { key: 's10', en: 'Have you heard the news?', tr: 'Sen haberi duydun mu?' },
      { key: 's11', en: "I've already bought a present for the baby.", tr: 'Bebek için şimdiden bir hediye aldım.' },
      { key: 's12', en: 'What has happened in your life this month?', tr: 'Bu ay senin hayatında neler oldu?' },
    ],
  },
  {
    id: 'pp-guests-tonight',
    title: 'Misafir hazırlığı',
    icon: 'checkmark-done-outline',
    sentences: [
      { key: 's1', en: 'Our guests are coming at eight tonight.', tr: 'Misafirlerimiz bu akşam saat sekizde geliyor.' },
      { key: 's2', en: "I've already cleaned the living room.", tr: 'Oturma odasını çoktan temizledim.' },
      { key: 's3', en: 'My father has just come back from the market.', tr: 'Babam az önce pazardan döndü.' },
      { key: 's4', en: 'He has bought fresh fruit and bread.', tr: 'Taze meyve ve ekmek aldı.' },
      { key: 's5', en: "I haven't made the dessert yet.", tr: 'Tatlıyı henüz yapmadım.' },
      { key: 's6', en: 'My mother has already cooked the rice.', tr: 'Annem pilavı çoktan pişirdi.' },
      { key: 's7', en: 'Has anyone set the table yet?', tr: 'Sofrayı kuran oldu mu?' },
      { key: 's8', en: 'No, nobody has done it yet.', tr: 'Hayır, henüz kimse kurmadı.' },
      { key: 's9', en: "I've just washed the glasses.", tr: 'Bardakları az önce yıkadım.' },
      { key: 's10', en: 'My sister has sent a message from the bus.', tr: 'Kız kardeşim otobüsten mesaj attı.' },
      { key: 's11', en: 'She has bought a cake for us.', tr: 'Bize pasta almış.' },
      { key: 's12', en: "I think we've done everything now.", tr: 'Sanırım artık her şeyi yaptık.' },
    ],
  },
  {
    id: 'pp-new-foods',
    title: 'Denediğim yemekler',
    icon: 'pizza-outline',
    sentences: [
      { key: 's1', en: 'I love trying new food.', tr: 'Yeni yemekler denemeye bayılırım.' },
      { key: 's2', en: "I've eaten sushi a few times.", tr: 'Birkaç kez suşi yedim.' },
      { key: 's3', en: "I've tried Indian food too, and I loved it.", tr: 'Hint yemeğini de denedim ve bayıldım.' },
      { key: 's4', en: "But I've never eaten snails.", tr: 'Ama hiç salyangoz yemedim.' },
      { key: 's5', en: 'Have you ever eaten Mexican food?', tr: 'Sen hiç Meksika yemeği yedin mi?', alts: ['Have you ever tried Mexican food?'] },
      { key: 's6', en: 'My friend has been to Mexico twice.', tr: "Arkadaşım iki kez Meksika'ya gitti." },
      { key: 's7', en: 'She has taught me a few Mexican recipes.', tr: 'Bana birkaç Meksika tarifi öğretti.' },
      { key: 's8', en: "I haven't cooked them at home yet.", tr: 'Onları henüz evde yapmadım.' },
      { key: 's9', en: "I've tried three new recipes this week.", tr: 'Bu hafta üç yeni tarif denedim.' },
      { key: 's10', en: 'My brother has asked for the chicken recipe.', tr: 'Kardeşim tavuk tarifini istedi.' },
      { key: 's11', en: "I've bought a new cookbook today.", tr: 'Bugün yeni bir yemek kitabı aldım.' },
      { key: 's12', en: 'What have you eaten today?', tr: 'Sen bugün ne yedin?' },
    ],
  },
  {
    id: 'pp-busy-week',
    title: 'Yoğun bir hafta',
    icon: 'today-outline',
    sentences: [
      { key: 's1', en: 'It has been a very busy week.', tr: 'Çok yoğun bir hafta oldu.' },
      { key: 's2', en: "I've worked late every day this week.", tr: 'Bu hafta her gün geç saate kadar çalıştım.' },
      { key: 's3', en: "I've had three meetings today.", tr: 'Bugün üç toplantım oldu.' },
      { key: 's4', en: "I've only eaten a sandwich today.", tr: 'Bugün sadece bir sandviç yedim.' },
      { key: 's5', en: "I've drunk four cups of coffee so far.", tr: 'Şimdiye kadar dört fincan kahve içtim.' },
      { key: 's6', en: "I haven't been to the gym this week.", tr: 'Bu hafta spor salonuna gitmedim.' },
      { key: 's7', en: "My phone hasn't stopped ringing all day.", tr: 'Telefonum bütün gün susmadı.' },
      { key: 's8', en: "I've answered more than fifty emails.", tr: 'Elliden fazla e-postaya cevap verdim.' },
      { key: 's9', en: "But I've finished my big project.", tr: 'Ama büyük projemi bitirdim.' },
      { key: 's10', en: 'My boss has already read it.', tr: 'Patronum onu okudu bile.' },
      { key: 's11', en: "I've decided to rest this weekend.", tr: 'Bu hafta sonu dinlenmeye karar verdim.' },
      { key: 's12', en: 'How has your week been?', tr: 'Senin haftan nasıl geçti?' },
    ],
  },
  {
    id: 'pp-years-in-my-life',
    title: 'Yıllardır hayatımda',
    icon: 'hourglass-outline',
    sentences: [
      { key: 's1', en: "I've lived in Istanbul for ten years.", tr: "On yıldır İstanbul'da yaşıyorum." },
      { key: 's2', en: "We've been in this flat since last spring.", tr: 'Geçen bahardan beri bu dairedeyiz.', alts: ["We've been in this apartment since last spring."] },
      { key: 's3', en: "I've made a lot of friends here.", tr: 'Burada çok arkadaş edindim.' },
      { key: 's4', en: "I haven't been to my hometown for two years.", tr: 'İki yıldır memleketime gitmedim.' },
      { key: 's5', en: "I've had the same job for five years.", tr: 'Beş yıldır aynı işteyim.' },
      { key: 's6', en: 'My boss has been at this company for twenty years.', tr: 'Patronum yirmi yıldır bu şirkette.' },
      { key: 's7', en: 'She has always been kind to me.', tr: 'Bana karşı hep nazik oldu.' },
      { key: 's8', en: "I haven't had a holiday since last summer.", tr: 'Geçen yazdan beri tatil yapmadım.', alts: ["I haven't had a vacation since last summer."] },
      { key: 's9', en: "I've known my best friend since primary school.", tr: 'En yakın arkadaşımı ilkokuldan beri tanıyorum.' },
      { key: 's10', en: "We've been friends for almost thirty years.", tr: 'Neredeyse otuz yıldır arkadaşız.' },
      { key: 's11', en: "I've had my cat for four years.", tr: 'Dört yıldır bir kedim var.' },
      { key: 's12', en: 'How long have you lived here?', tr: 'Sen ne zamandır burada yaşıyorsun?' },
    ],
  },
];
