import type { LadderTheme } from './types';

// Present Simple konusma merdiveni icerigi (elle yazildi). Her tema, o konuda
// art arda anlatilabilecek 12 cumlelik bir konusma akisidir.
export const PRESENT_SIMPLE_THEMES: LadderTheme[] = [
  {
    id: 'morning-routine',
    title: 'Sabah rutinim',
    icon: 'sunny-outline',
    sentences: [
      { key: 's1', en: 'I usually wake up around seven in the morning.', tr: 'Genellikle sabah yedi civarı uyanırım.', alts: ['I usually get up around seven in the morning.'], cue: 'sabah 7 civarı, uyanmak' },
      { key: 's2', en: 'I check my phone for a few minutes before I get up.', tr: 'Kalkmadan önce birkaç dakika telefonuma bakarım.', cue: 'kalkmadan önce, telefon, birkaç dakika' },
      { key: 's3', en: "I don't always feel like getting up early.", tr: 'Erken kalkmak her zaman içimden gelmez.', cue: 'erken kalkmak, her zaman değil, isteksiz' },
      { key: 's4', en: 'Do you hit the snooze button in the morning?', tr: 'Sabahları alarmı erteler misin?', cue: 'soru: alarmı ertelemek, sabahları' },
      { key: 's5', en: 'I quickly wash my face and brush my teeth.', tr: 'Hızlıca yüzümü yıkar ve dişlerimi fırçalarım.', cue: 'hızlıca, yüz yıkamak, diş fırçalamak' },
      { key: 's6', en: 'I sometimes shower in the morning, but I usually do it at night.', tr: 'Bazen sabahları duş alırım ama genellikle akşamları alırım.', cue: 'bazen sabah duş, genelde gece duş' },
      { key: 's7', en: "I don't spend much time choosing my clothes.", tr: 'Kıyafet seçerken fazla vakit harcamam.', cue: 'kıyafet seçmek, az vakit' },
      { key: 's8', en: 'My mother always makes fresh tea for breakfast.', tr: 'Annem kahvaltı için her zaman taze çay demler.', cue: 'annem, her zaman, taze çay, kahvaltı' },
      { key: 's9', en: 'We usually have breakfast together, although I sometimes skip it when I\'m late.', tr: 'Genellikle birlikte kahvaltı yaparız ama geç kaldığımda bazen atlarım.', cue: 'genelde birlikte kahvaltı, ama geç kalınca bazen atlarım' },
      { key: 's10', en: "I don't drink coffee in the morning because it makes me feel anxious.", tr: 'Sabahları kahve içmem çünkü beni tedirgin ediyor.', cue: 'sabah kahve içmem, çünkü tedirgin eder' },
      { key: 's11', en: 'Even though I wake up early, I always leave in a rush.', tr: 'Erken kalkmama rağmen her zaman aceleyle çıkarım.', cue: 'erken kalksam da, her zaman aceleyle çıkarım' },
      { key: 's12', en: 'What does your morning routine look like?', tr: 'Senin sabah rutinin nasıl?', cue: 'soru: senin sabah rutinin' },
    ],
  },
  {
    id: 'work-school',
    title: 'İşim ve okulum',
    icon: 'briefcase-outline',
    sentences: [
      { key: 's1', en: 'I work in an office in Istanbul.', tr: "İstanbul'da bir ofiste çalışırım.", cue: 'İstanbul, ofis, çalışmak' },
      { key: 's2', en: 'My office is near the metro station.', tr: 'Ofisim metro istasyonunun yakınında.', cue: 'ofis, metro yakını' },
      { key: 's3', en: 'I start work at nine every day.', tr: 'Her gün dokuzda işe başlarım.', cue: 'her gün saat 9, işe başlamak' },
      { key: 's4', en: 'I usually check my emails first.', tr: 'Genellikle önce e-postalarımı kontrol ederim.', cue: 'önce, e-posta kontrol' },
      { key: 's5', en: 'My boss often has meetings in the morning.', tr: 'Patronum sabahları sık sık toplantı yapar.', cue: 'patron, sık sık, sabah toplantı' },
      { key: 's6', en: "I don't like long meetings.", tr: 'Uzun toplantıları sevmem.', cue: 'uzun toplantı, sevmem' },
      { key: 's7', en: "We have lunch at one o'clock.", tr: 'Saat birde öğle yemeği yeriz.', alts: ["We eat lunch at one o'clock."], cue: 'saat 1, öğle yemeği' },
      { key: 's8', en: 'I finish work at six and go home.', tr: 'Altıda işi bitiririm ve eve giderim.', cue: 'saat 6, iş bitmek, eve gitmek' },
      { key: 's9', en: 'My sister goes to university in Ankara.', tr: "Kız kardeşim Ankara'da üniversiteye gider.", cue: 'kız kardeş, Ankara, üniversite' },
      { key: 's10', en: 'She studies English and history.', tr: 'O İngilizce ve tarih okur.', cue: 'o, İngilizce ve tarih okur' },
      { key: 's11', en: "She doesn't live with us, so she calls us every night.", tr: 'Bizimle yaşamaz, bu yüzden bizi her akşam arar.', cue: 'bizimle yaşamaz, her akşam arar' },
      { key: 's12', en: 'Do you work or go to school?', tr: 'Sen çalışıyor musun, yoksa okula mı gidiyorsun?', cue: 'soru: çalışıyor musun, okula mı gidiyorsun' },
    ],
  },
  {
    id: 'family',
    title: 'Ailem',
    icon: 'people-outline',
    sentences: [
      { key: 's1', en: 'I have a small family.', tr: 'Küçük bir ailem var.', cue: 'küçük aile' },
      { key: 's2', en: 'I live with my parents and my brother.', tr: 'Annem, babam ve erkek kardeşimle yaşarım.', cue: 'anne baba, erkek kardeş, birlikte yaşamak' },
      { key: 's3', en: 'My father works at a hospital.', tr: 'Babam bir hastanede çalışır.', cue: 'baba, hastane, çalışmak' },
      { key: 's4', en: 'He leaves home very early in the morning.', tr: 'Sabah çok erken evden çıkar.', cue: 'o, sabah çok erken, evden çıkmak' },
      { key: 's5', en: 'My mother teaches math at a primary school.', tr: 'Annem bir ilkokulda matematik öğretir.', cue: 'anne, ilkokul, matematik öğretmek' },
      { key: 's6', en: 'She loves her job and her students.', tr: 'İşini ve öğrencilerini çok sever.', cue: 'o, işini ve öğrencilerini sever' },
      { key: 's7', en: 'My brother is fifteen and he plays basketball.', tr: 'Kardeşim on beş yaşında ve basketbol oynar.', cue: 'kardeş, 15 yaşında, basketbol oynar' },
      { key: 's8', en: "He doesn't like homework at all.", tr: 'Ödevden hiç hoşlanmaz.', cue: 'o, ödevi hiç sevmez' },
      { key: 's9', en: 'My grandparents live in a village near Bursa.', tr: 'Büyükannemle büyükbabam Bursa yakınında bir köyde yaşar.', cue: 'büyükanne büyükbaba, Bursa yakını köy' },
      { key: 's10', en: 'We always visit them in the summer.', tr: 'Yazın onları her zaman ziyaret ederiz.', cue: 'yazın, her zaman, ziyaret' },
      { key: 's11', en: "We don't see them very often in winter.", tr: 'Kışın onları pek sık görmeyiz.', cue: 'kışın, pek sık görmeyiz' },
      { key: 's12', en: 'Does your family live in the same city?', tr: 'Ailen aynı şehirde mi yaşıyor?', cue: 'soru: ailen aynı şehirde mi' },
    ],
  },
  {
    id: 'food',
    title: 'Yemek alışkanlıklarım',
    icon: 'restaurant-outline',
    sentences: [
      { key: 's1', en: 'I really love Turkish food.', tr: 'Türk yemeklerine bayılırım.', cue: 'Türk yemeği, çok sevmek' },
      { key: 's2', en: 'I usually eat three meals a day.', tr: 'Genellikle günde üç öğün yemek yerim.', cue: 'günde 3 öğün' },
      { key: 's3', en: 'For breakfast, I eat cheese, olives and bread.', tr: 'Kahvaltıda peynir, zeytin ve ekmek yerim.', cue: 'kahvaltı: peynir, zeytin, ekmek' },
      { key: 's4', en: 'I often have soup for lunch.', tr: 'Öğle yemeğinde sık sık çorba içerim.', alts: ['I often eat soup for lunch.'], cue: 'öğle yemeği, sık sık çorba' },
      { key: 's5', en: 'My mother cooks dinner every evening.', tr: 'Annem her akşam yemek pişirir.', alts: ['My mother makes dinner every evening.'], cue: 'anne, her akşam yemek pişirir' },
      { key: 's6', en: 'She makes the best rice in the family.', tr: 'Ailedeki en güzel pilavı o yapar.', cue: 'o, ailenin en iyi pilavı' },
      { key: 's7', en: "I don't eat fast food very often.", tr: 'Hazır yemeği pek sık yemem.', cue: 'hazır yemek, pek sık değil' },
      { key: 's8', en: 'My brother never eats vegetables.', tr: 'Kardeşim asla sebze yemez.', cue: 'kardeş, asla sebze yemez' },
      { key: 's9', en: 'He says they taste bad.', tr: 'Tatlarının kötü olduğunu söyler.', cue: 'o, tadı kötü der' },
      { key: 's10', en: 'I drink a lot of water every day.', tr: 'Her gün bol su içerim.', cue: 'her gün bol su' },
      { key: 's11', en: 'We sometimes eat at a restaurant on Fridays.', tr: 'Cuma günleri bazen restoranda yeriz.', cue: 'cuma günleri, bazen restoran' },
      { key: 's12', en: 'What do you usually eat for dinner?', tr: 'Akşam yemeğinde genellikle ne yersin?', cue: 'soru: akşam genelde ne yersin' },
    ],
  },
  {
    id: 'weekend',
    title: 'Hafta sonum',
    icon: 'cafe-outline',
    sentences: [
      { key: 's1', en: "I love weekends because I don't work.", tr: 'Hafta sonlarını severim çünkü çalışmam.', cue: 'hafta sonu sevmek, çünkü çalışmamak' },
      { key: 's2', en: 'On Saturdays, I sleep until ten.', tr: 'Cumartesileri ona kadar uyurum.', cue: "cumartesi, saat 10'a kadar uyumak" },
      { key: 's3', en: 'Then I have a long breakfast with my family.', tr: 'Sonra ailemle uzun bir kahvaltı yaparım.', cue: 'sonra, ailece uzun kahvaltı' },
      { key: 's4', en: 'In the afternoon, I meet my friends at a coffee shop.', tr: 'Öğleden sonra arkadaşlarımla bir kafede buluşurum.', cue: 'öğleden sonra, kafede arkadaşlarla buluşmak' },
      { key: 's5', en: 'We drink coffee and talk for hours.', tr: 'Kahve içeriz ve saatlerce sohbet ederiz.', cue: 'kahve içmek, saatlerce sohbet' },
      { key: 's6', en: 'Sometimes we take a walk by the sea.', tr: 'Bazen deniz kenarında yürüyüş yaparız.', alts: ['Sometimes we go for a walk by the sea.'], cue: 'bazen, deniz kenarı, yürüyüş' },
      { key: 's7', en: 'My sister goes shopping on Saturday afternoons.', tr: 'Kız kardeşim cumartesi öğleden sonraları alışverişe gider.', cue: 'kız kardeş, cumartesi öğleden sonra, alışveriş' },
      { key: 's8', en: 'On Sundays, we visit my grandmother.', tr: 'Pazar günleri büyükannemi ziyaret ederiz.', cue: 'pazar, büyükanne ziyareti' },
      { key: 's9', en: 'She always cooks something delicious for us.', tr: 'Bize her zaman lezzetli bir şey pişirir.', cue: 'o, her zaman lezzetli bir şey pişirir' },
      { key: 's10', en: "I don't do any housework on Sundays.", tr: 'Pazarları hiç ev işi yapmam.', cue: 'pazar, hiç ev işi yapmam' },
      { key: 's11', en: 'Do you go out on weekends?', tr: 'Hafta sonları dışarı çıkar mısın?', cue: 'soru: hafta sonu dışarı çıkar mısın' },
      { key: 's12', en: 'I go to bed early on Sunday nights.', tr: 'Pazar akşamları erken yatarım.', cue: 'pazar akşamı, erken yatmak' },
    ],
  },
  {
    id: 'hobbies',
    title: 'Hobilerim',
    icon: 'football-outline',
    sentences: [
      { key: 's1', en: 'I have a few hobbies.', tr: 'Birkaç hobim var.', cue: 'birkaç hobi' },
      { key: 's2', en: 'I play football with my friends on Tuesdays.', tr: 'Salı günleri arkadaşlarımla futbol oynarım.', cue: 'salı, arkadaşlarla futbol' },
      { key: 's3', en: 'We play in a small park near my house.', tr: 'Evimin yakınındaki küçük bir parkta oynarız.', cue: 'ev yakını, küçük park, oynamak' },
      { key: 's4', en: 'I also read books before bed.', tr: 'Yatmadan önce kitap da okurum.', cue: 'yatmadan önce, kitap okumak' },
      { key: 's5', en: 'I usually read for thirty minutes.', tr: 'Genellikle otuz dakika okurum.', cue: 'genelde 30 dakika okumak' },
      { key: 's6', en: 'My best friend plays the guitar very well.', tr: 'En yakın arkadaşım çok iyi gitar çalar.', cue: 'en yakın arkadaş, gitar, çok iyi' },
      { key: 's7', en: 'He practices every day after work.', tr: 'Her gün işten sonra pratik yapar.', cue: 'o, işten sonra her gün pratik' },
      { key: 's8', en: "I don't play any instruments, but I love music.", tr: 'Hiç enstrüman çalmam ama müziği çok severim.', cue: 'enstrüman çalmam, ama müziği severim' },
      { key: 's9', en: 'I often listen to music on the bus.', tr: 'Otobüste sık sık müzik dinlerim.', cue: 'otobüste, sık sık müzik' },
      { key: 's10', en: 'My sister takes photos of the city.', tr: 'Kız kardeşim şehrin fotoğraflarını çeker.', cue: 'kız kardeş, şehrin fotoğrafı' },
      { key: 's11', en: "She doesn't like sports at all.", tr: 'Spordan hiç hoşlanmaz.', cue: 'o, sporu hiç sevmez' },
      { key: 's12', en: 'What do you do in your free time?', tr: 'Boş zamanında ne yaparsın?', cue: 'soru: boş zamanda ne yaparsın' },
    ],
  },
  {
    id: 'home',
    title: 'Evim',
    icon: 'home-outline',
    sentences: [
      { key: 's1', en: 'I live in a flat in Istanbul.', tr: "İstanbul'da bir dairede yaşarım.", alts: ['I live in an apartment in Istanbul.'], cue: 'İstanbul, daire, yaşamak' },
      { key: 's2', en: 'Our flat has three bedrooms and a small balcony.', tr: 'Dairemizde üç yatak odası ve küçük bir balkon var.', cue: 'daire: 3 yatak odası, küçük balkon' },
      { key: 's3', en: 'My room is small, but it gets a lot of sun.', tr: 'Odam küçük ama çok güneş alır.', cue: 'oda küçük, ama çok güneş' },
      { key: 's4', en: 'I study at a desk next to the window.', tr: 'Pencerenin yanındaki bir masada ders çalışırım.', cue: 'pencere yanı, masa, ders çalışmak' },
      { key: 's5', en: 'We usually sit in the living room in the evening.', tr: 'Akşamları genellikle oturma odasında otururuz.', cue: 'akşam, genelde oturma odası' },
      { key: 's6', en: 'My father watches the news on TV there.', tr: 'Babam orada televizyonda haberleri izler.', cue: 'baba, orada, haber izler' },
      { key: 's7', en: 'My mother often drinks tea on the balcony.', tr: 'Annem sık sık balkonda çay içer.', cue: 'anne, sık sık, balkonda çay' },
      { key: 's8', en: "We don't have a garden, so we grow flowers there.", tr: 'Bahçemiz yok, bu yüzden orada çiçek yetiştiririz.', cue: 'bahçe yok, orada çiçek yetiştirmek' },
      { key: 's9', en: 'I clean my room every Saturday.', tr: 'Her cumartesi odamı temizlerim.', cue: 'her cumartesi, oda temizlemek' },
      { key: 's10', en: 'My brother never cleans his room.', tr: 'Kardeşim odasını asla temizlemez.', cue: 'kardeş, asla oda temizlemez' },
      { key: 's11', en: "Our neighbors don't make much noise.", tr: 'Komşularımız pek gürültü yapmaz.', cue: 'komşular, pek gürültü yapmaz' },
      { key: 's12', en: 'Do you live in a house or a flat?', tr: 'Müstakil evde mi yaşıyorsun, dairede mi?', alts: ['Do you live in a house or an apartment?'], cue: 'soru: müstakil ev mi, daire mi' },
    ],
  },
  {
    id: 'city-transport',
    title: 'Şehrim ve ulaşım',
    icon: 'bus-outline',
    sentences: [
      { key: 's1', en: 'Istanbul is a very big and busy city.', tr: 'İstanbul çok büyük ve kalabalık bir şehir.', cue: 'İstanbul, çok büyük ve kalabalık' },
      { key: 's2', en: 'I go to work by metro every day.', tr: 'Her gün metroyla işe giderim.', alts: ['I take the metro to work every day.'], cue: 'her gün, metro, işe gitmek' },
      { key: 's3', en: 'The station is five minutes from my house.', tr: 'İstasyon evime beş dakika uzaklıkta.', cue: 'istasyon, evden 5 dakika' },
      { key: 's4', en: 'The trains usually come every few minutes.', tr: 'Trenler genellikle birkaç dakikada bir gelir.', cue: 'trenler, genelde birkaç dakikada bir' },
      { key: 's5', en: 'In the morning, the metro is always very crowded.', tr: 'Sabahları metro her zaman çok kalabalıktır.', cue: 'sabah, metro, her zaman çok kalabalık' },
      { key: 's6', en: 'I sometimes take the ferry to the other side.', tr: 'Bazen karşıya vapurla geçerim.', cue: 'bazen, karşıya, vapur' },
      { key: 's7', en: 'I love the ferry because the view is beautiful.', tr: 'Vapuru çok severim çünkü manzara çok güzel.', cue: 'vapuru severim, çünkü manzara güzel' },
      { key: 's8', en: "My brother doesn't like the bus, so he rides a bike.", tr: 'Kardeşim otobüsü sevmez, bu yüzden bisiklete biner.', cue: 'kardeş, otobüsü sevmez, bisiklete biner' },
      { key: 's9', en: 'My father drives to work, but the traffic is terrible.', tr: 'Babam işe arabayla gider ama trafik berbattır.', cue: 'baba, arabayla işe, trafik kötü' },
      { key: 's10', en: 'It often takes him an hour to get home.', tr: 'Eve varması sık sık bir saat sürer.', cue: 'eve varması, sık sık 1 saat' },
      { key: 's11', en: "I don't drive in the city center.", tr: 'Şehir merkezinde araba kullanmam.', cue: 'şehir merkezi, araba kullanmam' },
      { key: 's12', en: 'How do you get to work?', tr: 'İşe nasıl gidersin?', cue: 'soru: işe nasıl gidersin' },
    ],
  },
  {
    id: 'friends',
    title: 'Arkadaşlarım',
    icon: 'chatbubbles-outline',
    sentences: [
      { key: 's1', en: 'I have three close friends.', tr: 'Üç yakın arkadaşım var.', cue: '3 yakın arkadaş' },
      { key: 's2', en: 'We meet every Friday evening.', tr: 'Her cuma akşamı buluşuruz.', cue: 'her cuma akşamı, buluşmak' },
      { key: 's3', en: 'We usually go to a coffee shop near the park.', tr: 'Genellikle parkın yakınındaki bir kafeye gideriz.', cue: 'genelde, park yakını kafe' },
      { key: 's4', en: 'One of my friends works as a nurse.', tr: 'Arkadaşlarımdan biri hemşire olarak çalışır.', cue: 'arkadaşlardan biri, hemşire' },
      { key: 's5', en: 'She works at night, so she often feels tired.', tr: 'Geceleri çalışır, bu yüzden sık sık yorgun hisseder.', cue: 'o, gece çalışır, sık sık yorgun' },
      { key: 's6', en: 'My other friend lives near my house.', tr: 'Diğer arkadaşım evimin yakınında oturur.', cue: 'diğer arkadaş, ev yakınım' },
      { key: 's7', en: 'He always helps me when I have a problem.', tr: 'Bir sorunum olduğunda bana her zaman yardım eder.', cue: 'o, sorunum olunca her zaman yardım' },
      { key: 's8', en: 'We talk on the phone almost every day.', tr: 'Neredeyse her gün telefonda konuşuruz.', cue: 'neredeyse her gün, telefonda konuşmak' },
      { key: 's9', en: "We don't agree on everything, but we never fight.", tr: 'Her konuda aynı fikirde değiliz ama asla kavga etmeyiz.', cue: 'her konuda aynı fikirde değiliz, ama hiç kavga etmeyiz' },
      { key: 's10', en: 'We sometimes play board games at my house.', tr: 'Bazen bizim evde kutu oyunları oynarız.', cue: 'bazen, evimde kutu oyunu' },
      { key: 's11', en: "My friends don't like horror films.", tr: 'Arkadaşlarım korku filmlerini sevmez.', alts: ["My friends don't like horror movies."], cue: 'arkadaşlarım, korku filmini sevmez' },
      { key: 's12', en: 'Do you see your friends often?', tr: 'Arkadaşlarını sık görür müsün?', cue: 'soru: arkadaşlarını sık görür müsün' },
    ],
  },
  {
    id: 'evening-routine',
    title: 'Akşam rutinim',
    icon: 'moon-outline',
    sentences: [
      { key: 's1', en: 'I get home at about half past six.', tr: 'Altı buçuk civarında eve gelirim.', cue: 'altı buçuk civarı, eve gelmek' },
      { key: 's2', en: 'First, I change my clothes and wash my hands.', tr: 'Önce kıyafetlerimi değiştiririm ve ellerimi yıkarım.', cue: 'önce, kıyafet değiştirmek, el yıkamak' },
      { key: 's3', en: "We have dinner at seven o'clock.", tr: 'Saat yedide akşam yemeği yeriz.', alts: ["We eat dinner at seven o'clock."], cue: 'saat 7, akşam yemeği' },
      { key: 's4', en: 'After dinner, my father washes the dishes.', tr: 'Akşam yemeğinden sonra babam bulaşıkları yıkar.', cue: 'yemekten sonra, baba, bulaşık yıkar' },
      { key: 's5', en: 'I usually drink a cup of tea on the sofa.', tr: 'Genellikle kanepede bir bardak çay içerim.', cue: 'genelde, kanepede, bir bardak çay' },
      { key: 's6', en: 'My mother watches her favorite series on TV.', tr: 'Annem televizyonda en sevdiği diziyi izler.', cue: 'anne, en sevdiği dizi, TV' },
      { key: 's7', en: "I don't watch TV very much.", tr: 'Pek televizyon izlemem.', cue: 'pek TV izlemem' },
      { key: 's8', en: 'I study English for an hour instead.', tr: 'Onun yerine bir saat İngilizce çalışırım.', cue: 'onun yerine, 1 saat İngilizce' },
      { key: 's9', en: 'Then I prepare my bag for the next day.', tr: 'Sonra ertesi gün için çantamı hazırlarım.', cue: 'sonra, ertesi gün çantası' },
      { key: 's10', en: 'I never drink coffee in the evening.', tr: 'Akşamları asla kahve içmem.', cue: 'akşam, asla kahve içmem' },
      { key: 's11', en: 'Do you go to bed late?', tr: 'Geç yatar mısın?', cue: 'soru: geç yatar mısın' },
      { key: 's12', en: 'I usually go to bed at eleven.', tr: 'Genellikle on birde yatarım.', cue: "genelde, saat 11'de yatmak" },
    ],
  },
];
