import type { LadderTheme } from './types';

// Present Continuous konusma merdiveni icerigi (elle yazildi). Su an olan ya da
// bu aralar suren isler; her tema 12 cumlelik bir konusma akisidir.
export const PRESENT_CONTINUOUS_THEMES: LadderTheme[] = [
  {
    id: 'pc-right-now',
    title: 'Şu anda evde',
    icon: 'tv-outline',
    sentences: [
      { key: 's1', en: "I'm sitting on the sofa right now.", tr: 'Şu anda kanepede oturuyorum.' },
      { key: 's2', en: 'My mother is cooking dinner in the kitchen.', tr: 'Annem mutfakta akşam yemeği pişiriyor.', alts: ['My mother is making dinner in the kitchen.'] },
      { key: 's3', en: "She's making lentil soup and rice.", tr: 'Mercimek çorbası ve pilav yapıyor.' },
      { key: 's4', en: 'My father is watching the news on TV.', tr: 'Babam televizyonda haberleri izliyor.' },
      { key: 's5', en: "My little brother isn't doing his homework.", tr: 'Küçük kardeşim ödevini yapmıyor.' },
      { key: 's6', en: "He's playing games on his phone again.", tr: 'Yine telefonunda oyun oynuyor.' },
      { key: 's7', en: 'Our cat is sleeping next to me.', tr: 'Kedimiz yanımda uyuyor.' },
      { key: 's8', en: "It's raining very hard outside.", tr: 'Dışarıda çok şiddetli yağmur yağıyor.' },
      { key: 's9', en: "I'm not doing anything special.", tr: 'Özel bir şey yapmıyorum.' },
      { key: 's10', en: "I'm just drinking tea and reading a book.", tr: 'Sadece çay içip kitap okuyorum.' },
      { key: 's11', en: 'What are you doing right now?', tr: 'Sen şu anda ne yapıyorsun?', alts: ['What are you doing now?'] },
      { key: 's12', en: 'Is it raining there too?', tr: 'Orada da yağmur yağıyor mu?' },
    ],
  },
  {
    id: 'pc-busy-office',
    title: 'Ofiste yoğun bir gün',
    icon: 'laptop-outline',
    sentences: [
      { key: 's1', en: "It's a busy day, and everyone is working hard.", tr: 'Bugün çok yoğun, herkes sıkı çalışıyor.' },
      { key: 's2', en: "I'm writing a long report for my boss.", tr: 'Patronum için uzun bir rapor yazıyorum.' },
      { key: 's3', en: 'My boss is talking to a customer on the phone.', tr: 'Patronum telefonda bir müşteriyle konuşuyor.' },
      { key: 's4', en: 'Two of my colleagues are having a meeting.', tr: 'İki iş arkadaşım toplantı yapıyor.', alts: ['Two of my colleagues are in a meeting.'] },
      { key: 's5', en: "The printer isn't working again.", tr: 'Yazıcı yine çalışmıyor.' },
      { key: 's6', en: 'A technician is trying to fix it.', tr: 'Bir teknisyen onu tamir etmeye çalışıyor.' },
      { key: 's7', en: "I'm drinking my third coffee of the day.", tr: 'Günün üçüncü kahvesini içiyorum.' },
      { key: 's8', en: "We aren't taking a lunch break today.", tr: 'Bugün öğle arası vermiyoruz.' },
      { key: 's9', en: 'The phone is ringing all the time.', tr: 'Telefon durmadan çalıyor.' },
      { key: 's10', en: 'My new colleague is learning the job quickly.', tr: 'Yeni iş arkadaşım işi hızla öğreniyor.' },
      { key: 's11', en: 'Are you working from home today?', tr: 'Sen bugün evden mi çalışıyorsun?' },
      { key: 's12', en: "I'm counting the minutes until six.", tr: 'Saat altıya kadar dakikaları sayıyorum.' },
    ],
  },
  {
    id: 'pc-phone-call',
    title: 'Telefonda arkadaşımla',
    icon: 'call-outline',
    sentences: [
      { key: 's1', en: "Hi, Elif! I'm calling you from the bus.", tr: 'Selam Elif! Seni otobüsten arıyorum.' },
      { key: 's2', en: "I'm going home after work.", tr: 'İş çıkışı eve gidiyorum.' },
      { key: 's3', en: "It's raining, and the bus is moving very slowly.", tr: 'Yağmur yağıyor ve otobüs çok yavaş ilerliyor.' },
      { key: 's4', en: "I'm standing because there are no empty seats.", tr: 'Boş koltuk olmadığı için ayakta duruyorum.', alts: ["I'm standing because there aren't any empty seats."] },
      { key: 's5', en: 'Sorry, a baby is crying next to me.', tr: 'Kusura bakma, yanımda bir bebek ağlıyor.' },
      { key: 's6', en: 'What are you doing at the moment?', tr: 'Sen şu an ne yapıyorsun?', alts: ['What are you doing right now?'] },
      { key: 's7', en: "Oh, you're cooking dinner. I'm so hungry!", tr: 'Aa, akşam yemeği yapıyorsun. Çok açım!' },
      { key: 's8', en: 'Is your brother helping you in the kitchen?', tr: 'Kardeşin mutfakta sana yardım ediyor mu?' },
      { key: 's9', en: "So he isn't helping, he's watching TV.", tr: 'Demek yardım etmiyor, televizyon izliyor.' },
      { key: 's10', en: 'My phone battery is dying.', tr: 'Telefonumun şarjı bitiyor.' },
      { key: 's11', en: "I'm not joking, it's at five percent.", tr: 'Şaka yapmıyorum, şarj yüzde beşte.' },
      { key: 's12', en: "Okay, I'm getting off the bus now. Bye!", tr: 'Tamam, şimdi otobüsten iniyorum. Görüşürüz!' },
    ],
  },
  {
    id: 'pc-these-days',
    title: 'Bu aralar',
    icon: 'calendar-outline',
    sentences: [
      { key: 's1', en: "These days, I'm working very hard.", tr: 'Bu aralar çok çalışıyorum.' },
      { key: 's2', en: "I'm also learning English online.", tr: 'Bir yandan da internetten İngilizce öğreniyorum.' },
      { key: 's3', en: "I'm watching a lot of films in English.", tr: 'Bol bol İngilizce film izliyorum.', alts: ["I'm watching a lot of movies in English."] },
      { key: 's4', en: 'My English is slowly getting better.', tr: 'İngilizcem yavaş yavaş gelişiyor.', alts: ['My English is slowly improving.'] },
      { key: 's5', en: 'My sister is staying with us this month.', tr: 'Kız kardeşim bu ay bizde kalıyor.' },
      { key: 's6', en: "She's looking for a new job in Istanbul.", tr: "İstanbul'da yeni bir iş arıyor." },
      { key: 's7', en: 'Our neighbors are painting their flat.', tr: 'Komşularımız evlerini boyuyor.' },
      { key: 's8', en: "I'm not sleeping well because of the noise.", tr: 'Gürültü yüzünden iyi uyuyamıyorum.' },
      { key: 's9', en: "I'm trying to eat more vegetables.", tr: 'Daha çok sebze yemeye çalışıyorum.' },
      { key: 's10', en: "I'm not eating much sugar at the moment.", tr: 'Şu sıralar pek şeker yemiyorum.' },
      { key: 's11', en: 'What are you doing these days?', tr: 'Sen bu aralar neler yapıyorsun?' },
      { key: 's12', en: 'Are you still working at the same place?', tr: 'Hâlâ aynı yerde mi çalışıyorsun?' },
    ],
  },
  {
    id: 'pc-park-sunday',
    title: 'Parkta pazar sabahı',
    icon: 'leaf-outline',
    sentences: [
      { key: 's1', en: "I'm sitting on a bench in the park.", tr: 'Parkta bir bankta oturuyorum.' },
      { key: 's2', en: "The sun is shining, and it's warm.", tr: 'Güneş parlıyor ve hava ılık.' },
      { key: 's3', en: 'Some children are playing football on the grass.', tr: 'Birkaç çocuk çimenlerde futbol oynuyor.' },
      { key: 's4', en: 'Their parents are drinking tea and watching them.', tr: 'Anne babaları çay içip onları izliyor.' },
      { key: 's5', en: 'An old man is feeding the birds.', tr: 'Yaşlı bir adam kuşlara yem veriyor.' },
      { key: 's6', en: 'Two young women are running around the lake.', tr: 'İki genç kadın göletin etrafında koşuyor.', alts: ['Two young women are jogging around the lake.'] },
      { key: 's7', en: 'A man is selling simit near the gate.', tr: 'Girişin yanında bir adam simit satıyor.' },
      { key: 's8', en: "I'm not reading my book, I'm just watching people.", tr: 'Kitabımı okumuyorum, sadece insanları izliyorum.' },
      { key: 's9', en: 'A little girl is crying next to the swings.', tr: 'Küçük bir kız salıncakların yanında ağlıyor.' },
      { key: 's10', en: 'Her father is trying to find her toy.', tr: 'Babası oyuncağını bulmaya çalışıyor.' },
      { key: 's11', en: 'Nobody is working today, everyone is relaxing.', tr: 'Bugün kimse çalışmıyor, herkes dinleniyor.' },
      { key: 's12', en: 'Are you enjoying your Sunday too?', tr: 'Sen de pazarın tadını çıkarıyor musun?' },
    ],
  },
  {
    id: 'pc-ferry-ride',
    title: 'Vapurla karşıya',
    icon: 'boat-outline',
    sentences: [
      { key: 's1', en: "I'm crossing to the other side by ferry.", tr: 'Vapurla karşıya geçiyorum.', alts: ["I'm taking the ferry to the other side."] },
      { key: 's2', en: "I'm sitting outside because the weather is nice.", tr: 'Hava güzel olduğu için dışarıda oturuyorum.' },
      { key: 's3', en: "I'm drinking tea and eating a simit.", tr: 'Çay içip simit yiyorum.' },
      { key: 's4', en: 'Seagulls are flying next to the ferry.', tr: 'Martılar vapurun yanında uçuyor.' },
      { key: 's5', en: 'A boy is throwing bread to the seagulls.', tr: 'Bir çocuk martılara ekmek atıyor.' },
      { key: 's6', en: 'Many tourists are taking photos of the city.', tr: 'Birçok turist şehrin fotoğraflarını çekiyor.' },
      { key: 's7', en: 'An old couple is holding hands.', tr: 'Yaşlı bir çift el ele tutuşuyor.' },
      { key: 's8', en: "They aren't talking, they're just looking at the sea.", tr: 'Konuşmuyorlar, sadece denize bakıyorlar.' },
      { key: 's9', en: "The wind is blowing, and it's getting cold.", tr: 'Rüzgâr esiyor ve hava soğuyor.' },
      { key: 's10', en: "I'm not wearing a jacket today.", tr: 'Bugün üstümde ceket yok.' },
      { key: 's11', en: "We're getting close to the other side now.", tr: 'Artık karşıya yaklaşıyoruz.' },
      { key: 's12', en: 'Are you waiting for me there?', tr: 'Beni orada mı bekliyorsun?' },
    ],
  },
];
