import type { LadderTheme } from './types';

// Present Continuous (gelecek icin kesinlesmis planlar) konusma merdiveni icerigi
// (elle yazildi). Her tema 12 cumlelik bir konusma akisidir; cumlelerin cogu
// acik bir gelecek zaman ifadesi tasir.
export const PRESENT_CONTINUOUS_FUTURE_THEMES: LadderTheme[] = [
  {
    id: 'pcf-busy-week',
    title: 'Bu haftaki planlarım',
    icon: 'calendar-outline',
    sentences: [
      { key: 's1', en: "I'm very busy this week.", tr: 'Bu hafta çok yoğunum.' },
      { key: 's2', en: "I'm meeting my boss on Monday morning.", tr: 'Pazartesi sabahı patronumla görüşüyorum.' },
      { key: 's3', en: "On Tuesday, I'm having lunch with an old friend.", tr: 'Salı günü eski bir arkadaşımla öğle yemeği yiyorum.' },
      { key: 's4', en: "I'm going to a concert on Wednesday night.", tr: 'Çarşamba akşamı bir konsere gidiyorum.' },
      { key: 's5', en: 'My parents are visiting us on Thursday.', tr: 'Perşembe günü annemle babam bizi ziyarete geliyor.', alts: ['My parents are coming to see us on Thursday.'] },
      { key: 's6', en: "We're having dinner together at eight.", tr: 'Saat sekizde birlikte akşam yemeği yiyoruz.' },
      { key: 's7', en: "I'm not working on Friday afternoon.", tr: 'Cuma öğleden sonra çalışmıyorum.' },
      { key: 's8', en: "Instead, I'm taking my little brother to a football match.", tr: 'Onun yerine küçük kardeşimi futbol maçına götürüyorum.' },
      { key: 's9', en: "On Saturday, we're flying to Izmir.", tr: "Cumartesi İzmir'e uçuyoruz." },
      { key: 's10', en: "We're staying with my aunt for two nights.", tr: 'İki gece teyzemde kalıyoruz.' },
      { key: 's11', en: "We aren't coming back until Monday.", tr: 'Pazartesiye kadar dönmüyoruz.' },
      { key: 's12', en: 'What are you doing this weekend?', tr: 'Sen bu hafta sonu ne yapıyorsun?' },
    ],
  },
  {
    id: 'pcf-weekend-trip',
    title: 'Hafta sonu gezisi',
    icon: 'car-outline',
    sentences: [
      { key: 's1', en: "We're going to Cappadocia this weekend.", tr: "Bu hafta sonu Kapadokya'ya gidiyoruz." },
      { key: 's2', en: "We're leaving on Friday evening after work.", tr: 'Cuma akşamı işten sonra yola çıkıyoruz.' },
      { key: 's3', en: 'My friend Mehmet is picking me up at six.', tr: 'Arkadaşım Mehmet beni altıda alıyor.' },
      { key: 's4', en: "We're staying in a small cave hotel for two nights.", tr: 'İki gece küçük bir mağara otelinde kalıyoruz.' },
      { key: 's5', en: "We're taking a balloon tour early on Saturday morning.", tr: 'Cumartesi sabahı erkenden balon turuna çıkıyoruz.' },
      { key: 's6', en: "So we're getting up at four o'clock.", tr: 'Bu yüzden saat dörtte kalkıyoruz.' },
      { key: 's7', en: "In the afternoon, we're visiting an underground city.", tr: 'Öğleden sonra bir yeraltı şehrini geziyoruz.' },
      { key: 's8', en: "We aren't eating at the hotel on Saturday night.", tr: 'Cumartesi akşamı otelde yemek yemiyoruz.' },
      { key: 's9', en: "We're having dinner at a small local restaurant.", tr: 'Küçük, yöresel bir restoranda akşam yemeği yiyoruz.' },
      { key: 's10', en: "We're driving back on Sunday afternoon.", tr: 'Pazar öğleden sonra arabayla dönüyoruz.' },
      { key: 's11', en: "I'm not working at all this weekend.", tr: 'Bu hafta sonu hiç çalışmıyorum.' },
      { key: 's12', en: 'Are you doing anything special this weekend?', tr: 'Bu hafta sonu özel bir şey yapıyor musun?' },
    ],
  },
  {
    id: 'pcf-doctor-appointment',
    title: 'Doktor randevum',
    icon: 'medkit-outline',
    sentences: [
      { key: 's1', en: "I'm seeing the doctor tomorrow morning.", tr: 'Yarın sabah doktora gidiyorum.', alts: ["I'm going to the doctor tomorrow morning."] },
      { key: 's2', en: 'My appointment is at half past nine.', tr: 'Randevum dokuz buçukta.' },
      { key: 's3', en: "I'm having a blood test before that.", tr: 'Ondan önce kan tahlili yaptırıyorum.' },
      { key: 's4', en: "So I'm not having breakfast tomorrow.", tr: 'Bu yüzden yarın kahvaltı yapmıyorum.' },
      { key: 's5', en: 'My brother is driving me to the hospital at nine.', tr: 'Kardeşim beni dokuzda hastaneye götürüyor.' },
      { key: 's6', en: "He's picking me up again at noon.", tr: 'Öğlen beni yine o alıyor.' },
      { key: 's7', en: "I'm not working until two o'clock.", tr: 'Saat ikiye kadar çalışmıyorum.' },
      { key: 's8', en: "At three, I'm meeting a customer.", tr: 'Saat üçte bir müşteriyle görüşüyorum.' },
      { key: 's9', en: "I'm also seeing the dentist on Friday.", tr: 'Cuma günü dişçiye de gidiyorum.', alts: ["I'm also going to the dentist on Friday."] },
      { key: 's10', en: 'My mother is coming with me.', tr: 'Annem de benimle geliyor.' },
      { key: 's11', en: "We're having lunch together after the appointment.", tr: 'Randevudan sonra birlikte öğle yemeği yiyoruz.' },
      { key: 's12', en: 'Are you joining us for lunch on Friday?', tr: 'Cuma günü öğle yemeğinde bize katılıyor musun?' },
    ],
  },
  {
    id: 'pcf-birthday-dinner',
    title: 'Doğum günü yemeği',
    icon: 'gift-outline',
    sentences: [
      { key: 's1', en: "It's my mother's birthday on Saturday.", tr: 'Cumartesi annemin doğum günü.' },
      { key: 's2', en: "We aren't eating at home that evening.", tr: 'O akşam evde yemek yemiyoruz.' },
      { key: 's3', en: "We're having dinner at a fish restaurant by the sea.", tr: 'Deniz kenarındaki bir balık restoranında akşam yemeği yiyoruz.' },
      { key: 's4', en: 'My brother is booking a table tomorrow.', tr: 'Masayı yarın kardeşim ayırtıyor.' },
      { key: 's5', en: 'My aunt and uncle are coming from Ankara on Friday.', tr: "Teyzemle eniştem cuma günü Ankara'dan geliyor." },
      { key: 's6', en: "They're staying with us for the weekend.", tr: 'Hafta sonu bizde kalıyorlar.' },
      { key: 's7', en: 'My sister is making a chocolate cake that morning.', tr: 'Kız kardeşim o sabah çikolatalı pasta yapıyor.' },
      { key: 's8', en: "I'm buying the flowers on Saturday afternoon.", tr: 'Çiçekleri cumartesi öğleden sonra ben alıyorum.' },
      { key: 's9', en: "My grandmother isn't coming because she's ill.", tr: 'Büyükannem hasta olduğu için gelmiyor.', alts: ["My grandmother isn't coming because she's sick."] },
      { key: 's10', en: "We're calling her from the restaurant.", tr: 'Onu restorandan arıyoruz.' },
      { key: 's11', en: "We're giving my mother a new watch.", tr: 'Anneme yeni bir saat hediye ediyoruz.' },
      { key: 's12', en: 'Are you coming to the dinner too?', tr: 'Sen de yemeğe geliyor musun?' },
    ],
  },
  {
    id: 'pcf-business-trip',
    title: 'İş seyahati',
    icon: 'airplane-outline',
    sentences: [
      { key: 's1', en: "I'm flying to Berlin on Monday morning.", tr: "Pazartesi sabahı Berlin'e uçuyorum." },
      { key: 's2', en: "My flight is leaving at seven o'clock.", tr: 'Uçağım saat yedide kalkıyor.', alts: ["My flight leaves at seven o'clock."] },
      { key: 's3', en: "I'm taking a taxi to the airport at five.", tr: 'Saat beşte havalimanına taksiyle gidiyorum.', alts: ["I'm going to the airport by taxi at five."] },
      { key: 's4', en: 'My colleague Emre is coming with me.', tr: 'İş arkadaşım Emre de benimle geliyor.' },
      { key: 's5', en: "We're meeting our German customers on Monday afternoon.", tr: 'Pazartesi öğleden sonra Alman müşterilerimizle görüşüyoruz.' },
      { key: 's6', en: "We're staying at a hotel near their office.", tr: 'Ofislerinin yakınındaki bir otelde kalıyoruz.' },
      { key: 's7', en: "On Tuesday, we're visiting their factory.", tr: 'Salı günü fabrikalarını geziyoruz.' },
      { key: 's8', en: "We aren't visiting the city center this time.", tr: 'Bu sefer şehir merkezini gezmiyoruz.' },
      { key: 's9', en: "We're having dinner with their manager on Tuesday night.", tr: 'Salı akşamı müdürleriyle akşam yemeği yiyoruz.' },
      { key: 's10', en: "I'm not staying there for the weekend.", tr: 'Hafta sonu orada kalmıyorum.' },
      { key: 's11', en: "I'm coming back on Wednesday evening.", tr: 'Çarşamba akşamı dönüyorum.' },
      { key: 's12', en: 'Are you picking me up from the airport on Wednesday?', tr: 'Çarşamba günü beni havalimanından alıyor musun?' },
    ],
  },
  {
    id: 'pcf-moving-house',
    title: 'Ev taşıma',
    icon: 'cube-outline',
    sentences: [
      { key: 's1', en: "We're moving to a new flat next week.", tr: 'Önümüzdeki hafta yeni bir daireye taşınıyoruz.', alts: ["We're moving to a new apartment next week."] },
      { key: 's2', en: 'The new flat is closer to my office.', tr: 'Yeni daire ofisime daha yakın.', alts: ['The new apartment is closer to my office.'] },
      { key: 's3', en: "We're signing the contract on Tuesday.", tr: 'Salı günü sözleşmeyi imzalıyoruz.' },
      { key: 's4', en: 'The owner is giving us the keys on Wednesday.', tr: 'Çarşamba günü ev sahibi anahtarları bize veriyor.' },
      { key: 's5', en: "I'm packing the kitchen on Thursday night.", tr: 'Perşembe akşamı mutfağı topluyorum.' },
      { key: 's6', en: "We aren't taking our old sofa with us.", tr: 'Eski kanepemizi götürmüyoruz.' },
      { key: 's7', en: 'My cousin is buying it on Friday.', tr: 'Cuma günü onu kuzenim alıyor.' },
      { key: 's8', en: 'A moving company is coming on Saturday morning.', tr: 'Cumartesi sabahı bir nakliye firması geliyor.' },
      { key: 's9', en: 'My friends are helping us on Sunday.', tr: 'Pazar günü arkadaşlarım bize yardım ediyor.' },
      { key: 's10', en: "We're ordering pizza for everyone in the evening.", tr: 'Akşam herkese pizza söylüyoruz.' },
      { key: 's11', en: "I'm not working next Monday.", tr: 'Önümüzdeki pazartesi çalışmıyorum.' },
      { key: 's12', en: 'Are you coming to our new home next weekend?', tr: 'Önümüzdeki hafta sonu yeni evimize geliyor musun?' },
    ],
  },
];
