import type { LadderTheme } from './types';

// Present Simple konusma merdiveni icerigi (elle yazildi). Her tema, o konuda
// art arda anlatilabilecek 12 cumlelik bir konusma akisidir.
export const PRESENT_SIMPLE_THEMES: LadderTheme[] = [
  // Sabah rutini: her olay ayri tema, tek sabit fiil. Ozne + siklik zarfi
  // degisir; olumlu / olumsuz / soru karisik. Ipucu = Ingilizce kelime
  // sirasinda yalin Turkce kelimeler: zarf fiilden once, "degil" / "mi"
  // yardimci fiil yerinde, soru kelimesi en basta. Son tema: baglacli uzun cumleler.
  {
    id: 'morning-wake-up',
    title: 'Uyanmak',
    icon: 'alarm-outline',
    sentences: [
      { key: 's1', en: 'I usually wake up at seven.', tr: 'Genelde yedide uyanırım.', cue: 'ben · genelde · uyanmak · saat 7' },
      { key: 's2', en: 'My brother sometimes wakes up at noon.', tr: 'Kardeşim bazen öğlen uyanır.', cue: 'kardeşim · bazen · uyanmak · öğlen' },
      { key: 's3', en: "I don't usually wake up before my alarm.", tr: 'Genelde alarmdan önce uyanmam.', cue: 'ben · değil · genelde · uyanmak · alarmdan önce' },
      { key: 's4', en: 'Do you usually wake up early?', tr: 'Genelde erken uyanır mısın?', cue: 'mi · sen · genelde · uyanmak · erken' },
      { key: 's5', en: 'My mother always wakes up first.', tr: 'Annem hep ilk uyanır.', cue: 'annem · her zaman · uyanmak · ilk' },
      { key: 's6', en: 'My sister never wakes up on time.', tr: 'Kız kardeşim asla zamanında uyanmaz.', cue: 'kız kardeşim · asla · uyanmak · zamanında' },
      { key: 's7', en: 'Does your father usually wake up early?', tr: 'Baban genelde erken uyanır mı?', cue: 'mi · baban · genelde · uyanmak · erken' },
      { key: 's8', en: 'We often wake up late on Sundays.', tr: 'Pazar günleri sık sık geç uyanırız.', cue: 'biz · sık sık · uyanmak · geç · pazar günleri' },
      { key: 's9', en: "He doesn't always wake up at eight.", tr: 'O her zaman sekizde uyanmaz.', alts: ["She doesn't always wake up at eight."], cue: 'o · değil · her zaman · uyanmak · saat 8' },
      { key: 's10', en: 'What time do you usually wake up?', tr: 'Genelde saat kaçta uyanırsın?', cue: 'saat kaçta · mi · sen · genelde · uyanmak' },
      { key: 's11', en: "They don't usually wake up before nine.", tr: 'Onlar genelde dokuzdan önce uyanmaz.', cue: 'onlar · değil · genelde · uyanmak · saat 9’dan önce' },
      { key: 's12', en: 'Does she sometimes wake up at night?', tr: 'O bazen gece uyanır mı?', alts: ['Does he sometimes wake up at night?'], cue: 'mi · o · bazen · uyanmak · gece' },
    ],
  },
  {
    id: 'morning-get-up',
    title: 'Yataktan kalkmak',
    icon: 'bed-outline',
    sentences: [
      { key: 's1', en: 'I usually get up right away.', tr: 'Genelde hemen kalkarım.', cue: 'ben · genelde · kalkmak · hemen' },
      { key: 's2', en: 'You usually get up late.', tr: 'Sen genelde geç kalkarsın.', cue: 'sen · genelde · kalkmak · geç' },
      { key: 's3', en: "I don't usually get up early on weekends.", tr: 'Hafta sonları genelde erken kalkmam.', cue: 'ben · değil · genelde · kalkmak · erken · hafta sonları' },
      { key: 's4', en: 'Do you usually get up late?', tr: 'Genelde geç mi kalkarsın?', cue: 'mi · sen · genelde · kalkmak · geç' },
      { key: 's5', en: 'My father always gets up at six.', tr: 'Babam her zaman altıda kalkar.', cue: 'babam · her zaman · kalkmak · saat 6' },
      { key: 's6', en: "My brother doesn't usually get up before ten.", tr: 'Kardeşim genelde saat ondan önce kalkmaz.', cue: 'kardeşim · değil · genelde · kalkmak · saat 10’dan önce' },
      { key: 's7', en: 'Does your sister usually get up early?', tr: 'Kız kardeşin genelde erken kalkar mı?', cue: 'mi · kız kardeşin · genelde · kalkmak · erken' },
      { key: 's8', en: 'I sometimes get up at noon on Sundays.', tr: 'Pazar günleri bazen öğlen kalkarım.', cue: 'ben · bazen · kalkmak · öğlen · pazar günleri' },
      { key: 's9', en: 'We rarely get up before eight.', tr: 'Nadiren sekizden önce kalkarız.', cue: 'biz · nadiren · kalkmak · saat 8’den önce' },
      { key: 's10', en: "She doesn't always get up when the alarm goes off.", tr: 'Alarm çalınca her zaman kalkmaz.', alts: ["He doesn't always get up when the alarm goes off."], cue: 'o · değil · her zaman · kalkmak · alarm çalınca' },
      { key: 's11', en: 'Do they usually get up early on weekdays?', tr: 'Hafta içi genelde erken kalkarlar mı?', cue: 'mi · onlar · genelde · kalkmak · erken · hafta içi' },
      { key: 's12', en: 'Why do you always get up so early?', tr: 'Neden hep bu kadar erken kalkıyorsun?', cue: 'neden · mi · sen · her zaman · kalkmak · bu kadar erken' },
    ],
  },
  {
    id: 'morning-check-phone',
    title: 'Telefona bakmak',
    icon: 'phone-portrait-outline',
    sentences: [
      { key: 's1', en: 'I always check my phone first thing in the morning.', tr: 'Sabah ilk iş her zaman telefonuma bakarım.', cue: 'ben · her zaman · telefona bakmak · sabah ilk iş' },
      { key: 's2', en: 'My sister usually checks her messages in bed.', tr: 'Kız kardeşim genelde yatakta mesajlarına bakar.', cue: 'kız kardeşim · genelde · mesajlarına bakmak · yatakta' },
      { key: 's3', en: "I don't usually check my email before breakfast.", tr: 'Kahvaltıdan önce genelde e-postama bakmam.', cue: 'ben · değil · genelde · e-postaya bakmak · kahvaltıdan önce' },
      { key: 's4', en: 'Do you usually check your phone in bed?', tr: 'Genelde yatakta telefonuna bakar mısın?', cue: 'mi · sen · genelde · telefona bakmak · yatakta' },
      { key: 's5', en: 'My father always checks the weather before he leaves.', tr: 'Babam çıkmadan önce hep hava durumuna bakar.', cue: 'babam · her zaman · hava durumuna bakmak · çıkmadan önce' },
      { key: 's6', en: 'He never checks the news in the morning.', tr: 'Sabahları asla haberlere bakmaz.', alts: ['She never checks the news in the morning.'], cue: 'o · asla · haberlere bakmak · sabahları' },
      { key: 's7', en: 'Does your mother often check her phone at breakfast?', tr: 'Annen kahvaltıda sık sık telefonuna bakar mı?', cue: 'mi · annen · sık sık · telefona bakmak · kahvaltıda' },
      { key: 's8', en: 'We sometimes check the traffic before we leave.', tr: 'Çıkmadan önce bazen trafiğe bakarız.', cue: 'biz · bazen · trafiğe bakmak · çıkmadan önce' },
      { key: 's9', en: "My brother doesn't always check his messages.", tr: 'Kardeşim mesajlarına her zaman bakmaz.', cue: 'kardeşim · değil · her zaman · mesajlarına bakmak' },
      { key: 's10', en: "They don't usually check their phones at the table.", tr: 'Sofrada genelde telefonlarına bakmazlar.', cue: 'onlar · değil · genelde · telefona bakmak · sofrada' },
      { key: 's11', en: 'How often do you check your phone in the morning?', tr: 'Sabahları ne sıklıkla telefonuna bakarsın?', cue: 'ne sıklıkla · mi · sen · telefona bakmak · sabahları' },
      { key: 's12', en: 'I rarely check social media before work.', tr: 'İşten önce sosyal medyaya nadiren bakarım.', cue: 'ben · nadiren · sosyal medyaya bakmak · işten önce' },
    ],
  },
  {
    id: 'morning-shower',
    title: 'Duş almak',
    icon: 'water-outline',
    sentences: [
      { key: 's1', en: 'I usually take a shower in the morning.', tr: 'Genelde sabahları duş alırım.', alts: ['I usually have a shower in the morning.', 'I usually shower in the morning.'], cue: 'ben · genelde · duş almak · sabahları' },
      { key: 's2', en: 'My brother always takes a long shower.', tr: 'Kardeşim hep uzun duş alır.', cue: 'kardeşim · her zaman · duş almak · uzun' },
      { key: 's3', en: "I don't always take a shower before work.", tr: 'İşten önce her zaman duş almam.', cue: 'ben · değil · her zaman · duş almak · işten önce' },
      { key: 's4', en: 'Do you usually take a shower in the morning or at night?', tr: 'Genelde sabah mı duş alırsın, akşam mı?', cue: 'mi · sen · genelde · duş almak · sabah mı akşam mı' },
      { key: 's5', en: 'My father sometimes takes a cold shower.', tr: 'Babam bazen soğuk duş alır.', cue: 'babam · bazen · duş almak · soğuk' },
      { key: 's6', en: 'She never takes a shower at night.', tr: 'Akşamları asla duş almaz.', alts: ['He never takes a shower at night.'], cue: 'o · asla · duş almak · akşamları' },
      { key: 's7', en: 'Does your sister usually take a shower before breakfast?', tr: 'Kız kardeşin genelde kahvaltıdan önce duş alır mı?', cue: 'mi · kız kardeşin · genelde · duş almak · kahvaltıdan önce' },
      { key: 's8', en: 'I often take a quick shower after I get up.', tr: 'Kalktıktan sonra sık sık kısa bir duş alırım.', cue: 'ben · sık sık · duş almak · kısa · kalktıktan sonra' },
      { key: 's9', en: "My brother doesn't usually take a shower in the morning.", tr: 'Kardeşim genelde sabahları duş almaz.', cue: 'kardeşim · değil · genelde · duş almak · sabahları' },
      { key: 's10', en: "We don't always take a shower before school.", tr: 'Okuldan önce her zaman duş almayız.', cue: 'biz · değil · her zaman · duş almak · okuldan önce' },
      { key: 's11', en: 'When does your brother usually take a shower?', tr: 'Kardeşin genelde ne zaman duş alır?', cue: 'ne zaman · mi · kardeşin · genelde · duş almak' },
      { key: 's12', en: 'Does he always take a shower after his morning run?', tr: 'Sabah koşusundan sonra hep duş alır mı?', alts: ['Does she always take a shower after her morning run?'], cue: 'mi · o · her zaman · duş almak · sabah koşusundan sonra' },
    ],
  },
  {
    id: 'morning-breakfast',
    title: 'Kahvaltı yapmak',
    icon: 'restaurant-outline',
    sentences: [
      { key: 's1', en: 'I usually have breakfast at home.', tr: 'Genelde evde kahvaltı yaparım.', cue: 'ben · genelde · kahvaltı yapmak · evde' },
      { key: 's2', en: 'My family always has breakfast together on Sundays.', tr: 'Ailem pazar günleri hep birlikte kahvaltı yapar.', cue: 'ailem · her zaman · kahvaltı yapmak · birlikte · pazar günleri' },
      { key: 's3', en: "I don't usually have breakfast on weekdays.", tr: 'Hafta içi genelde kahvaltı yapmam.', cue: 'ben · değil · genelde · kahvaltı yapmak · hafta içi' },
      { key: 's4', en: 'Do you always have breakfast before school?', tr: 'Okuldan önce hep kahvaltı yapar mısın?', cue: 'mi · sen · her zaman · kahvaltı yapmak · okuldan önce' },
      { key: 's5', en: 'My father sometimes has breakfast at work.', tr: 'Babam bazen işte kahvaltı yapar.', cue: 'babam · bazen · kahvaltı yapmak · işte' },
      { key: 's6', en: "My sister never has breakfast when she's late.", tr: 'Kız kardeşim geç kaldığında asla kahvaltı yapmaz.', cue: 'kız kardeşim · asla · kahvaltı yapmak · geç kalınca' },
      { key: 's7', en: 'Does your brother usually have breakfast?', tr: 'Kardeşin genelde kahvaltı yapar mı?', cue: 'mi · kardeşin · genelde · kahvaltı yapmak' },
      { key: 's8', en: 'We often have a big breakfast on Saturdays.', tr: 'Cumartesileri sık sık büyük bir kahvaltı yaparız.', cue: 'biz · sık sık · kahvaltı yapmak · büyük · cumartesileri' },
      { key: 's9', en: "He doesn't usually have breakfast before nine.", tr: 'Genelde dokuzdan önce kahvaltı yapmaz.', alts: ["She doesn't usually have breakfast before nine."], cue: 'o · değil · genelde · kahvaltı yapmak · saat 9’dan önce' },
      { key: 's10', en: "My mother doesn't always have breakfast with us.", tr: 'Annem her zaman bizimle kahvaltı yapmaz.', cue: 'annem · değil · her zaman · kahvaltı yapmak · bizimle' },
      { key: 's11', en: 'Where do you usually have breakfast on weekdays?', tr: 'Hafta içi genelde nerede kahvaltı yaparsın?', cue: 'nerede · mi · sen · genelde · kahvaltı yapmak · hafta içi' },
      { key: 's12', en: 'Do they often have breakfast out on weekends?', tr: 'Hafta sonları sık sık dışarıda kahvaltı yaparlar mı?', cue: 'mi · onlar · sık sık · kahvaltı yapmak · dışarıda · hafta sonları' },
    ],
  },
  {
    id: 'morning-tea-coffee',
    title: 'Çay, kahve içmek',
    icon: 'cafe-outline',
    sentences: [
      { key: 's1', en: 'I always drink tea with breakfast.', tr: 'Kahvaltıda her zaman çay içerim.', cue: 'ben · her zaman · çay içmek · kahvaltıda' },
      { key: 's2', en: 'My father usually drinks two cups of tea.', tr: 'Babam genelde iki bardak çay içer.', alts: ['My father usually drinks two glasses of tea.'], cue: 'babam · genelde · çay içmek · 2 bardak' },
      { key: 's3', en: "I don't usually drink coffee in the morning.", tr: 'Sabahları genelde kahve içmem.', cue: 'ben · değil · genelde · kahve içmek · sabahları' },
      { key: 's4', en: 'Do you usually drink tea or coffee in the morning?', tr: 'Sabahları genelde çay mı içersin, kahve mi?', cue: 'mi · sen · genelde · içmek · çay mı kahve mi · sabahları' },
      { key: 's5', en: 'My sister sometimes drinks coffee on the way to work.', tr: 'Kız kardeşim bazen işe giderken kahve içer.', cue: 'kız kardeşim · bazen · kahve içmek · işe giderken' },
      { key: 's6', en: 'My mother never drinks coffee on an empty stomach.', tr: 'Annem aç karnına asla kahve içmez.', cue: 'annem · asla · kahve içmek · aç karnına' },
      { key: 's7', en: 'Does your brother often drink coffee before school?', tr: 'Kardeşin okuldan önce sık sık kahve içer mi?', cue: 'mi · kardeşin · sık sık · kahve içmek · okuldan önce' },
      { key: 's8', en: 'We usually drink tea together after breakfast.', tr: 'Kahvaltıdan sonra genelde birlikte çay içeriz.', cue: 'biz · genelde · çay içmek · birlikte · kahvaltıdan sonra' },
      { key: 's9', en: "She doesn't usually drink milk.", tr: 'Genelde süt içmez.', alts: ["He doesn't usually drink milk."], cue: 'o · değil · genelde · süt içmek' },
      { key: 's10', en: "They don't always drink water when they wake up.", tr: 'Uyanınca her zaman su içmezler.', cue: 'onlar · değil · her zaman · su içmek · uyanınca' },
      { key: 's11', en: 'How many cups of tea do you usually drink?', tr: 'Genelde kaç bardak çay içersin?', alts: ['How many glasses of tea do you usually drink?'], cue: 'kaç bardak · mi · sen · genelde · çay içmek' },
      { key: 's12', en: 'Does he always drink a glass of water first?', tr: 'Önce hep bir bardak su içer mi?', alts: ['Does she always drink a glass of water first?'], cue: 'mi · o · her zaman · bir bardak su içmek · önce' },
    ],
  },
  {
    id: 'morning-get-dressed',
    title: 'Giyinmek',
    icon: 'shirt-outline',
    sentences: [
      { key: 's1', en: 'I usually get dressed after breakfast.', tr: 'Genelde kahvaltıdan sonra giyinirim.', cue: 'ben · genelde · giyinmek · kahvaltıdan sonra' },
      { key: 's2', en: 'My sister always gets dressed very slowly.', tr: 'Kız kardeşim hep çok yavaş giyinir.', cue: 'kız kardeşim · her zaman · giyinmek · çok yavaş' },
      { key: 's3', en: "I don't usually get dressed until the last minute.", tr: 'Genelde son dakikaya kadar giyinmem.', cue: 'ben · değil · genelde · giyinmek · son dakikaya kadar' },
      { key: 's4', en: 'Do you usually get dressed before or after breakfast?', tr: 'Genelde kahvaltıdan önce mi giyinirsin, sonra mı?', cue: 'mi · sen · genelde · giyinmek · kahvaltıdan önce mi sonra mı' },
      { key: 's5', en: 'My brother sometimes gets dressed in five minutes.', tr: 'Kardeşim bazen beş dakikada giyinir.', cue: 'kardeşim · bazen · giyinmek · 5 dakikada' },
      { key: 's6', en: 'My father never gets dressed in a hurry.', tr: 'Babam asla aceleyle giyinmez.', cue: 'babam · asla · giyinmek · aceleyle' },
      { key: 's7', en: 'Does your mother usually get dressed first?', tr: 'Annen genelde ilk giyinir mi?', cue: 'mi · annen · genelde · giyinmek · ilk' },
      { key: 's8', en: 'We often get dressed in the dark in winter.', tr: 'Kışın sık sık karanlıkta giyiniriz.', cue: 'biz · sık sık · giyinmek · karanlıkta · kışın' },
      { key: 's9', en: "He doesn't always get dressed right after he gets up.", tr: 'Kalkar kalkmaz her zaman giyinmez.', alts: ["She doesn't always get dressed right after she gets up."], cue: 'o · değil · her zaman · giyinmek · kalkar kalkmaz' },
      { key: 's10', en: "The kids don't usually get dressed without help.", tr: 'Çocuklar genelde yardımsız giyinmez.', cue: 'çocuklar · değil · genelde · giyinmek · yardımsız' },
      { key: 's11', en: 'Why do you always get dressed so late?', tr: 'Neden hep bu kadar geç giyiniyorsun?', cue: 'neden · mi · sen · her zaman · giyinmek · bu kadar geç' },
      { key: 's12', en: 'Does she usually get dressed in the bathroom?', tr: 'Genelde banyoda mı giyinir?', alts: ['Does he usually get dressed in the bathroom?'], cue: 'mi · o · genelde · giyinmek · banyoda' },
    ],
  },
  {
    id: 'morning-leave-house',
    title: 'Evden çıkmak',
    icon: 'exit-outline',
    sentences: [
      { key: 's1', en: 'I usually leave the house at eight.', tr: 'Genelde sekizde evden çıkarım.', cue: 'ben · genelde · evden çıkmak · saat 8' },
      { key: 's2', en: 'My father always leaves the house before us.', tr: 'Babam hep bizden önce evden çıkar.', cue: 'babam · her zaman · evden çıkmak · bizden önce' },
      { key: 's3', en: "I don't usually leave the house without breakfast.", tr: 'Genelde kahvaltı yapmadan evden çıkmam.', cue: 'ben · değil · genelde · evden çıkmak · kahvaltısız' },
      { key: 's4', en: 'Do you usually leave the house early?', tr: 'Genelde evden erken çıkar mısın?', cue: 'mi · sen · genelde · evden çıkmak · erken' },
      { key: 's5', en: 'My sister sometimes leaves the house without her keys.', tr: 'Kız kardeşim bazen anahtarsız evden çıkar.', cue: 'kız kardeşim · bazen · evden çıkmak · anahtarsız' },
      { key: 's6', en: 'My brother never leaves the house on time.', tr: 'Kardeşim asla zamanında evden çıkmaz.', cue: 'kardeşim · asla · evden çıkmak · zamanında' },
      { key: 's7', en: 'Does your mother usually leave the house first?', tr: 'Annen genelde evden ilk çıkar mı?', cue: 'mi · annen · genelde · evden çıkmak · ilk' },
      { key: 's8', en: 'We often leave the house together.', tr: 'Sık sık evden birlikte çıkarız.', cue: 'biz · sık sık · evden çıkmak · birlikte' },
      { key: 's9', en: "She doesn't always leave the house at the same time.", tr: 'Evden her zaman aynı saatte çıkmaz.', alts: ["He doesn't always leave the house at the same time."], cue: 'o · değil · her zaman · evden çıkmak · aynı saatte' },
      { key: 's10', en: "They don't usually leave the house before nine.", tr: 'Genelde dokuzdan önce evden çıkmazlar.', cue: 'onlar · değil · genelde · evden çıkmak · saat 9’dan önce' },
      { key: 's11', en: 'What time do you usually leave the house?', tr: 'Genelde saat kaçta evden çıkarsın?', cue: 'saat kaçta · mi · sen · genelde · evden çıkmak' },
      { key: 's12', en: 'Does he always leave the house in a rush?', tr: 'Evden hep aceleyle mi çıkar?', alts: ['Does she always leave the house in a rush?'], cue: 'mi · o · her zaman · evden çıkmak · aceleyle' },
    ],
  },
  {
    id: 'morning-commute',
    title: 'Otobüs, metro',
    icon: 'bus-outline',
    sentences: [
      { key: 's1', en: 'I usually take the bus to work.', tr: 'Genelde işe otobüsle giderim.', cue: 'ben · genelde · otobüsle gitmek · işe' },
      { key: 's2', en: 'My sister always takes the metro.', tr: 'Kız kardeşim her zaman metroyla gider.', cue: 'kız kardeşim · her zaman · metroyla gitmek' },
      { key: 's3', en: "I don't usually take a taxi in the morning.", tr: 'Sabahları genelde taksiye binmem.', cue: 'ben · değil · genelde · taksiye binmek · sabahları' },
      { key: 's4', en: 'Do you usually take the bus or the metro?', tr: 'Genelde otobüse mi binersin, metroya mı?', cue: 'mi · sen · genelde · binmek · otobüs mü metro mu' },
      { key: 's5', en: 'My father sometimes takes the ferry to work.', tr: 'Babam bazen işe vapurla gider.', cue: 'babam · bazen · vapurla gitmek · işe' },
      { key: 's6', en: 'My brother never takes the bus to school.', tr: 'Kardeşim okula asla otobüsle gitmez.', cue: 'kardeşim · asla · otobüsle gitmek · okula' },
      { key: 's7', en: 'Does your mother usually take the same bus?', tr: 'Annen genelde aynı otobüse mi biner?', cue: 'mi · annen · genelde · binmek · aynı otobüs' },
      { key: 's8', en: 'We often take the early bus to avoid traffic.', tr: 'Trafiğe takılmamak için sık sık erken otobüse bineriz.', cue: 'biz · sık sık · binmek · erken otobüs · trafikten kaçmak için' },
      { key: 's9', en: "He doesn't always take the metro.", tr: 'Her zaman metroyla gitmez.', alts: ["She doesn't always take the metro."], cue: 'o · değil · her zaman · metroyla gitmek' },
      { key: 's10', en: "They don't usually take the bus on rainy days.", tr: 'Yağmurlu günlerde genelde otobüse binmezler.', cue: 'onlar · değil · genelde · otobüse binmek · yağmurlu günlerde' },
      { key: 's11', en: 'Which bus do you usually take in the morning?', tr: 'Sabahları genelde hangi otobüse binersin?', cue: 'hangi otobüs · mi · sen · genelde · binmek · sabahları' },
      { key: 's12', en: "Does she usually take a taxi when she's late?", tr: 'Geç kalınca genelde taksiye biner mi?', alts: ["Does he usually take a taxi when he's late?"], cue: 'mi · o · genelde · taksiye binmek · geç kalınca' },
    ],
  },
  {
    id: 'morning-long',
    title: 'Sabahımı anlat',
    icon: 'link-outline',
    sentences: [
      { key: 's1', en: "I usually wake up at seven, but I don't get up until eight.", tr: 'Genelde yedide uyanırım ama sekize kadar kalkmam.', cue: 'ben · genelde · uyanmak · saat 7 · ama · ben · değil · kalkmak · 8’e kadar' },
      { key: 's2', en: 'My brother always gets up late, so he never has breakfast.', tr: 'Kardeşim hep geç kalkar, bu yüzden hiç kahvaltı yapmaz.', cue: 'kardeşim · her zaman · kalkmak · geç · bu yüzden · o · asla · kahvaltı yapmak' },
      { key: 's3', en: 'I always check my phone before I get up.', tr: 'Kalkmadan önce hep telefonuma bakarım.', cue: 'ben · her zaman · telefona bakmak · önce · ben · kalkmak' },
      { key: 's4', en: 'Although my father gets up early, he often leaves the house late.', tr: 'Babam erken kalkmasına rağmen sık sık evden geç çıkar.', cue: 'rağmen · babam · kalkmak · erken · o · sık sık · evden çıkmak · geç' },
      { key: 's5', en: "My sister doesn't usually have breakfast because she's never hungry.", tr: 'Kız kardeşim genelde kahvaltı yapmaz çünkü hiç aç olmaz.', cue: 'kız kardeşim · değil · genelde · kahvaltı yapmak · çünkü · o · asla · aç' },
      { key: 's6', en: 'When I wake up late, I usually skip breakfast.', tr: 'Geç uyandığımda genelde kahvaltıyı atlarım.', cue: '-dığında · ben · uyanmak · geç · ben · genelde · kahvaltıyı atlamak' },
      { key: 's7', en: 'We usually drink tea after we have breakfast.', tr: 'Kahvaltı yaptıktan sonra genelde çay içeriz.', cue: 'biz · genelde · çay içmek · sonra · biz · kahvaltı yapmak' },
      { key: 's8', en: "Even though I'm always tired, I never press snooze.", tr: 'Hep yorgun olmama rağmen alarmı asla ertelemem.', cue: 'rağmen · ben · her zaman · yorgun · ben · asla · alarmı ertelemek' },
      { key: 's9', en: 'My mother usually takes a shower before we wake up.', tr: 'Annem genelde biz uyanmadan önce duş alır.', cue: 'annem · genelde · duş almak · önce · biz · uyanmak' },
      { key: 's10', en: "He doesn't usually take the bus, so he often walks to work.", tr: 'Genelde otobüse binmez, bu yüzden sık sık işe yürüyerek gider.', alts: ["She doesn't usually take the bus, so she often walks to work."], cue: 'o · değil · genelde · otobüse binmek · bu yüzden · o · sık sık · yürümek · işe' },
      { key: 's11', en: 'Do you usually check your phone before you get dressed?', tr: 'Giyinmeden önce genelde telefonuna bakar mısın?', cue: 'mi · sen · genelde · telefona bakmak · önce · sen · giyinmek' },
      { key: 's12', en: 'Why do you always leave the house late when you get up early?', tr: 'Erken kalktığında neden hep evden geç çıkıyorsun?', cue: 'neden · mi · sen · her zaman · evden çıkmak · geç · -dığında · sen · kalkmak · erken' },
    ],
  },
  {
    id: 'work-school',
    title: 'İşim ve okulum',
    icon: 'briefcase-outline',
    sentences: [
      { key: 's1', en: 'I work in an office in Istanbul.', tr: "İstanbul'da bir ofiste çalışırım.", cue: 'İstanbul, ofis, çalışmak' },
      { key: 's2', en: 'My office is near the metro station.', tr: 'Ofisim metro istasyonunun yakınında.', cue: 'ofis, metro yakını' },
      { key: 's3', en: 'I start work at nine every day.', tr: 'Her gün dokuzda işe başlarım.', cue: 'her gün saat 9, işe başlamak' },
      { key: 's4', en: 'I usually check my emails first.', tr: 'Genellikle önce e-postalarımı kontrol ederim.', cue: 'önce, e-posta kontrol' },
      { key: 's5', en: 'My boss often has meetings in the morning.', tr: 'Patronum sabahları sık sık toplantı yapar.', cue: 'patron, sık sık, sabah toplantı' },
      { key: 's6', en: "I don't like long meetings.", tr: 'Uzun toplantıları sevmem.', cue: 'uzun toplantı, sevmem' },
      { key: 's7', en: "We have lunch at one o'clock.", tr: 'Saat birde öğle yemeği yeriz.', alts: ["We eat lunch at one o'clock."], cue: 'saat 1, öğle yemeği' },
      { key: 's8', en: 'I finish work at six and go home.', tr: 'Altıda işi bitiririm ve eve giderim.', cue: 'saat 6, iş bitmek, eve gitmek' },
      { key: 's9', en: 'My sister goes to university in Ankara.', tr: "Kız kardeşim Ankara'da üniversiteye gider.", cue: 'kız kardeş, Ankara, üniversite' },
      { key: 's10', en: 'She studies English and history.', tr: 'O İngilizce ve tarih okur.', cue: 'o, İngilizce ve tarih okur' },
      { key: 's11', en: "She doesn't live with us, so she calls us every night.", tr: 'Bizimle yaşamaz, bu yüzden bizi her akşam arar.', cue: 'bizimle yaşamaz, her akşam arar' },
      { key: 's12', en: 'Do you work or go to school?', tr: 'Sen çalışıyor musun, yoksa okula mı gidiyorsun?', cue: 'soru: çalışıyor musun, okula mı gidiyorsun' },
    ],
  },
  {
    id: 'family',
    title: 'Ailem',
    icon: 'people-outline',
    sentences: [
      { key: 's1', en: 'I have a small family.', tr: 'Küçük bir ailem var.', cue: 'küçük aile' },
      { key: 's2', en: 'I live with my parents and my brother.', tr: 'Annem, babam ve erkek kardeşimle yaşarım.', cue: 'anne baba, erkek kardeş, birlikte yaşamak' },
      { key: 's3', en: 'My father works at a hospital.', tr: 'Babam bir hastanede çalışır.', cue: 'baba, hastane, çalışmak' },
      { key: 's4', en: 'He leaves home very early in the morning.', tr: 'Sabah çok erken evden çıkar.', cue: 'o, sabah çok erken, evden çıkmak' },
      { key: 's5', en: 'My mother teaches math at a primary school.', tr: 'Annem bir ilkokulda matematik öğretir.', cue: 'anne, ilkokul, matematik öğretmek' },
      { key: 's6', en: 'She loves her job and her students.', tr: 'İşini ve öğrencilerini çok sever.', cue: 'o, işini ve öğrencilerini sever' },
      { key: 's7', en: 'My brother is fifteen and he plays basketball.', tr: 'Kardeşim on beş yaşında ve basketbol oynar.', cue: 'kardeş, 15 yaşında, basketbol oynar' },
      { key: 's8', en: "He doesn't like homework at all.", tr: 'Ödevden hiç hoşlanmaz.', cue: 'o, ödevi hiç sevmez' },
      { key: 's9', en: 'My grandparents live in a village near Bursa.', tr: 'Büyükannemle büyükbabam Bursa yakınında bir köyde yaşar.', cue: 'büyükanne büyükbaba, Bursa yakını köy' },
      { key: 's10', en: 'We always visit them in the summer.', tr: 'Yazın onları her zaman ziyaret ederiz.', cue: 'yazın, her zaman, ziyaret' },
      { key: 's11', en: "We don't see them very often in winter.", tr: 'Kışın onları pek sık görmeyiz.', cue: 'kışın, pek sık görmeyiz' },
      { key: 's12', en: 'Does your family live in the same city?', tr: 'Ailen aynı şehirde mi yaşıyor?', cue: 'soru: ailen aynı şehirde mi' },
    ],
  },
  {
    id: 'food',
    title: 'Yemek alışkanlıklarım',
    icon: 'restaurant-outline',
    sentences: [
      { key: 's1', en: 'I really love Turkish food.', tr: 'Türk yemeklerine bayılırım.', cue: 'Türk yemeği, çok sevmek' },
      { key: 's2', en: 'I usually eat three meals a day.', tr: 'Genellikle günde üç öğün yemek yerim.', cue: 'günde 3 öğün' },
      { key: 's3', en: 'For breakfast, I eat cheese, olives and bread.', tr: 'Kahvaltıda peynir, zeytin ve ekmek yerim.', cue: 'kahvaltı: peynir, zeytin, ekmek' },
      { key: 's4', en: 'I often have soup for lunch.', tr: 'Öğle yemeğinde sık sık çorba içerim.', alts: ['I often eat soup for lunch.'], cue: 'öğle yemeği, sık sık çorba' },
      { key: 's5', en: 'My mother cooks dinner every evening.', tr: 'Annem her akşam yemek pişirir.', alts: ['My mother makes dinner every evening.'], cue: 'anne, her akşam yemek pişirir' },
      { key: 's6', en: 'She makes the best rice in the family.', tr: 'Ailedeki en güzel pilavı o yapar.', cue: 'o, ailenin en iyi pilavı' },
      { key: 's7', en: "I don't eat fast food very often.", tr: 'Hazır yemeği pek sık yemem.', cue: 'hazır yemek, pek sık değil' },
      { key: 's8', en: 'My brother never eats vegetables.', tr: 'Kardeşim asla sebze yemez.', cue: 'kardeş, asla sebze yemez' },
      { key: 's9', en: 'He says they taste bad.', tr: 'Tatlarının kötü olduğunu söyler.', cue: 'o, tadı kötü der' },
      { key: 's10', en: 'I drink a lot of water every day.', tr: 'Her gün bol su içerim.', cue: 'her gün bol su' },
      { key: 's11', en: 'We sometimes eat at a restaurant on Fridays.', tr: 'Cuma günleri bazen restoranda yeriz.', cue: 'cuma günleri, bazen restoran' },
      { key: 's12', en: 'What do you usually eat for dinner?', tr: 'Akşam yemeğinde genellikle ne yersin?', cue: 'soru: akşam genelde ne yersin' },
    ],
  },
  {
    id: 'weekend',
    title: 'Hafta sonum',
    icon: 'cafe-outline',
    sentences: [
      { key: 's1', en: "I love weekends because I don't work.", tr: 'Hafta sonlarını severim çünkü çalışmam.', cue: 'hafta sonu sevmek, çünkü çalışmamak' },
      { key: 's2', en: 'On Saturdays, I sleep until ten.', tr: 'Cumartesileri ona kadar uyurum.', cue: "cumartesi, saat 10'a kadar uyumak" },
      { key: 's3', en: 'Then I have a long breakfast with my family.', tr: 'Sonra ailemle uzun bir kahvaltı yaparım.', cue: 'sonra, ailece uzun kahvaltı' },
      { key: 's4', en: 'In the afternoon, I meet my friends at a coffee shop.', tr: 'Öğleden sonra arkadaşlarımla bir kafede buluşurum.', cue: 'öğleden sonra, kafede arkadaşlarla buluşmak' },
      { key: 's5', en: 'We drink coffee and talk for hours.', tr: 'Kahve içeriz ve saatlerce sohbet ederiz.', cue: 'kahve içmek, saatlerce sohbet' },
      { key: 's6', en: 'Sometimes we take a walk by the sea.', tr: 'Bazen deniz kenarında yürüyüş yaparız.', alts: ['Sometimes we go for a walk by the sea.'], cue: 'bazen, deniz kenarı, yürüyüş' },
      { key: 's7', en: 'My sister goes shopping on Saturday afternoons.', tr: 'Kız kardeşim cumartesi öğleden sonraları alışverişe gider.', cue: 'kız kardeş, cumartesi öğleden sonra, alışveriş' },
      { key: 's8', en: 'On Sundays, we visit my grandmother.', tr: 'Pazar günleri büyükannemi ziyaret ederiz.', cue: 'pazar, büyükanne ziyareti' },
      { key: 's9', en: 'She always cooks something delicious for us.', tr: 'Bize her zaman lezzetli bir şey pişirir.', cue: 'o, her zaman lezzetli bir şey pişirir' },
      { key: 's10', en: "I don't do any housework on Sundays.", tr: 'Pazarları hiç ev işi yapmam.', cue: 'pazar, hiç ev işi yapmam' },
      { key: 's11', en: 'Do you go out on weekends?', tr: 'Hafta sonları dışarı çıkar mısın?', cue: 'soru: hafta sonu dışarı çıkar mısın' },
      { key: 's12', en: 'I go to bed early on Sunday nights.', tr: 'Pazar akşamları erken yatarım.', cue: 'pazar akşamı, erken yatmak' },
    ],
  },
  {
    id: 'hobbies',
    title: 'Hobilerim',
    icon: 'football-outline',
    sentences: [
      { key: 's1', en: 'I have a few hobbies.', tr: 'Birkaç hobim var.', cue: 'birkaç hobi' },
      { key: 's2', en: 'I play football with my friends on Tuesdays.', tr: 'Salı günleri arkadaşlarımla futbol oynarım.', cue: 'salı, arkadaşlarla futbol' },
      { key: 's3', en: 'We play in a small park near my house.', tr: 'Evimin yakınındaki küçük bir parkta oynarız.', cue: 'ev yakını, küçük park, oynamak' },
      { key: 's4', en: 'I also read books before bed.', tr: 'Yatmadan önce kitap da okurum.', cue: 'yatmadan önce, kitap okumak' },
      { key: 's5', en: 'I usually read for thirty minutes.', tr: 'Genellikle otuz dakika okurum.', cue: 'genelde 30 dakika okumak' },
      { key: 's6', en: 'My best friend plays the guitar very well.', tr: 'En yakın arkadaşım çok iyi gitar çalar.', cue: 'en yakın arkadaş, gitar, çok iyi' },
      { key: 's7', en: 'He practices every day after work.', tr: 'Her gün işten sonra pratik yapar.', cue: 'o, işten sonra her gün pratik' },
      { key: 's8', en: "I don't play any instruments, but I love music.", tr: 'Hiç enstrüman çalmam ama müziği çok severim.', cue: 'enstrüman çalmam, ama müziği severim' },
      { key: 's9', en: 'I often listen to music on the bus.', tr: 'Otobüste sık sık müzik dinlerim.', cue: 'otobüste, sık sık müzik' },
      { key: 's10', en: 'My sister takes photos of the city.', tr: 'Kız kardeşim şehrin fotoğraflarını çeker.', cue: 'kız kardeş, şehrin fotoğrafı' },
      { key: 's11', en: "She doesn't like sports at all.", tr: 'Spordan hiç hoşlanmaz.', cue: 'o, sporu hiç sevmez' },
      { key: 's12', en: 'What do you do in your free time?', tr: 'Boş zamanında ne yaparsın?', cue: 'soru: boş zamanda ne yaparsın' },
    ],
  },
  {
    id: 'home',
    title: 'Evim',
    icon: 'home-outline',
    sentences: [
      { key: 's1', en: 'I live in a flat in Istanbul.', tr: "İstanbul'da bir dairede yaşarım.", alts: ['I live in an apartment in Istanbul.'], cue: 'İstanbul, daire, yaşamak' },
      { key: 's2', en: 'Our flat has three bedrooms and a small balcony.', tr: 'Dairemizde üç yatak odası ve küçük bir balkon var.', cue: 'daire: 3 yatak odası, küçük balkon' },
      { key: 's3', en: 'My room is small, but it gets a lot of sun.', tr: 'Odam küçük ama çok güneş alır.', cue: 'oda küçük, ama çok güneş' },
      { key: 's4', en: 'I study at a desk next to the window.', tr: 'Pencerenin yanındaki bir masada ders çalışırım.', cue: 'pencere yanı, masa, ders çalışmak' },
      { key: 's5', en: 'We usually sit in the living room in the evening.', tr: 'Akşamları genellikle oturma odasında otururuz.', cue: 'akşam, genelde oturma odası' },
      { key: 's6', en: 'My father watches the news on TV there.', tr: 'Babam orada televizyonda haberleri izler.', cue: 'baba, orada, haber izler' },
      { key: 's7', en: 'My mother often drinks tea on the balcony.', tr: 'Annem sık sık balkonda çay içer.', cue: 'anne, sık sık, balkonda çay' },
      { key: 's8', en: "We don't have a garden, so we grow flowers there.", tr: 'Bahçemiz yok, bu yüzden orada çiçek yetiştiririz.', cue: 'bahçe yok, orada çiçek yetiştirmek' },
      { key: 's9', en: 'I clean my room every Saturday.', tr: 'Her cumartesi odamı temizlerim.', cue: 'her cumartesi, oda temizlemek' },
      { key: 's10', en: 'My brother never cleans his room.', tr: 'Kardeşim odasını asla temizlemez.', cue: 'kardeş, asla oda temizlemez' },
      { key: 's11', en: "Our neighbors don't make much noise.", tr: 'Komşularımız pek gürültü yapmaz.', cue: 'komşular, pek gürültü yapmaz' },
      { key: 's12', en: 'Do you live in a house or a flat?', tr: 'Müstakil evde mi yaşıyorsun, dairede mi?', alts: ['Do you live in a house or an apartment?'], cue: 'soru: müstakil ev mi, daire mi' },
    ],
  },
  {
    id: 'city-transport',
    title: 'Şehrim ve ulaşım',
    icon: 'bus-outline',
    sentences: [
      { key: 's1', en: 'Istanbul is a very big and busy city.', tr: 'İstanbul çok büyük ve kalabalık bir şehir.', cue: 'İstanbul, çok büyük ve kalabalık' },
      { key: 's2', en: 'I go to work by metro every day.', tr: 'Her gün metroyla işe giderim.', alts: ['I take the metro to work every day.'], cue: 'her gün, metro, işe gitmek' },
      { key: 's3', en: 'The station is five minutes from my house.', tr: 'İstasyon evime beş dakika uzaklıkta.', cue: 'istasyon, evden 5 dakika' },
      { key: 's4', en: 'The trains usually come every few minutes.', tr: 'Trenler genellikle birkaç dakikada bir gelir.', cue: 'trenler, genelde birkaç dakikada bir' },
      { key: 's5', en: 'In the morning, the metro is always very crowded.', tr: 'Sabahları metro her zaman çok kalabalıktır.', cue: 'sabah, metro, her zaman çok kalabalık' },
      { key: 's6', en: 'I sometimes take the ferry to the other side.', tr: 'Bazen karşıya vapurla geçerim.', cue: 'bazen, karşıya, vapur' },
      { key: 's7', en: 'I love the ferry because the view is beautiful.', tr: 'Vapuru çok severim çünkü manzara çok güzel.', cue: 'vapuru severim, çünkü manzara güzel' },
      { key: 's8', en: "My brother doesn't like the bus, so he rides a bike.", tr: 'Kardeşim otobüsü sevmez, bu yüzden bisiklete biner.', cue: 'kardeş, otobüsü sevmez, bisiklete biner' },
      { key: 's9', en: 'My father drives to work, but the traffic is terrible.', tr: 'Babam işe arabayla gider ama trafik berbattır.', cue: 'baba, arabayla işe, trafik kötü' },
      { key: 's10', en: 'It often takes him an hour to get home.', tr: 'Eve varması sık sık bir saat sürer.', cue: 'eve varması, sık sık 1 saat' },
      { key: 's11', en: "I don't drive in the city center.", tr: 'Şehir merkezinde araba kullanmam.', cue: 'şehir merkezi, araba kullanmam' },
      { key: 's12', en: 'How do you get to work?', tr: 'İşe nasıl gidersin?', cue: 'soru: işe nasıl gidersin' },
    ],
  },
  {
    id: 'friends',
    title: 'Arkadaşlarım',
    icon: 'chatbubbles-outline',
    sentences: [
      { key: 's1', en: 'I have three close friends.', tr: 'Üç yakın arkadaşım var.', cue: '3 yakın arkadaş' },
      { key: 's2', en: 'We meet every Friday evening.', tr: 'Her cuma akşamı buluşuruz.', cue: 'her cuma akşamı, buluşmak' },
      { key: 's3', en: 'We usually go to a coffee shop near the park.', tr: 'Genellikle parkın yakınındaki bir kafeye gideriz.', cue: 'genelde, park yakını kafe' },
      { key: 's4', en: 'One of my friends works as a nurse.', tr: 'Arkadaşlarımdan biri hemşire olarak çalışır.', cue: 'arkadaşlardan biri, hemşire' },
      { key: 's5', en: 'She works at night, so she often feels tired.', tr: 'Geceleri çalışır, bu yüzden sık sık yorgun hisseder.', cue: 'o, gece çalışır, sık sık yorgun' },
      { key: 's6', en: 'My other friend lives near my house.', tr: 'Diğer arkadaşım evimin yakınında oturur.', cue: 'diğer arkadaş, ev yakınım' },
      { key: 's7', en: 'He always helps me when I have a problem.', tr: 'Bir sorunum olduğunda bana her zaman yardım eder.', cue: 'o, sorunum olunca her zaman yardım' },
      { key: 's8', en: 'We talk on the phone almost every day.', tr: 'Neredeyse her gün telefonda konuşuruz.', cue: 'neredeyse her gün, telefonda konuşmak' },
      { key: 's9', en: "We don't agree on everything, but we never fight.", tr: 'Her konuda aynı fikirde değiliz ama asla kavga etmeyiz.', cue: 'her konuda aynı fikirde değiliz, ama hiç kavga etmeyiz' },
      { key: 's10', en: 'We sometimes play board games at my house.', tr: 'Bazen bizim evde kutu oyunları oynarız.', cue: 'bazen, evimde kutu oyunu' },
      { key: 's11', en: "My friends don't like horror films.", tr: 'Arkadaşlarım korku filmlerini sevmez.', alts: ["My friends don't like horror movies."], cue: 'arkadaşlarım, korku filmini sevmez' },
      { key: 's12', en: 'Do you see your friends often?', tr: 'Arkadaşlarını sık görür müsün?', cue: 'soru: arkadaşlarını sık görür müsün' },
    ],
  },
  {
    id: 'evening-routine',
    title: 'Akşam rutinim',
    icon: 'moon-outline',
    sentences: [
      { key: 's1', en: 'I get home at about half past six.', tr: 'Altı buçuk civarında eve gelirim.', cue: 'altı buçuk civarı, eve gelmek' },
      { key: 's2', en: 'First, I change my clothes and wash my hands.', tr: 'Önce kıyafetlerimi değiştiririm ve ellerimi yıkarım.', cue: 'önce, kıyafet değiştirmek, el yıkamak' },
      { key: 's3', en: "We have dinner at seven o'clock.", tr: 'Saat yedide akşam yemeği yeriz.', alts: ["We eat dinner at seven o'clock."], cue: 'saat 7, akşam yemeği' },
      { key: 's4', en: 'After dinner, my father washes the dishes.', tr: 'Akşam yemeğinden sonra babam bulaşıkları yıkar.', cue: 'yemekten sonra, baba, bulaşık yıkar' },
      { key: 's5', en: 'I usually drink a cup of tea on the sofa.', tr: 'Genellikle kanepede bir bardak çay içerim.', cue: 'genelde, kanepede, bir bardak çay' },
      { key: 's6', en: 'My mother watches her favorite series on TV.', tr: 'Annem televizyonda en sevdiği diziyi izler.', cue: 'anne, en sevdiği dizi, TV' },
      { key: 's7', en: "I don't watch TV very much.", tr: 'Pek televizyon izlemem.', cue: 'pek TV izlemem' },
      { key: 's8', en: 'I study English for an hour instead.', tr: 'Onun yerine bir saat İngilizce çalışırım.', cue: 'onun yerine, 1 saat İngilizce' },
      { key: 's9', en: 'Then I prepare my bag for the next day.', tr: 'Sonra ertesi gün için çantamı hazırlarım.', cue: 'sonra, ertesi gün çantası' },
      { key: 's10', en: 'I never drink coffee in the evening.', tr: 'Akşamları asla kahve içmem.', cue: 'akşam, asla kahve içmem' },
      { key: 's11', en: 'Do you go to bed late?', tr: 'Geç yatar mısın?', cue: 'soru: geç yatar mısın' },
      { key: 's12', en: 'I usually go to bed at eleven.', tr: 'Genellikle on birde yatarım.', cue: "genelde, saat 11'de yatmak" },
    ],
  },
];
