import type { LadderTheme } from './types';

// Present Perfect Continuous konusma merdiveni icerigi (elle yazildi). Her tema,
// o konuda art arda anlatilabilecek 12 cumlelik bir konusma akisidir. Karsilastirma
// icin yer yer present perfect simple de kullanilir.
export const PRESENT_PERFECT_CONTINUOUS_THEMES: LadderTheme[] = [
  {
    id: 'ppc-learning-english',
    title: 'İngilizce öğreniyorum',
    icon: 'language-outline',
    sentences: [
      { key: 's1', en: "I've been learning English for two years.", tr: 'İki yıldır İngilizce öğreniyorum.' },
      { key: 's2', en: "I've been using this app since January.", tr: 'Ocaktan beri bu uygulamayı kullanıyorum.' },
      { key: 's3', en: "I've been practicing a little every day.", tr: 'Her gün biraz pratik yapıyorum.' },
      { key: 's4', en: "I've learned a lot of new words.", tr: 'Bir sürü yeni kelime öğrendim.' },
      { key: 's5', en: "Lately, I've been watching TV series in English.", tr: 'Son zamanlarda İngilizce dizi izliyorum.' },
      { key: 's6', en: "I've been reading short stories on the metro too.", tr: 'Metroda da kısa hikâyeler okuyorum.' },
      { key: 's7', en: "But I haven't been speaking enough.", tr: 'Ama bu aralar yeterince konuşmuyorum.' },
      { key: 's8', en: "So I've been talking to myself in English at home.", tr: 'Bu yüzden evde kendi kendime İngilizce konuşuyorum.' },
      { key: 's9', en: 'My sister has been taking English lessons since September.', tr: 'Kız kardeşim eylülden beri İngilizce dersi alıyor.' },
      { key: 's10', en: "We've been practicing together in the evenings.", tr: 'Akşamları birlikte pratik yapıyoruz.' },
      { key: 's11', en: "We haven't been speaking Turkish at dinner lately.", tr: 'Son zamanlarda akşam yemeğinde Türkçe konuşmuyoruz.' },
      { key: 's12', en: 'How long have you been learning English?', tr: 'Sen ne zamandır İngilizce öğreniyorsun?', alts: ['How long have you been studying English?'] },
    ],
  },
  {
    id: 'ppc-long-day',
    title: 'Yorucu bir gün',
    icon: 'battery-dead-outline',
    sentences: [
      { key: 's1', en: "I'm so tired because I've been working all day.", tr: 'Bütün gün çalıştığım için çok yorgunum.' },
      { key: 's2', en: "I've been sitting at my desk since eight o'clock.", tr: 'Saat sekizden beri masamda oturuyorum.' },
      { key: 's3', en: "I've been looking at the screen for hours.", tr: 'Saatlerdir ekrana bakıyorum.' },
      { key: 's4', en: "And I haven't eaten anything since breakfast.", tr: 'Üstelik kahvaltıdan beri hiçbir şey yemedim.' },
      { key: 's5', en: 'Now the whole house smells great.', tr: 'Şimdi bütün ev mis gibi kokuyor.' },
      { key: 's6', en: 'My mother has been cooking since lunchtime.', tr: 'Annem öğleden beri yemek yapıyor.' },
      { key: 's7', en: 'My little brother is wet and muddy.', tr: 'Küçük kardeşim sırılsıklam ve çamur içinde.' },
      { key: 's8', en: 'Have you been playing football in the rain?', tr: 'Yağmurda futbol mu oynuyordun?' },
      { key: 's9', en: "My father hasn't been feeling well this week.", tr: 'Babam bu hafta kendini pek iyi hissetmiyor.' },
      { key: 's10', en: 'He has been coughing since Monday.', tr: 'Pazartesiden beri öksürüyor.' },
      { key: 's11', en: "I've been making him soup every evening.", tr: 'Her akşam ona çorba yapıyorum.' },
      { key: 's12', en: 'It has been a very long day.', tr: 'Çok uzun bir gün oldu.' },
    ],
  },
  {
    id: 'ppc-new-city',
    title: 'Yeni şehrim',
    icon: 'map-outline',
    sentences: [
      { key: 's1', en: "I've been living in Izmir for three years.", tr: "Üç yıldır İzmir'de yaşıyorum." },
      { key: 's2', en: "I've been working at a hotel since I moved here.", tr: 'Buraya taşındığımdan beri bir otelde çalışıyorum.' },
      { key: 's3', en: "I've really been enjoying the weather.", tr: 'Havanın keyfini gerçekten çıkarıyorum.', alts: ["I've been really enjoying the weather."] },
      { key: 's4', en: "It hasn't snowed at all this winter.", tr: 'Bu kış hiç kar yağmadı.' },
      { key: 's5', en: "I've been going to the beach every weekend.", tr: 'Her hafta sonu denize gidiyorum.' },
      { key: 's6', en: "I've also been learning to swim.", tr: 'Bir de yüzme öğreniyorum.' },
      { key: 's7', en: "But I haven't been sleeping well lately.", tr: 'Ama son zamanlarda iyi uyuyamıyorum.' },
      { key: 's8', en: 'My neighbors have been making a lot of noise.', tr: 'Komşularım çok gürültü yapıyor.' },
      { key: 's9', en: 'My parents have been staying with me since Sunday.', tr: 'Annemler pazardan beri bende kalıyor.' },
      { key: 's10', en: "We've been eating fish by the sea every night.", tr: 'Her akşam deniz kenarında balık yiyoruz.' },
      { key: 's11', en: 'My father has been going for a walk every morning.', tr: 'Babam her sabah yürüyüşe çıkıyor.' },
      { key: 's12', en: 'How long have you been living in your current city?', tr: 'Sen ne zamandır şimdiki şehrinde yaşıyorsun?' },
    ],
  },
  {
    id: 'ppc-healthy-habits',
    title: 'Sağlıklı alışkanlıklar',
    icon: 'fitness-outline',
    sentences: [
      { key: 's1', en: "I've been trying to live a healthier life.", tr: 'Daha sağlıklı yaşamaya çalışıyorum.' },
      { key: 's2', en: "I've been going to the gym since March.", tr: 'Marttan beri spor salonuna gidiyorum.' },
      { key: 's3', en: "I've also been walking to work every day.", tr: 'Ayrıca her gün işe yürüyerek gidiyorum.' },
      { key: 's4', en: "I've already lost four kilos.", tr: 'Şimdiden dört kilo verdim.' },
      { key: 's5', en: "I haven't been eating much sugar lately.", tr: 'Son zamanlarda pek şeker yemiyorum.' },
      { key: 's6', en: "I've been drinking water instead of fizzy drinks.", tr: 'Gazlı içecek yerine su içiyorum.', alts: ["I've been drinking water instead of soda."] },
      { key: 's7', en: 'My wife has been cooking with less oil.', tr: 'Eşim daha az yağla yemek yapıyor.' },
      { key: 's8', en: "We haven't been ordering fast food at all.", tr: 'Hiç dışarıdan hazır yemek söylemiyoruz.' },
      { key: 's9', en: "I've been sleeping much better since I started.", tr: 'Başladığımdan beri çok daha iyi uyuyorum.' },
      { key: 's10', en: 'My brother has been running with me on Sundays.', tr: 'Kardeşim pazar günleri benimle koşuyor.' },
      { key: 's11', en: 'Have you been doing any sport lately?', tr: 'Son zamanlarda hiç spor yapıyor musun?', alts: ['Have you been doing any exercise lately?'] },
      { key: 's12', en: "I've never felt better in my life.", tr: 'Hayatımda hiç bu kadar iyi hissetmedim.' },
    ],
  },
  {
    id: 'ppc-repairman',
    title: 'Tamirci bekliyorum',
    icon: 'construct-outline',
    sentences: [
      { key: 's1', en: "I've been waiting for the technician since nine.", tr: 'Dokuzdan beri teknik servisi bekliyorum.' },
      { key: 's2', en: "Our washing machine hasn't been working for a week.", tr: 'Çamaşır makinemiz bir haftadır çalışmıyor.' },
      { key: 's3', en: "I've been washing clothes by hand since Monday.", tr: 'Pazartesiden beri çamaşırları elde yıkıyorum.' },
      { key: 's4', en: "I've called the company three times today.", tr: 'Bugün şirketi üç kez aradım.' },
      { key: 's5', en: "I've been looking out of the window for hours.", tr: 'Saatlerdir camdan dışarı bakıyorum.' },
      { key: 's6', en: "I haven't left the house since yesterday.", tr: 'Dünden beri evden çıkmadım.' },
      { key: 's7', en: 'My neighbor has been having the same problem.', tr: 'Komşum da aynı sorunu yaşıyor.' },
      { key: 's8', en: 'She has been waiting for two days.', tr: 'İki gündür bekliyor.' },
      { key: 's9', en: 'Oh, someone is ringing the doorbell!', tr: 'Aa, kapı çalıyor!' },
      { key: 's10', en: "Finally! I've been waiting for you all day.", tr: 'Sonunda! Bütün gündür sizi bekliyorum.' },
      { key: 's11', en: 'How long have you been doing this job?', tr: 'Ne zamandır bu işi yapıyorsunuz?' },
      { key: 's12', en: 'Great, he has already fixed it!', tr: 'Harika, tamir etti bile!' },
    ],
  },
  {
    id: 'ppc-old-friend',
    title: 'Eski bir arkadaşla',
    icon: 'people-circle-outline',
    sentences: [
      { key: 's1', en: "Hi! I haven't seen you for a long time.", tr: 'Selam! Seni görmeyeli uzun zaman oldu.' },
      { key: 's2', en: 'What have you been doing lately?', tr: 'Son zamanlarda neler yapıyorsun?' },
      { key: 's3', en: "I've been working at a new company since May.", tr: 'Mayıstan beri yeni bir şirkette çalışıyorum.' },
      { key: 's4', en: "It's hard, but I've been learning a lot.", tr: 'Zor ama çok şey öğreniyorum.' },
      { key: 's5', en: 'My husband and I have been looking for a new flat.', tr: 'Eşimle yeni bir daire arıyoruz.', alts: ['My husband and I have been looking for a new apartment.'] },
      { key: 's6', en: "We've been looking for three months now.", tr: 'Üç aydır arıyoruz.' },
      { key: 's7', en: "We haven't found the right one yet.", tr: 'Henüz aradığımızı bulamadık.' },
      { key: 's8', en: 'Prices have been going up every month.', tr: 'Fiyatlar her ay artıyor.' },
      { key: 's9', en: 'And you? How long have you been living in Bursa?', tr: "Peki sen? Ne zamandır Bursa'da yaşıyorsun?" },
      { key: 's10', en: 'You look great! Have you been doing yoga?', tr: 'Harika görünüyorsun! Yoga mı yapıyorsun?' },
      { key: 's11', en: "I've really missed our long talks.", tr: 'Uzun sohbetlerimizi gerçekten özledim.' },
      { key: 's12', en: "We haven't talked like this for years.", tr: 'Yıllardır böyle sohbet etmemiştik.' },
    ],
  },
];
