import type { LadderTheme } from './types';

// Relative clauses konusma merdiveni icerigi (elle yazildi). Tanimlayici yan
// cumle: who / which / that / where. Her tema 12 cumlelik bir konusma akisidir.
export const RELATIVE_CLAUSES_THEMES: LadderTheme[] = [
  {
    id: 'rel-people',
    title: 'Hayatımdaki insanlar',
    icon: 'people-circle-outline',
    sentences: [
      { key: 's1', en: 'I have a friend who lives in Izmir.', tr: "İzmir'de yaşayan bir arkadaşım var.", alts: ['I have a friend that lives in Izmir.'] },
      { key: 's2', en: 'She is the person who calls me every Sunday.', tr: 'Beni her pazar arayan kişi o.' },
      { key: 's3', en: 'My brother is someone who never gets angry.', tr: 'Kardeşim asla sinirlenmeyen biridir.' },
      { key: 's4', en: 'He works for a company that makes toys.', tr: 'Oyuncak üreten bir şirkette çalışıyor.' },
      { key: 's5', en: 'My aunt is the woman who taught me to cook.', tr: 'Teyzem, bana yemek yapmayı öğreten kişidir.' },
      { key: 's6', en: 'She lives in a village where there is no internet.', tr: 'İnternetin olmadığı bir köyde yaşıyor.' },
      { key: 's7', en: "My neighbor is a man who doesn't talk much.", tr: 'Komşum pek konuşmayan bir adam.' },
      { key: 's8', en: 'But he always helps people who need help.', tr: 'Ama yardıma ihtiyacı olan insanlara hep yardım eder.' },
      { key: 's9', en: 'My best friend is a girl who I met at school.', tr: 'En yakın arkadaşım okulda tanıştığım bir kız.', alts: ['My best friend is a girl that I met at school.'] },
      { key: 's10', en: 'She is the only person who knows all my secrets.', tr: 'Bütün sırlarımı bilen tek kişi o.' },
      { key: 's11', en: "I don't like people who lie.", tr: 'Yalan söyleyen insanları sevmem.' },
      { key: 's12', en: 'Do you have a friend who lives in another city?', tr: 'Başka bir şehirde yaşayan bir arkadaşın var mı?' },
    ],
  },
  {
    id: 'rel-places',
    title: 'Sevdiğim yerler',
    icon: 'location-outline',
    sentences: [
      { key: 's1', en: 'There is a coffee shop where I go every morning.', tr: 'Her sabah gittiğim bir kafe var.', alts: ['There is a coffee shop that I go to every morning.'] },
      { key: 's2', en: 'It is the place where I read and relax.', tr: 'Kitap okuyup dinlendiğim yer orası.' },
      { key: 's3', en: "The owner is a man who knows everyone's name.", tr: 'Sahibi herkesin adını bilen bir adam.' },
      { key: 's4', en: 'I always sit at a table that has a sea view.', tr: 'Hep deniz manzarası olan bir masaya otururum.' },
      { key: 's5', en: 'The park where I walk every evening is near my house.', tr: 'Her akşam yürüdüğüm park evimin yakınında.' },
      { key: 's6', en: 'It has old trees that give a lot of shade.', tr: 'Bol gölge veren yaşlı ağaçları var.' },
      { key: 's7', en: "It isn't a place where people play loud music.", tr: 'İnsanların yüksek sesle müzik açtığı bir yer değil.' },
      { key: 's8', en: 'I also love the ferry that goes to the Asian side.', tr: 'Anadolu yakasına giden vapuru da çok severim.' },
      { key: 's9', en: 'On the ferry, there is a man who sells tea.', tr: 'Vapurda çay satan bir adam var.' },
      { key: 's10', en: 'Istanbul is the city where I feel at home.', tr: 'İstanbul kendimi evimde hissettiğim şehir.' },
      { key: 's11', en: "I don't like places that are too crowded.", tr: 'Çok kalabalık olan yerleri sevmem.' },
      { key: 's12', en: 'Is there a place where you feel really happy?', tr: 'Kendini gerçekten mutlu hissettiğin bir yer var mı?' },
    ],
  },
  {
    id: 'rel-things',
    title: 'Eşyalarım',
    icon: 'watch-outline',
    sentences: [
      { key: 's1', en: 'I have a watch that belonged to my grandfather.', tr: 'Eskiden dedeme ait olan bir saatim var.', alts: ['I have a watch which belonged to my grandfather.'] },
      { key: 's2', en: 'It is the thing that I love most.', tr: 'En çok sevdiğim şey o.' },
      { key: 's3', en: "It is an old watch which doesn't work anymore.", tr: 'Artık çalışmayan eski bir saat.' },
      { key: 's4', en: 'I keep it in a box that my mother gave me.', tr: 'Onu annemin bana verdiği bir kutuda saklıyorum.' },
      { key: 's5', en: 'I also have a bike that I ride every weekend.', tr: 'Her hafta sonu bindiğim bir bisikletim de var.', alts: ['I also have a bike which I ride every weekend.'] },
      { key: 's6', en: 'It was the first thing that I bought with my salary.', tr: 'Maaşımla aldığım ilk şeydi.' },
      { key: 's7', en: 'I have a bag that goes everywhere with me.', tr: 'Benimle her yere gelen bir çantam var.' },
      { key: 's8', en: 'It has a pocket where I keep my keys.', tr: 'Anahtarlarımı koyduğum bir cebi var.' },
      { key: 's9', en: 'The picture that is on my wall was painted by my sister.', tr: 'Duvarımda asılı olan resim kız kardeşim tarafından yapıldı.' },
      { key: 's10', en: "I don't buy things that I don't need.", tr: 'İhtiyacım olmayan şeyleri almam.' },
      { key: 's11', en: "The things that I love aren't very expensive.", tr: 'Sevdiğim şeyler pek pahalı değil.' },
      { key: 's12', en: 'What is the thing that you use most every day?', tr: 'Her gün en çok kullandığın eşya ne?' },
    ],
  },
  {
    id: 'rel-film-book',
    title: 'Filmler ve kitaplar',
    icon: 'film-outline',
    sentences: [
      { key: 's1', en: 'I watched a film that made me cry.', tr: 'Beni ağlatan bir film izledim.', alts: ['I watched a movie that made me cry.'] },
      { key: 's2', en: 'It is about a man who loses his memory.', tr: 'Hafızasını kaybeden bir adamı anlatıyor.' },
      { key: 's3', en: 'He lives in a small town where nobody knows him.', tr: 'Kimsenin onu tanımadığı küçük bir kasabada yaşıyor.' },
      { key: 's4', en: 'One day, he meets a woman who helps him.', tr: 'Bir gün ona yardım eden bir kadınla tanışıyor.' },
      { key: 's5', en: 'She finds an old letter which has his real name.', tr: 'Üzerinde gerçek adı yazan eski bir mektup buluyor.' },
      { key: 's6', en: 'The actor who plays the man is really good.', tr: 'Adamı oynayan oyuncu gerçekten çok iyi.' },
      { key: 's7', en: 'The music that you hear at the end is beautiful.', tr: 'Sonunda duyduğun müzik çok güzel.' },
      { key: 's8', en: "It isn't a film that small children would enjoy.", tr: 'Küçük çocukların hoşlanacağı bir film değil.' },
      { key: 's9', en: 'I also like books that have a surprise ending.', tr: 'Sürpriz sonu olan kitapları da severim.' },
      { key: 's10', en: 'The last book that I read was a detective story.', tr: 'Okuduğum son kitap bir polisiye romandı.' },
      { key: 's11', en: "I don't read books that are too long.", tr: 'Çok uzun olan kitapları okumam.' },
      { key: 's12', en: 'What is a film that you can watch again and again?', tr: 'Tekrar tekrar izleyebileceğin bir film hangisi?', alts: ['What is a movie that you can watch again and again?'] },
    ],
  },
  {
    id: 'rel-neighborhood',
    title: 'Mahallem',
    icon: 'storefront-outline',
    sentences: [
      { key: 's1', en: 'I live in a neighborhood where everyone knows each other.', tr: 'Herkesin birbirini tanıdığı bir mahallede yaşıyorum.' },
      { key: 's2', en: 'There is a bakery that opens at six in the morning.', tr: 'Sabah altıda açılan bir fırın var.', alts: ['There is a bakery which opens at six in the morning.'] },
      { key: 's3', en: 'The baker is a man who always smiles.', tr: 'Fırıncı her zaman gülümseyen bir adam.' },
      { key: 's4', en: 'Next to it, there is a shop that sells fruit and vegetables.', tr: 'Onun yanında meyve sebze satan bir dükkân var.' },
      { key: 's5', en: 'There is a small mosque where my grandfather prays.', tr: 'Dedemin namaz kıldığı küçük bir cami var.' },
      { key: 's6', en: 'Behind it, there is a park where children play football.', tr: 'Arkasında çocukların futbol oynadığı bir park var.' },
      { key: 's7', en: 'The old woman who lives upstairs feeds the street cats.', tr: 'Üst katta oturan yaşlı kadın sokak kedilerini besler.' },
      { key: 's8', en: "There isn't a shop that stays open all night.", tr: 'Bütün gece açık kalan bir dükkân yok.' },
      { key: 's9', en: 'The street where I live is quiet at night.', tr: 'Yaşadığım sokak geceleri sessizdir.' },
      { key: 's10', en: 'But the neighbors who live next door have a noisy dog.', tr: 'Ama yan dairede oturan komşuların gürültücü bir köpeği var.' },
      { key: 's11', en: "I don't know the people who moved in last month.", tr: 'Geçen ay taşınan insanları tanımıyorum.' },
      { key: 's12', en: 'Do you live in a place where you know your neighbors?', tr: 'Komşularını tanıdığın bir yerde mi yaşıyorsun?' },
    ],
  },
  {
    id: 'rel-job',
    title: 'İşim',
    icon: 'laptop-outline',
    sentences: [
      { key: 's1', en: 'I work for a company that makes mobile apps.', tr: 'Mobil uygulama yapan bir şirkette çalışıyorum.', alts: ['I work for a company which makes mobile apps.'] },
      { key: 's2', en: 'Our office is in a building which has twenty floors.', tr: 'Ofisimiz yirmi katı olan bir binada.' },
      { key: 's3', en: 'I sit next to a colleague who comes from Ankara.', tr: "Ankara'dan gelen bir iş arkadaşımın yanında oturuyorum." },
      { key: 's4', en: 'He is the person who helps me when I have a problem.', tr: 'Bir sorunum olduğunda bana yardım eden kişi o.' },
      { key: 's5', en: 'My manager is a woman who works very hard.', tr: 'Müdürüm çok çalışan bir kadın.' },
      { key: 's6', en: 'She gives us tasks that are sometimes very difficult.', tr: 'Bize bazen çok zor olan görevler veriyor.' },
      { key: 's7', en: 'The part of my job that I like most is design.', tr: 'İşimin en sevdiğim kısmı tasarım.' },
      { key: 's8', en: "I don't like meetings that last for hours.", tr: 'Saatlerce süren toplantıları sevmem.' },
      { key: 's9', en: 'There is a kitchen where we drink tea together.', tr: 'Birlikte çay içtiğimiz bir mutfak var.' },
      { key: 's10', en: 'We have lunch at a restaurant that is near the office.', tr: 'Ofisin yakınında olan bir restoranda öğle yemeği yeriz.' },
      { key: 's11', en: "It isn't a job that makes me rich, but I love it.", tr: 'Beni zengin eden bir iş değil ama onu seviyorum.' },
      { key: 's12', en: 'Is your job something that you really enjoy?', tr: 'İşin gerçekten keyif aldığın bir şey mi?' },
    ],
  },
];
