import type { LadderTheme } from './types';

// "Used to" konusma merdiveni icerigi (elle yazildi). Gecmisteki, artik suren
// olmayan aliskanliklar ve durumlar; yer yer bugunle (present simple) karsilastirma.
export const USED_TO_THEMES: LadderTheme[] = [
  {
    id: 'usedto-childhood',
    title: 'Çocukluğum',
    icon: 'happy-outline',
    sentences: [
      { key: 's1', en: 'I used to live in a small town near Bursa.', tr: 'Eskiden Bursa yakınlarında küçük bir kasabada yaşardım.' },
      { key: 's2', en: 'We used to have a big garden with fruit trees.', tr: 'Meyve ağaçları olan büyük bir bahçemiz vardı.' },
      { key: 's3', en: 'I used to play outside with my cousins every day.', tr: 'Her gün kuzenlerimle dışarıda oynardım.' },
      { key: 's4', en: 'We used to climb trees and ride our bikes.', tr: 'Ağaçlara tırmanır, bisiklete binerdik.' },
      { key: 's5', en: "I didn't use to like vegetables at all.", tr: 'Sebzeleri hiç sevmezdim.', alts: ['I never used to like vegetables.'] },
      { key: 's6', en: 'My grandmother used to cook for the whole family.', tr: 'Büyükannem bütün aileye yemek yapardı.' },
      { key: 's7', en: 'She used to tell us stories before bed.', tr: 'Yatmadan önce bize masal anlatırdı.' },
      { key: 's8', en: 'I used to be afraid of the dark.', tr: 'Karanlıktan korkardım.' },
      { key: 's9', en: "My father didn't use to work on Sundays.", tr: 'Babam pazar günleri çalışmazdı.' },
      { key: 's10', en: 'So we used to go to the beach together.', tr: 'Bu yüzden hep birlikte denize giderdik.' },
      { key: 's11', en: 'Did you use to play outside as a child?', tr: 'Sen çocukken dışarıda oynar mıydın?', alts: ['Did you use to play outside when you were a child?'] },
      { key: 's12', en: 'Now I live in Istanbul, and I miss those days.', tr: "Şimdi İstanbul'da yaşıyorum ve o günleri özlüyorum." },
    ],
  },
  {
    id: 'usedto-school-days',
    title: 'Okul yıllarım',
    icon: 'school-outline',
    sentences: [
      { key: 's1', en: 'I used to walk to school every morning.', tr: 'Her sabah okula yürüyerek giderdim.', alts: ['I used to go to school on foot every morning.'] },
      { key: 's2', en: 'My best friend used to wait for me at the corner.', tr: 'En yakın arkadaşım beni köşede beklerdi.' },
      { key: 's3', en: 'We used to wear a dark blue uniform.', tr: 'Lacivert bir forma giyerdik.' },
      { key: 's4', en: "I didn't use to like getting up early.", tr: 'Erken kalkmayı sevmezdim.' },
      { key: 's5', en: 'My favorite subject used to be math.', tr: 'En sevdiğim ders matematikti.', alts: ['Math used to be my favorite subject.'] },
      { key: 's6', en: 'I used to sit in the front row.', tr: 'En ön sırada otururdum.' },
      { key: 's7', en: 'Our teacher used to give us homework every day.', tr: 'Öğretmenimiz bize her gün ödev verirdi.' },
      { key: 's8', en: "I didn't use to do my homework on time.", tr: 'Ödevlerimi zamanında yapmazdım.' },
      { key: 's9', en: 'At lunchtime, we used to play football in the schoolyard.', tr: 'Öğle arasında okul bahçesinde futbol oynardık.' },
      { key: 's10', en: 'We used to buy simit at the school gate.', tr: 'Okul kapısında simit alırdık.' },
      { key: 's11', en: 'Did you use to wear a uniform too?', tr: 'Sen de forma giyer miydin?' },
      { key: 's12', en: 'I sometimes miss my school days.', tr: 'Bazen okul yıllarımı özlüyorum.' },
    ],
  },
  {
    id: 'usedto-old-neighborhood',
    title: 'Eski mahallem',
    icon: 'storefront-outline',
    sentences: [
      { key: 's1', en: 'We used to live in an old neighborhood in Izmir.', tr: "Bir zamanlar İzmir'de eski bir mahallede otururduk." },
      { key: 's2', en: 'Everybody used to know each other.', tr: 'Herkes birbirini tanırdı.', alts: ['Everyone used to know each other.'] },
      { key: 's3', en: 'Our neighbors used to visit us in the evenings.', tr: 'Komşularımız akşamları bize gelirdi.' },
      { key: 's4', en: 'My mother used to drink tea with them on the balcony.', tr: 'Annem onlarla balkonda çay içerdi.' },
      { key: 's5', en: 'There used to be a small grocery store on the corner.', tr: 'Köşede küçük bir bakkal vardı.' },
      { key: 's6', en: 'The owner used to give us candy.', tr: 'Bakkal amca bize şeker verirdi.' },
      { key: 's7', en: "We didn't use to lock our doors.", tr: 'Kapılarımızı kilitlemezdik.' },
      { key: 's8', en: 'The streets used to be quiet and clean.', tr: 'Sokaklar sessiz ve temizdi.' },
      { key: 's9', en: 'Children used to play in the street until dark.', tr: 'Çocuklar hava kararana kadar sokakta oynardı.' },
      { key: 's10', en: 'Today there are tall buildings everywhere.', tr: 'Bugün her yer yüksek binalarla dolu.' },
      { key: 's11', en: 'Did you use to know all your neighbors?', tr: 'Sen bütün komşularını tanır mıydın?' },
      { key: 's12', en: "Now I don't even know my neighbors' names.", tr: 'Şimdiyse komşularımın adını bile bilmiyorum.' },
    ],
  },
  {
    id: 'usedto-summer-holidays',
    title: 'Çocukluk yazlarım',
    icon: 'umbrella-outline',
    sentences: [
      { key: 's1', en: "Every summer, we used to go to my grandparents' village.", tr: 'Her yaz dedemlerin köyüne giderdik.' },
      { key: 's2', en: 'The journey used to take ten hours by bus.', tr: 'Otobüs yolculuğu on saat sürerdi.' },
      { key: 's3', en: 'My grandfather used to wait for us at the bus stop.', tr: 'Dedem bizi otobüs durağında beklerdi.' },
      { key: 's4', en: 'We used to sleep in the garden on hot nights.', tr: 'Sıcak gecelerde bahçede uyurduk.' },
      { key: 's5', en: 'In the mornings, we used to swim in the sea.', tr: 'Sabahları denizde yüzerdik.' },
      { key: 's6', en: 'My grandmother used to bake fresh bread.', tr: 'Babaannem taze ekmek pişirirdi.' },
      { key: 's7', en: 'We used to eat breakfast under a big tree.', tr: 'Kahvaltıyı büyük bir ağacın altında yapardık.', alts: ['We used to have breakfast under a big tree.'] },
      { key: 's8', en: "I didn't use to watch TV in the summer.", tr: 'Yazları televizyon izlemezdim.' },
      { key: 's9', en: 'We never used to get bored in the village.', tr: 'Köyde hiç sıkılmazdık.' },
      { key: 's10', en: 'At night, my grandfather used to tell funny stories.', tr: 'Geceleri dedem komik hikâyeler anlatırdı.' },
      { key: 's11', en: 'Did you use to visit your grandparents in the summer?', tr: 'Sen de yazları dedenlere gider miydin?' },
      { key: 's12', en: 'I still love the smell of the sea.', tr: 'Denizin kokusunu hâlâ çok severim.' },
    ],
  },
  {
    id: 'usedto-old-habits',
    title: 'Eski alışkanlıklarım',
    icon: 'repeat-outline',
    sentences: [
      { key: 's1', en: 'I used to drink five cups of coffee a day.', tr: 'Eskiden günde beş fincan kahve içerdim.', alts: ['I used to have five cups of coffee a day.'] },
      { key: 's2', en: 'Now I only drink one cup in the morning.', tr: 'Şimdi sadece sabahları bir fincan içiyorum.' },
      { key: 's3', en: 'I used to go to bed after midnight.', tr: 'Gece yarısından sonra yatardım.' },
      { key: 's4', en: 'So I used to feel tired all day.', tr: 'Bu yüzden gün boyu yorgun dolaşırdım.' },
      { key: 's5', en: "I didn't use to exercise at all.", tr: 'Hiç spor yapmazdım.' },
      { key: 's6', en: 'I used to go everywhere by car.', tr: 'Her yere arabayla giderdim.', alts: ['I used to drive everywhere.'] },
      { key: 's7', en: 'Now I walk to work every day.', tr: 'Şimdi her gün işe yürüyerek gidiyorum.' },
      { key: 's8', en: 'I used to eat fast food for lunch.', tr: 'Öğle yemeğinde hazır yemek yerdim.' },
      { key: 's9', en: 'My mother used to worry about my health.', tr: 'Annem sağlığım için endişelenirdi.' },
      { key: 's10', en: 'I used to spend hours on my phone at night.', tr: 'Geceleri saatlerimi telefonda geçirirdim.' },
      { key: 's11', en: 'Did you use to have any bad habits?', tr: 'Senin de kötü alışkanlıkların var mıydı?' },
      { key: 's12', en: "I didn't use to feel this good.", tr: 'Eskiden kendimi bu kadar iyi hissetmezdim.' },
    ],
  },
  {
    id: 'usedto-before-internet',
    title: 'İnternetten önce',
    icon: 'mail-outline',
    sentences: [
      { key: 's1', en: "We didn't use to have internet at home.", tr: 'Eskiden evde internet yoktu.', alts: ["We didn't use to have the internet at home."] },
      { key: 's2', en: 'We used to have one phone in the living room.', tr: 'Oturma odasında tek bir telefonumuz vardı.' },
      { key: 's3', en: 'I used to call my friends from that phone.', tr: 'Arkadaşlarımı o telefondan arardım.' },
      { key: 's4', en: 'My sister used to listen to my calls.', tr: 'Ablam telefon konuşmalarımı dinlerdi.' },
      { key: 's5', en: 'We used to write letters to our relatives.', tr: 'Akrabalarımıza mektup yazardık.' },
      { key: 's6', en: 'A letter used to take a week to arrive.', tr: 'Bir mektubun gelmesi bir hafta sürerdi.' },
      { key: 's7', en: 'I used to listen to music on cassettes.', tr: 'Müziği kasetten dinlerdim.' },
      { key: 's8', en: 'There used to be only two channels on TV.', tr: 'Televizyonda sadece iki kanal vardı.', alts: ['There used to be just two channels on TV.'] },
      { key: 's9', en: 'My father used to buy a newspaper every morning.', tr: 'Babam her sabah gazete alırdı.' },
      { key: 's10', en: "We didn't use to take photos of our food.", tr: 'Yemeklerimizin fotoğrafını çekmezdik.' },
      { key: 's11', en: 'Did you use to write letters too?', tr: 'Sen de mektup yazar mıydın?' },
      { key: 's12', en: 'Now everything is on my phone.', tr: 'Şimdi her şey telefonumda.' },
    ],
  },
];
