import type { LadderTheme } from './types';

// Will / won't konusma merdiveni icerigi (elle yazildi): anlik kararlar,
// teklif ve sozler, gelecek tahminleri. Her tema 12 cumlelik bir konusma akisidir.
export const WILL_THEMES: LadderTheme[] = [
  {
    id: 'will-restaurant-order',
    title: 'Restoranda sipariş',
    icon: 'restaurant-outline',
    sentences: [
      { key: 's1', en: "I'm really hungry, so I'll order now.", tr: 'Çok acıktım, o yüzden hemen sipariş vereceğim.' },
      { key: 's2', en: "I'll have the lentil soup first.", tr: 'Önce mercimek çorbası alacağım.', alts: ["I'll start with the lentil soup."] },
      { key: 's3', en: "Then I'll have the chicken kebab with rice.", tr: 'Sonra pilavlı tavuk şiş alacağım.' },
      { key: 's4', en: "I won't have a salad today.", tr: 'Bugün salata almayacağım.' },
      { key: 's5', en: 'What will you have?', tr: 'Sen ne alacaksın?' },
      { key: 's6', en: "I'll drink a cold ayran with my meal.", tr: 'Yemeğin yanında soğuk bir ayran içeceğim.' },
      { key: 's7', en: "I won't drink cola tonight.", tr: 'Bu akşam kola içmeyeceğim.' },
      { key: 's8', en: 'The baklava looks delicious.', tr: 'Baklava çok lezzetli görünüyor.' },
      { key: 's9', en: "Okay, I'll have a small piece.", tr: 'Tamam, küçük bir dilim alacağım.' },
      { key: 's10', en: 'Will you share it with me?', tr: 'Benimle paylaşır mısın?' },
      { key: 's11', en: "I'll have a Turkish coffee after that.", tr: 'Ondan sonra bir Türk kahvesi içeceğim.', alts: ["I'll drink a Turkish coffee after that."] },
      { key: 's12', en: "Don't worry, I'll pay the bill tonight.", tr: 'Merak etme, bu akşam hesabı ben ödeyeceğim.' },
    ],
  },
  {
    id: 'will-helping-sick-friend',
    title: 'Hasta arkadaşıma yardım',
    icon: 'heart-outline',
    sentences: [
      { key: 's1', en: 'You look really tired today.', tr: 'Bugün gerçekten yorgun görünüyorsun.' },
      { key: 's2', en: "Sit down, I'll make you some tea.", tr: 'Sen otur, ben sana çay yaparım.' },
      { key: 's3', en: "I'll go to the pharmacy for you.", tr: 'Senin için eczaneye ben giderim.' },
      { key: 's4', en: "I'll get some fruit and orange juice too.", tr: 'Biraz meyve ve portakal suyu da alırım.', alts: ["I'll buy some fruit and orange juice too."] },
      { key: 's5', en: "Give me your list, I won't forget anything.", tr: 'Listeni bana ver, hiçbir şeyi unutmayacağım.' },
      { key: 's6', en: "I'll take your dog for a walk tonight.", tr: 'Bu akşam köpeğini ben gezdiririm.' },
      { key: 's7', en: "Don't cook, I'll bring dinner.", tr: 'Yemek yapma, akşam yemeğini ben getiririm.' },
      { key: 's8', en: 'Will you call me tomorrow morning?', tr: 'Yarın sabah beni arar mısın?' },
      { key: 's9', en: "I won't stay long, because you need rest.", tr: 'Uzun kalmayacağım, çünkü dinlenmen gerek.' },
      { key: 's10', en: "I'll tell your boss about it.", tr: 'Patronuna ben haber veririm.' },
      { key: 's11', en: "I'm sure you'll feel better tomorrow.", tr: 'Eminim yarın kendini daha iyi hissedeceksin.' },
      { key: 's12', en: "I promise I'll come again on Sunday.", tr: 'Söz veriyorum, pazar günü yine geleceğim.' },
    ],
  },
  {
    id: 'will-weather-tomorrow',
    title: 'Yarının havası',
    icon: 'partly-sunny-outline',
    sentences: [
      { key: 's1', en: 'I think it will rain tomorrow.', tr: 'Sanırım yarın yağmur yağacak.' },
      { key: 's2', en: 'The sky is very dark tonight.', tr: 'Bu akşam gökyüzü çok karanlık.' },
      { key: 's3', en: 'It will be cold in the morning.', tr: 'Sabah hava soğuk olacak.' },
      { key: 's4', en: "I'll take my umbrella to work.", tr: 'Şemsiyemi işe götüreceğim.' },
      { key: 's5', en: "It won't snow, but it will be windy.", tr: 'Kar yağmayacak ama rüzgârlı olacak.' },
      { key: 's6', en: "The rain won't stop until the evening.", tr: 'Yağmur akşama kadar dinmeyecek.' },
      { key: 's7', en: 'The traffic will be terrible, as usual.', tr: 'Trafik her zamanki gibi berbat olacak.' },
      { key: 's8', en: "So I'll take the metro, not the car.", tr: 'O yüzden arabayla değil, metroyla gideceğim.', alts: ["So I'll go by metro, not by car."] },
      { key: 's9', en: 'Will it be sunny on the weekend?', tr: 'Hafta sonu hava güneşli olacak mı?' },
      { key: 's10', en: 'I hope it will be warm on Saturday.', tr: 'Umarım cumartesi hava sıcak olur.' },
      { key: 's11', en: "I think we'll have a picnic by the sea.", tr: 'Sanırım deniz kenarında piknik yapacağız.' },
      { key: 's12', en: 'What will the weather be like in your city?', tr: 'Senin şehrinde hava nasıl olacak?' },
    ],
  },
  {
    id: 'will-new-year-promises',
    title: 'Yeni yıl sözlerim',
    icon: 'sparkles-outline',
    sentences: [
      { key: 's1', en: "Tonight is New Year's Eve.", tr: 'Bu gece yılbaşı.' },
      { key: 's2', en: "I'll wake up earlier next year.", tr: 'Gelecek yıl daha erken kalkacağım.', alts: ["I'll get up earlier next year."] },
      { key: 's3', en: "I'll walk for thirty minutes every day.", tr: 'Her gün otuz dakika yürüyeceğim.' },
      { key: 's4', en: "I won't eat fast food during the week.", tr: 'Hafta içi hazır yemek yemeyeceğim.' },
      { key: 's5', en: "I'll drink more water and less coffee.", tr: 'Daha çok su, daha az kahve içeceğim.' },
      { key: 's6', en: "I'll spend less money on clothes.", tr: 'Kıyafetlere daha az para harcayacağım.' },
      { key: 's7', en: "I'll save some money for a summer holiday.", tr: 'Yaz tatili için biraz para biriktireceğim.' },
      { key: 's8', en: "I'll study English every day with this app.", tr: 'Bu uygulamayla her gün İngilizce çalışacağım.', alts: ["I'll learn English every day with this app."] },
      { key: 's9', en: "I'll call my grandmother every Sunday.", tr: 'Her pazar büyükannemi arayacağım.' },
      { key: 's10', en: "It won't be easy, but I'll try.", tr: 'Kolay olmayacak ama deneyeceğim.' },
      { key: 's11', en: 'What will you change next year?', tr: 'Sen gelecek yıl neyi değiştireceksin?' },
      { key: 's12', en: "I'm sure it will be a great year.", tr: 'Eminim harika bir yıl olacak.' },
    ],
  },
  {
    id: 'will-future-life',
    title: 'Gelecekte hayat',
    icon: 'rocket-outline',
    sentences: [
      { key: 's1', en: 'Life will be very different in thirty years.', tr: 'Otuz yıl sonra hayat çok farklı olacak.' },
      { key: 's2', en: 'I think robots will do most of the housework.', tr: 'Bence ev işlerinin çoğunu robotlar yapacak.' },
      { key: 's3', en: 'Cars will drive themselves.', tr: 'Arabalar kendi kendine gidecek.' },
      { key: 's4', en: "People won't learn to drive.", tr: 'İnsanlar araba kullanmayı öğrenmeyecek.' },
      { key: 's5', en: 'Most people will work from home.', tr: 'Çoğu insan evden çalışacak.' },
      { key: 's6', en: 'Cities will be greener and quieter.', tr: 'Şehirler daha yeşil ve daha sessiz olacak.' },
      { key: 's7', en: "We won't use cash anymore.", tr: 'Artık nakit para kullanmayacağız.' },
      { key: 's8', en: 'Everybody will pay with their phone.', tr: 'Herkes telefonuyla ödeme yapacak.', alts: ['Everyone will pay with their phone.'] },
      { key: 's9', en: 'People will live longer than today.', tr: 'İnsanlar bugünden daha uzun yaşayacak.' },
      { key: 's10', en: "Maybe we'll spend our holidays on the Moon.", tr: "Belki tatillerimizi Ay'da geçireceğiz." },
      { key: 's11', en: 'Will people still read books?', tr: 'İnsanlar hâlâ kitap okuyacak mı?' },
      { key: 's12', en: 'I think they will, because books are special.', tr: 'Bence okuyacaklar, çünkü kitaplar özel.' },
    ],
  },
  {
    id: 'will-clothes-shopping',
    title: 'Mağazada alışveriş',
    icon: 'shirt-outline',
    sentences: [
      { key: 's1', en: 'I need a new jacket for the winter.', tr: 'Kış için yeni bir monta ihtiyacım var.' },
      { key: 's2', en: "I'll try on this blue one.", tr: 'Şu maviyi deneyeceğim.', alts: ["I'll try this blue one on."] },
      { key: 's3', en: "It's too small, so I'll try a bigger size.", tr: 'Çok küçük, o yüzden bir beden büyüğünü deneyeceğim.' },
      { key: 's4', en: "Perfect, I'll take it.", tr: 'Harika, bunu alacağım.', alts: ["Perfect, I'll buy it."] },
      { key: 's5', en: 'Oh, these shoes are on sale.', tr: 'Aa, bu ayakkabılar indirimde.' },
      { key: 's6', en: "I'll get the black ones too.", tr: 'Siyahları da alacağım.' },
      { key: 's7', en: "I won't buy a bag today.", tr: 'Bugün çanta almayacağım.' },
      { key: 's8', en: 'I think my sister will love this scarf.', tr: 'Bence kız kardeşim bu atkıya bayılacak.' },
      { key: 's9', en: "I'll buy it for her birthday.", tr: 'Doğum günü için onu alacağım.' },
      { key: 's10', en: 'Will you wrap it for me, please?', tr: 'Bunu benim için paketler misiniz?' },
      { key: 's11', en: "I'll pay by card.", tr: 'Kartla ödeyeceğim.' },
      { key: 's12', en: "I won't spend any more money today.", tr: 'Bugün daha fazla para harcamayacağım.' },
    ],
  },
];
