import { routine } from '../types';

// Rutin 2: kahvalti yapmak. Kurallar: docs/SPEAKING_RULES.md.
export const BREAKFAST = routine({
  id: 'ps-breakfast',
  title: 'Kahvaltı yapmak',
  icon: 'restaurant-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually have breakfast at home.', tr: 'Genelde evde kahvaltı yaparım.', cue: 'ben · genelde · kahvaltı yapmak · evde' },
        { key: 's2', en: 'My dad always has breakfast at seven.', tr: 'Babam her zaman yedide kahvaltı yapar.', cue: 'babam · her zaman · kahvaltı yapmak · saat 7' },
        { key: 's3', en: 'You often have breakfast in bed on Sundays.', tr: 'Pazar günleri sık sık yatakta kahvaltı yaparsın.', cue: 'sen · sık sık · kahvaltı yapmak · yatakta · pazar günleri' },
        { key: 's4', en: 'She sometimes has breakfast at work.', tr: 'O bazen işte kahvaltı yapar.', cue: 'o · bazen · kahvaltı yapmak · işte' },
        { key: 's5', en: 'We rarely have breakfast together on weekdays.', tr: 'Hafta içi nadiren birlikte kahvaltı yaparız.', cue: 'biz · nadiren · kahvaltı yapmak · birlikte · hafta içi' },
        { key: 's6', en: 'My brother never has breakfast before school.', tr: 'Erkek kardeşim okuldan önce asla kahvaltı yapmaz.', cue: 'erkek kardeşim · asla · kahvaltı yapmak · okuldan önce' },
        { key: 's7', en: 'They occasionally have breakfast by the sea.', tr: 'Onlar ara sıra deniz kenarında kahvaltı yapar.', cue: 'onlar · ara sıra · kahvaltı yapmak · deniz kenarında' },
        { key: 's8', en: 'My mom usually has breakfast with the whole family.', tr: 'Annem genelde bütün aileyle kahvaltı yapar.', cue: 'annem · genelde · kahvaltı yapmak · bütün aileyle' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often have eggs for breakfast.', tr: 'Kahvaltıda sık sık yumurta yerim.', alts: ['I often eat eggs for breakfast.'], cue: 'ben · sık sık · yemek · yumurta · kahvaltıda' },
        { key: 's10', en: 'My sister always has breakfast in a hurry.', tr: 'Kız kardeşim her zaman aceleyle kahvaltı yapar.', cue: 'kız kardeşim · her zaman · kahvaltı yapmak · aceleyle' },
        { key: 's11', en: 'He usually has breakfast at six thirty on weekdays.', tr: 'O hafta içi genelde altı buçukta kahvaltı yapar.', alts: ['He usually has breakfast at half past six on weekdays.'], cue: 'o · genelde · kahvaltı yapmak · saat 6.30 · hafta içi' },
        { key: 's12', en: 'You sometimes have breakfast in the kitchen.', tr: 'Bazen mutfakta kahvaltı yaparsın.', cue: 'sen · bazen · kahvaltı yapmak · mutfakta' },
        { key: 's13', en: 'We usually have a big breakfast on Sundays.', tr: 'Pazar günleri genelde büyük bir kahvaltı yaparız.', cue: 'biz · genelde · büyük bir kahvaltı yapmak · pazar günleri' },
        { key: 's14', en: 'My grandpa hardly ever has breakfast after eight.', tr: 'Dedem neredeyse hiç sekizden sonra kahvaltı yapmaz.', cue: 'dedem · neredeyse hiç · kahvaltı yapmak · saat 8’den sonra' },
        { key: 's15', en: 'I rarely have breakfast before nine on weekends.', tr: 'Hafta sonları nadiren dokuzdan önce kahvaltı yaparım.', cue: 'ben · nadiren · kahvaltı yapmak · saat 9’dan önce · hafta sonları' },
        { key: 's16', en: 'The kids always have cereal for breakfast.', tr: 'Çocuklar kahvaltıda her zaman mısır gevreği yer.', alts: ['The kids always eat cereal for breakfast.'], cue: 'çocuklar · her zaman · yemek · mısır gevreği · kahvaltıda' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually have breakfast on weekdays.", tr: 'Hafta içi genelde kahvaltı yapmam.', cue: 'ben · değil · genelde · kahvaltı yapmak · hafta içi' },
        { key: 's18', en: "My brother doesn't always have breakfast at home.", tr: 'Erkek kardeşim her zaman evde kahvaltı yapmaz.', cue: 'erkek kardeşim · değil · her zaman · kahvaltı yapmak · evde' },
        { key: 's19', en: "You don't often have breakfast with us.", tr: 'Pek sık bizimle kahvaltı yapmazsın.', cue: 'sen · değil · sık sık · kahvaltı yapmak · bizimle' },
        { key: 's20', en: "She doesn't usually have breakfast before work.", tr: 'O genelde işten önce kahvaltı yapmaz.', cue: 'o · değil · genelde · kahvaltı yapmak · işten önce' },
        { key: 's21', en: "We don't always have breakfast together.", tr: 'Her zaman birlikte kahvaltı yapmayız.', cue: 'biz · değil · her zaman · kahvaltı yapmak · birlikte' },
        { key: 's22', en: "My mom doesn't usually have breakfast until ten.", tr: 'Annem genelde ona kadar kahvaltı yapmaz.', cue: 'annem · değil · genelde · kahvaltı yapmak · saat 10’a kadar' },
        { key: 's23', en: "They don't often have breakfast at home on weekends.", tr: 'Hafta sonları pek sık evde kahvaltı yapmazlar.', cue: 'onlar · değil · sık sık · kahvaltı yapmak · evde · hafta sonları' },
        { key: 's24', en: "He doesn't usually have much for breakfast.", tr: 'O kahvaltıda genelde pek bir şey yemez.', alts: ["He doesn't usually eat much for breakfast."], cue: 'o · değil · genelde · yemek · çok · kahvaltıda' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually have breakfast at home?', tr: 'Genelde evde mi kahvaltı yaparsın?', cue: 'mi · sen · genelde · kahvaltı yapmak · evde' },
        { key: 's26', en: 'Does your dad always have breakfast with you?', tr: 'Baban her zaman seninle mi kahvaltı yapar?', cue: 'mi · baban · her zaman · kahvaltı yapmak · seninle' },
        { key: 's27', en: 'Does she often have breakfast at work?', tr: 'O sık sık işte mi kahvaltı yapar?', cue: 'mi · o · sık sık · kahvaltı yapmak · işte' },
        { key: 's28', en: 'Do they usually have breakfast together?', tr: 'Genelde birlikte mi kahvaltı yaparlar?', cue: 'mi · onlar · genelde · kahvaltı yapmak · birlikte' },
        { key: 's29', en: 'What time do you usually have breakfast?', tr: 'Genelde saat kaçta kahvaltı yaparsın?', cue: 'saat kaçta · mi · sen · genelde · kahvaltı yapmak' },
        { key: 's30', en: 'How often do you have breakfast with your parents?', tr: 'Ne sıklıkla annenle babanla kahvaltı yaparsın?', cue: 'ne sıklıkla · mi · sen · kahvaltı yapmak · annenle babanla' },
        { key: 's31', en: 'Why does your brother never have breakfast?', tr: 'Erkek kardeşin neden hiç kahvaltı yapmıyor?', cue: 'neden · mi · erkek kardeşin · asla · kahvaltı yapmak' },
        { key: 's32', en: 'What do you usually have for breakfast?', tr: 'Kahvaltıda genelde ne yersin?', alts: ['What do you usually eat for breakfast?'], cue: 'ne · mi · sen · genelde · yemek · kahvaltıda' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always has breakfast standing up.', tr: 'Ev arkadaşım her zaman ayakta kahvaltı yapar.', cue: 'ev arkadaşım · her zaman · kahvaltı yapmak · ayakta' },
        { key: 's34', en: "I don't usually have breakfast alone.", tr: 'Genelde yalnız kahvaltı yapmam.', alts: ["I don't usually have breakfast by myself."], cue: 'ben · değil · genelde · kahvaltı yapmak · yalnız' },
        { key: 's35', en: 'Do you often have breakfast in front of the TV?', tr: 'Sık sık televizyonun karşısında kahvaltı yapar mısın?', cue: 'mi · sen · sık sık · kahvaltı yapmak · televizyonun karşısında' },
        { key: 's36', en: 'My grandma never has breakfast without tea.', tr: 'Büyükannem asla çaysız kahvaltı yapmaz.', cue: 'büyükannem · asla · kahvaltı yapmak · çaysız' },
        { key: 's37', en: 'Our neighbors occasionally have breakfast in the garden.', tr: 'Komşularımız ara sıra bahçede kahvaltı yapar.', cue: 'komşularımız · ara sıra · kahvaltı yapmak · bahçede' },
        { key: 's38', en: 'Where do you usually have breakfast on weekends?', tr: 'Hafta sonları genelde nerede kahvaltı yaparsın?', cue: 'nerede · mi · sen · genelde · kahvaltı yapmak · hafta sonları' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: "I usually have breakfast at eight, but I don't have lunch until two.", tr: 'Genelde sekizde kahvaltı yaparım ama ikiye kadar öğle yemeği yemem.', alts: ["I usually have breakfast at eight, but I don't eat lunch until two."], cue: 'ben · genelde · kahvaltı yapmak · saat 8 · ama · ben · değil · öğle yemeği yemek · saat 2’ye kadar' },
        { key: 's40', en: "My brother never has breakfast, so he's always hungry at school.", tr: 'Erkek kardeşim asla kahvaltı yapmaz, bu yüzden okulda hep açtır.', cue: 'erkek kardeşim · asla · kahvaltı yapmak · bu yüzden · o · her zaman · aç · okulda' },
        { key: 's41', en: "She rarely has breakfast because she's never hungry in the morning.", tr: 'O nadiren kahvaltı yapar çünkü sabahları hiç aç olmaz.', alts: ["She rarely has breakfast because she's never hungry in the mornings."], cue: 'o · nadiren · kahvaltı yapmak · çünkü · o · asla · aç · sabahları' },
        { key: 's42', en: 'We usually have breakfast together and then go to work.', tr: 'Genelde birlikte kahvaltı yapar, sonra işe gideriz.', cue: 'biz · genelde · kahvaltı yapmak · birlikte · ve · sonra · işe gitmek' },
        { key: 's43', en: 'I occasionally have breakfast on the balcony and read a book.', tr: 'Ara sıra balkonda kahvaltı yapar ve kitap okurum.', cue: 'ben · ara sıra · kahvaltı yapmak · balkonda · ve · kitap okumak' },
        { key: 's44', en: 'Do you usually have breakfast at home or at work?', tr: 'Genelde evde mi kahvaltı yaparsın, yoksa işte mi?', cue: 'mi · sen · genelde · kahvaltı yapmak · evde · yoksa · işte' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When I have breakfast late, I usually skip lunch.', tr: 'Geç kahvaltı yaptığımda genelde öğle yemeğini atlarım.', cue: '-dığında · ben · kahvaltı yapmak · geç · ben · genelde · atlamak · öğle yemeği' },
        { key: 's46', en: 'My dad always has breakfast before he leaves the house.', tr: 'Babam her zaman evden çıkmadan önce kahvaltı yapar.', alts: ['My dad always has breakfast before he leaves home.'], cue: 'babam · her zaman · kahvaltı yapmak · -madan önce · o · çıkmak · evden' },
        { key: 's47', en: 'Even though he wakes up late, he always has breakfast.', tr: 'Geç uyanmasına rağmen her zaman kahvaltı yapar.', alts: ['Although he wakes up late, he always has breakfast.'], cue: '-masına rağmen · o · uyanmak · geç · o · her zaman · kahvaltı yapmak' },
        { key: 's48', en: 'As soon as I have breakfast, I usually brush my teeth.', tr: 'Kahvaltı yapar yapmaz genelde dişlerimi fırçalarım.', cue: '-ar -maz · ben · kahvaltı yapmak · ben · genelde · dişlerimi fırçalamak' },
        { key: 's49', en: "My roommate doesn't usually have breakfast until she gets to work.", tr: 'Ev arkadaşım genelde işe varana kadar kahvaltı yapmaz.', cue: 'ev arkadaşım · değil · genelde · kahvaltı yapmak · -ana kadar · o · varmak · işe' },
        { key: 's50', en: 'Do you usually have breakfast after you go to the gym?', tr: 'Spora gittikten sonra genelde kahvaltı yapar mısın?', cue: 'mi · sen · genelde · kahvaltı yapmak · -dıktan sonra · sen · spora gitmek' },
      ],
    },
  ],
});
