import { routine } from '../types';

// Rutin 3: kahve yapmak. Kurallar: docs/SPEAKING_RULES.md.
export const COFFEE = routine({
  id: 'ps-coffee',
  title: 'Kahve yapmak',
  icon: 'cafe-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually make coffee at seven.', tr: 'Genelde yedide kahve yaparım.', cue: 'ben · genelde · kahve yapmak · saat 7' },
        { key: 's2', en: 'My dad always makes Turkish coffee after breakfast.', tr: 'Babam kahvaltıdan sonra her zaman Türk kahvesi yapar.', cue: 'babam · her zaman · Türk kahvesi yapmak · kahvaltıdan sonra' },
        { key: 's3', en: 'You often make coffee for the whole office.', tr: 'Sık sık bütün ofise kahve yaparsın.', cue: 'sen · sık sık · kahve yapmak · bütün ofise' },
        { key: 's4', en: 'She sometimes makes coffee with milk.', tr: 'O bazen sütlü kahve yapar.', cue: 'o · bazen · kahve yapmak · sütlü' },
        { key: 's5', en: 'We rarely make filter coffee at home.', tr: 'Evde nadiren filtre kahve yaparız.', cue: 'biz · nadiren · filtre kahve yapmak · evde' },
        { key: 's6', en: 'My roommate never makes coffee for me.', tr: 'Ev arkadaşım bana asla kahve yapmaz.', alts: ['My roommate never makes me coffee.'], cue: 'ev arkadaşım · asla · kahve yapmak · bana' },
        { key: 's7', en: 'They occasionally make coffee in the afternoon.', tr: 'Onlar ara sıra öğleden sonra kahve yapar.', cue: 'onlar · ara sıra · kahve yapmak · öğleden sonra' },
        { key: 's8', en: 'My mom usually makes coffee for the guests.', tr: 'Annem genelde misafirlere kahve yapar.', cue: 'annem · genelde · kahve yapmak · misafirlere' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often make a cup of coffee before work.', tr: 'Sık sık işten önce bir fincan kahve yaparım.', cue: 'ben · sık sık · bir fincan kahve yapmak · işten önce' },
        { key: 's10', en: 'My sister always makes coffee without sugar.', tr: 'Kız kardeşim her zaman şekersiz kahve yapar.', cue: 'kız kardeşim · her zaman · kahve yapmak · şekersiz' },
        { key: 's11', en: 'He usually makes strong coffee.', tr: 'O genelde sert kahve yapar.', cue: 'o · genelde · sert kahve yapmak' },
        { key: 's12', en: 'You sometimes make coffee late at night.', tr: 'Bazen gece geç saatte kahve yaparsın.', cue: 'sen · bazen · kahve yapmak · gece geç saatte' },
        { key: 's13', en: 'We usually make coffee together on Sundays.', tr: 'Pazar günleri genelde birlikte kahve yaparız.', cue: 'biz · genelde · kahve yapmak · birlikte · pazar günleri' },
        { key: 's14', en: 'My grandpa hardly ever makes filter coffee.', tr: 'Dedem neredeyse hiç filtre kahve yapmaz.', cue: 'dedem · neredeyse hiç · filtre kahve yapmak' },
        { key: 's15', en: 'I rarely make coffee in the evening.', tr: 'Akşamları nadiren kahve yaparım.', alts: ['I rarely make coffee in the evenings.'], cue: 'ben · nadiren · kahve yapmak · akşamları' },
        { key: 's16', en: 'My colleagues always make coffee after lunch.', tr: 'İş arkadaşlarım her zaman öğle yemeğinden sonra kahve yapar.', cue: 'iş arkadaşlarım · her zaman · kahve yapmak · öğle yemeğinden sonra' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually make coffee on weekdays.", tr: 'Hafta içi genelde kahve yapmam.', cue: 'ben · değil · genelde · kahve yapmak · hafta içi' },
        { key: 's18', en: "My dad doesn't always make coffee in the morning.", tr: 'Babam sabahları her zaman kahve yapmaz.', alts: ["My dad doesn't always make coffee in the mornings."], cue: 'babam · değil · her zaman · kahve yapmak · sabahları' },
        { key: 's19', en: "You don't often make Turkish coffee.", tr: 'Pek sık Türk kahvesi yapmazsın.', cue: 'sen · değil · sık sık · Türk kahvesi yapmak' },
        { key: 's20', en: "She doesn't usually make coffee with sugar.", tr: 'O genelde şekerli kahve yapmaz.', cue: 'o · değil · genelde · kahve yapmak · şekerli' },
        { key: 's21', en: "We don't always make coffee at home.", tr: 'Her zaman evde kahve yapmayız.', cue: 'biz · değil · her zaman · kahve yapmak · evde' },
        { key: 's22', en: "My mom doesn't usually make coffee after dinner.", tr: 'Annem genelde akşam yemeğinden sonra kahve yapmaz.', cue: 'annem · değil · genelde · kahve yapmak · akşam yemeğinden sonra' },
        { key: 's23', en: "They don't often make coffee for their guests.", tr: 'Misafirlerine pek sık kahve yapmazlar.', cue: 'onlar · değil · sık sık · kahve yapmak · misafirlerine' },
        { key: 's24', en: "He doesn't usually make coffee at work.", tr: 'O işte genelde kahve yapmaz.', cue: 'o · değil · genelde · kahve yapmak · işte' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually make coffee in the morning?', tr: 'Sabahları genelde kahve yapar mısın?', alts: ['Do you usually make coffee in the mornings?'], cue: 'mi · sen · genelde · kahve yapmak · sabahları' },
        { key: 's26', en: 'Does your dad always make Turkish coffee?', tr: 'Baban her zaman Türk kahvesi mi yapar?', cue: 'mi · baban · her zaman · Türk kahvesi yapmak' },
        { key: 's27', en: 'Does she often make coffee with milk?', tr: 'O sık sık sütlü kahve yapar mı?', cue: 'mi · o · sık sık · kahve yapmak · sütlü' },
        { key: 's28', en: 'Do they sometimes make filter coffee at work?', tr: 'İşte bazen filtre kahve yaparlar mı?', cue: 'mi · onlar · bazen · filtre kahve yapmak · işte' },
        { key: 's29', en: 'What time do you usually make coffee?', tr: 'Genelde saat kaçta kahve yaparsın?', cue: 'saat kaçta · mi · sen · genelde · kahve yapmak' },
        { key: 's30', en: 'How often do you make coffee at home?', tr: 'Evde ne sıklıkla kahve yaparsın?', cue: 'ne sıklıkla · mi · sen · kahve yapmak · evde' },
        { key: 's31', en: 'Why does your sister always make coffee without sugar?', tr: 'Kız kardeşin neden hep şekersiz kahve yapar?', cue: 'neden · mi · kız kardeşin · her zaman · kahve yapmak · şekersiz' },
        { key: 's32', en: 'What kind of coffee do you usually make?', tr: 'Genelde ne tür kahve yaparsın?', alts: ['What type of coffee do you usually make?'], cue: 'ne tür kahve · mi · sen · genelde · yapmak' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always makes coffee for both of us.', tr: 'Ev arkadaşım her zaman ikimize de kahve yapar.', cue: 'ev arkadaşım · her zaman · kahve yapmak · ikimize de' },
        { key: 's34', en: "I don't usually make coffee after four.", tr: 'Genelde dörtten sonra kahve yapmam.', cue: 'ben · değil · genelde · kahve yapmak · saat 4’ten sonra' },
        { key: 's35', en: 'Do you often make coffee for your parents?', tr: 'Annenle babana sık sık kahve yapar mısın?', cue: 'mi · sen · sık sık · kahve yapmak · annenle babana' },
        { key: 's36', en: 'My grandma occasionally makes Turkish coffee for the neighbors.', tr: 'Büyükannem ara sıra komşulara Türk kahvesi yapar.', cue: 'büyükannem · ara sıra · Türk kahvesi yapmak · komşulara' },
        { key: 's37', en: 'My uncle hardly ever makes coffee at home.', tr: 'Amcam evde neredeyse hiç kahve yapmaz.', cue: 'amcam · neredeyse hiç · kahve yapmak · evde' },
        { key: 's38', en: 'Why does your roommate never make coffee?', tr: 'Ev arkadaşın neden hiç kahve yapmaz?', cue: 'neden · mi · ev arkadaşın · asla · kahve yapmak' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I usually make coffee at home, but I sometimes buy it on the way.', tr: 'Genelde evde kahve yaparım ama bazen yolda alırım.', alts: ['I usually make coffee at home, but I sometimes buy it on my way.'], cue: 'ben · genelde · kahve yapmak · evde · ama · ben · bazen · almak · onu · yolda' },
        { key: 's40', en: 'My brother never makes coffee, so I always make it for him.', tr: 'Erkek kardeşim asla kahve yapmaz, bu yüzden ona hep ben yaparım.', cue: 'erkek kardeşim · asla · kahve yapmak · bu yüzden · ben · her zaman · yapmak · onu · ona' },
        { key: 's41', en: 'She usually makes coffee at night because she works late.', tr: 'O genelde gece kahve yapar çünkü geç saate kadar çalışır.', cue: 'o · genelde · kahve yapmak · gece · çünkü · o · çalışmak · geç saate kadar' },
        { key: 's42', en: 'We sometimes make Turkish coffee and sit on the balcony.', tr: 'Bazen Türk kahvesi yapıp balkonda otururuz.', cue: 'biz · bazen · Türk kahvesi yapmak · ve · oturmak · balkonda' },
        { key: 's43', en: 'My mom usually makes coffee and reads the news.', tr: 'Annem genelde kahve yapar ve haberleri okur.', cue: 'annem · genelde · kahve yapmak · ve · haberleri okumak' },
        { key: 's44', en: 'Do you usually make coffee, or do you prefer tea?', tr: 'Genelde kahve mi yaparsın, yoksa çayı mı tercih edersin?', cue: 'mi · sen · genelde · kahve yapmak · yoksa · mi · sen · tercih etmek · çay' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When my dad makes Turkish coffee, he always adds a little sugar.', tr: 'Babam Türk kahvesi yaptığında her zaman biraz şeker ekler.', cue: '-dığında · babam · Türk kahvesi yapmak · o · her zaman · eklemek · biraz şeker' },
        { key: 's46', en: 'I always make coffee before I check my email.', tr: 'E-postalarıma bakmadan önce her zaman kahve yaparım.', alts: ['I always make coffee before I check my emails.'], cue: 'ben · her zaman · kahve yapmak · -madan önce · ben · bakmak · e-postalarıma' },
        { key: 's47', en: 'Even though he hardly ever drinks coffee, he always makes it for his guests.', tr: 'Neredeyse hiç kahve içmemesine rağmen misafirlerine her zaman kahve yapar.', alts: ['Although he hardly ever drinks coffee, he always makes it for his guests.'], cue: '-masına rağmen · o · neredeyse hiç · kahve içmek · o · her zaman · yapmak · onu · misafirlerine' },
        { key: 's48', en: 'As soon as I get to the office, I usually make a cup of coffee.', tr: 'Ofise varır varmaz genelde bir fincan kahve yaparım.', alts: ['As soon as I arrive at the office, I usually make a cup of coffee.'], cue: '-ar -maz · ben · varmak · ofise · ben · genelde · bir fincan kahve yapmak' },
        { key: 's49', en: "My mom doesn't usually make coffee until the kids leave for school.", tr: 'Annem genelde çocuklar okula gidene kadar kahve yapmaz.', alts: ["My mom doesn't usually make coffee until the kids go to school."], cue: 'annem · değil · genelde · kahve yapmak · -ana kadar · çocuklar · okula gitmek' },
        { key: 's50', en: 'Do you usually make coffee after you have lunch?', tr: 'Öğle yemeği yedikten sonra genelde kahve yapar mısın?', alts: ['Do you usually make coffee after you eat lunch?'], cue: 'mi · sen · genelde · kahve yapmak · -dıktan sonra · sen · öğle yemeği yemek' },
      ],
    },
  ],
});
