import { routine } from '../types';

// Rutin 6: giyinmek. Kurallar: docs/SPEAKING_RULES.md.
export const GET_DRESSED = routine({
  id: 'ps-get-dressed',
  title: 'Giyinmek',
  icon: 'shirt-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually get dressed after breakfast.', tr: 'Genelde kahvaltıdan sonra giyinirim.', cue: 'ben · genelde · giyinmek · kahvaltıdan sonra' },
        { key: 's2', en: 'My dad always gets dressed in five minutes.', tr: 'Babam her zaman beş dakikada giyinir.', cue: 'babam · her zaman · giyinmek · 5 dakikada' },
        { key: 's3', en: 'You often get dressed in the dark.', tr: 'Sık sık karanlıkta giyinirsin.', cue: 'sen · sık sık · giyinmek · karanlıkta' },
        { key: 's4', en: 'She sometimes gets dressed in a hurry.', tr: 'O bazen aceleyle giyinir.', alts: ['She sometimes gets dressed in a rush.'], cue: 'o · bazen · giyinmek · aceleyle' },
        { key: 's5', en: 'We rarely get dressed before ten on Sundays.', tr: 'Pazar günleri nadiren ondan önce giyiniriz.', cue: 'biz · nadiren · giyinmek · saat 10’dan önce · pazar günleri' },
        { key: 's6', en: 'My little brother never gets dressed by himself.', tr: 'Küçük erkek kardeşim asla kendi kendine giyinmez.', alts: ['My little brother never gets dressed on his own.'], cue: 'küçük erkek kardeşim · asla · giyinmek · kendi kendine' },
        { key: 's7', en: 'They occasionally get dressed in the living room.', tr: 'Onlar ara sıra salonda giyinir.', cue: 'onlar · ara sıra · giyinmek · salonda' },
        { key: 's8', en: 'My mom usually gets dressed at six thirty.', tr: 'Annem genelde altı buçukta giyinir.', alts: ['My mom usually gets dressed at half past six.'], cue: 'annem · genelde · giyinmek · saat 6.30' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often get dressed in front of the TV.', tr: 'Sık sık televizyonun önünde giyinirim.', cue: 'ben · sık sık · giyinmek · televizyonun önünde' },
        { key: 's10', en: 'My sister always gets dressed slowly.', tr: 'Kız kardeşim her zaman yavaş giyinir.', cue: 'kız kardeşim · her zaman · giyinmek · yavaş' },
        { key: 's11', en: 'He usually gets dressed in ten minutes.', tr: 'O genelde on dakikada giyinir.', cue: 'o · genelde · giyinmek · 10 dakikada' },
        { key: 's12', en: 'You sometimes get dressed without looking in the mirror.', tr: 'Bazen aynaya bakmadan giyinirsin.', alts: ['You sometimes get dressed without looking at the mirror.'], cue: 'sen · bazen · giyinmek · aynaya bakmadan' },
        { key: 's13', en: 'We usually get dressed quickly in the winter.', tr: 'Kışın genelde çabuk giyiniriz.', alts: ['We usually get dressed quickly in winter.'], cue: 'biz · genelde · giyinmek · çabuk · kışın' },
        { key: 's14', en: 'My roommate hardly ever gets dressed on Sundays.', tr: 'Ev arkadaşım pazar günleri neredeyse hiç giyinmez.', cue: 'ev arkadaşım · neredeyse hiç · giyinmek · pazar günleri' },
        { key: 's15', en: 'I rarely get dressed before breakfast.', tr: 'Nadiren kahvaltıdan önce giyinirim.', cue: 'ben · nadiren · giyinmek · kahvaltıdan önce' },
        { key: 's16', en: 'The kids always get dressed in their room.', tr: 'Çocuklar her zaman odalarında giyinir.', alts: ['The kids always get dressed in their rooms.'], cue: 'çocuklar · her zaman · giyinmek · odalarında' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually get dressed right away.", tr: 'Genelde hemen giyinmem.', cue: 'ben · değil · genelde · giyinmek · hemen' },
        { key: 's18', en: "My son doesn't always get dressed without help.", tr: 'Oğlum her zaman yardımsız giyinmez.', cue: 'oğlum · değil · her zaman · giyinmek · yardımsız' },
        { key: 's19', en: "You don't often get dressed this early.", tr: 'Pek sık bu kadar erken giyinmezsin.', cue: 'sen · değil · sık sık · giyinmek · bu kadar erken' },
        { key: 's20', en: "She doesn't usually get dressed before her coffee.", tr: 'O genelde kahvesini içmeden giyinmez.', cue: 'o · değil · genelde · giyinmek · kahvesinden önce' },
        { key: 's21', en: "We don't always get dressed at the same time.", tr: 'Her zaman aynı anda giyinmeyiz.', cue: 'biz · değil · her zaman · giyinmek · aynı anda' },
        { key: 's22', en: "My mom doesn't usually get dressed before seven.", tr: 'Annem genelde yediden önce giyinmez.', cue: 'annem · değil · genelde · giyinmek · saat 7’den önce' },
        { key: 's23', en: "They don't usually get dressed on Sunday mornings.", tr: 'Pazar sabahları genelde giyinmezler.', cue: 'onlar · değil · genelde · giyinmek · pazar sabahları' },
        { key: 's24', en: "He doesn't often get dressed before lunch on weekends.", tr: 'O hafta sonları pek sık öğle yemeğinden önce giyinmez.', cue: 'o · değil · sık sık · giyinmek · öğle yemeğinden önce · hafta sonları' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually get dressed before breakfast?', tr: 'Genelde kahvaltıdan önce mi giyinirsin?', cue: 'mi · sen · genelde · giyinmek · kahvaltıdan önce' },
        { key: 's26', en: 'Does your son always get dressed by himself?', tr: 'Oğlun her zaman kendi kendine mi giyinir?', alts: ['Does your son always get dressed on his own?'], cue: 'mi · oğlun · her zaman · giyinmek · kendi kendine' },
        { key: 's27', en: 'Does she often get dressed in a hurry?', tr: 'O sık sık aceleyle mi giyinir?', alts: ['Does she often get dressed in a rush?'], cue: 'mi · o · sık sık · giyinmek · aceleyle' },
        { key: 's28', en: 'Do they usually get dressed in the same room?', tr: 'Genelde aynı odada mı giyinirler?', cue: 'mi · onlar · genelde · giyinmek · aynı odada' },
        { key: 's29', en: 'What time do you usually get dressed?', tr: 'Genelde saat kaçta giyinirsin?', cue: 'saat kaçta · mi · sen · genelde · giyinmek' },
        { key: 's30', en: 'How long does it usually take you to get dressed?', tr: 'Giyinmen genelde ne kadar sürer?', cue: 'ne kadar · mi · genelde · sürmek · senin için · giyinmek' },
        { key: 's31', en: 'Why does your sister always get dressed so slowly?', tr: 'Kız kardeşin neden hep bu kadar yavaş giyiniyor?', cue: 'neden · mi · kız kardeşin · her zaman · giyinmek · bu kadar yavaş' },
        { key: 's32', en: 'Does your mom usually help you get dressed?', tr: 'Annen genelde giyinmene yardım eder mi?', cue: 'mi · annen · genelde · yardım etmek · sen · giyinmek' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always gets dressed in the bathroom.', tr: 'Ev arkadaşım her zaman banyoda giyinir.', cue: 'ev arkadaşım · her zaman · giyinmek · banyoda' },
        { key: 's34', en: "I don't often get dressed in front of the mirror.", tr: 'Pek sık aynanın önünde giyinmem.', cue: 'ben · değil · sık sık · giyinmek · aynanın önünde' },
        { key: 's35', en: 'Do you always get dressed right after your shower?', tr: 'Duştan hemen sonra her zaman giyinir misin?', alts: ['Do you always get dressed right after the shower?'], cue: 'mi · sen · her zaman · giyinmek · duştan hemen sonra' },
        { key: 's36', en: 'My grandpa hardly ever gets dressed without help.', tr: 'Dedem neredeyse hiç yardımsız giyinmez.', cue: 'dedem · neredeyse hiç · giyinmek · yardımsız' },
        { key: 's37', en: 'My husband occasionally gets dressed in the hallway.', tr: 'Eşim ara sıra koridorda giyinir.', alts: ['My wife occasionally gets dressed in the hallway.'], cue: 'eşim · ara sıra · giyinmek · koridorda' },
        { key: 's38', en: 'Why do you never get dressed on weekends?', tr: 'Neden hafta sonları hiç giyinmezsin?', cue: 'neden · mi · sen · asla · giyinmek · hafta sonları' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I usually get dressed quickly, but I always forget something.', tr: 'Genelde çabuk giyinirim ama her zaman bir şey unuturum.', alts: ['I usually get dressed fast, but I always forget something.'], cue: 'ben · genelde · giyinmek · çabuk · ama · ben · her zaman · unutmak · bir şey' },
        { key: 's40', en: 'My son always gets dressed slowly, so he often misses the bus.', tr: 'Oğlum hep yavaş giyinir, bu yüzden sık sık otobüsü kaçırır.', cue: 'oğlum · her zaman · giyinmek · yavaş · bu yüzden · o · sık sık · kaçırmak · otobüsü' },
        { key: 's41', en: 'She usually gets dressed in the dark because her husband is still asleep.', tr: 'O genelde karanlıkta giyinir çünkü kocası hâlâ uyuyordur.', cue: 'o · genelde · giyinmek · karanlıkta · çünkü · kocası · hâlâ · uyuyor' },
        { key: 's42', en: 'We sometimes get dressed and leave without breakfast.', tr: 'Bazen giyinip kahvaltı yapmadan çıkarız.', alts: ['We sometimes get dressed and leave without eating breakfast.', 'We sometimes get dressed and leave without having breakfast.'], cue: 'biz · bazen · giyinmek · ve · çıkmak · kahvaltısız' },
        { key: 's43', en: 'My sister usually gets dressed in five minutes and does her makeup in the car.', tr: 'Kız kardeşim genelde beş dakikada giyinir ve makyajını arabada yapar.', cue: 'kız kardeşim · genelde · giyinmek · 5 dakikada · ve · makyajını yapmak · arabada' },
        { key: 's44', en: 'Do you usually get dressed right away, or do you have coffee first?', tr: 'Genelde hemen mi giyinirsin, yoksa önce kahve mi içersin?', alts: ['Do you usually get dressed right away, or do you drink coffee first?'], cue: 'mi · sen · genelde · giyinmek · hemen · yoksa · mi · sen · kahve içmek · önce' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: "When it's cold, I usually get dressed under the blanket.", tr: 'Hava soğuk olduğunda genelde battaniyenin altında giyinirim.', alts: ["When it's cold, I usually get dressed under the covers."], cue: '-dığında · hava · soğuk · ben · genelde · giyinmek · battaniyenin altında' },
        { key: 's46', en: 'My mom always gets dressed before the kids wake up.', tr: 'Annem her zaman çocuklar uyanmadan önce giyinir.', cue: 'annem · her zaman · giyinmek · -madan önce · çocuklar · uyanmak' },
        { key: 's47', en: 'Even though he works from home, he always gets dressed for work.', tr: 'Evden çalışmasına rağmen her zaman işe gidiyormuş gibi giyinir.', alts: ['Although he works from home, he always gets dressed for work.'], cue: '-masına rağmen · o · çalışmak · evden · o · her zaman · giyinmek · iş için' },
        { key: 's48', en: 'As soon as I get dressed, I usually make my bed.', tr: 'Giyinir giyinmez genelde yatağımı toplarım.', alts: ['As soon as I get dressed, I usually make the bed.'], cue: '-ar -maz · ben · giyinmek · ben · genelde · yatağımı toplamak' },
        { key: 's49', en: "The kids don't usually get dressed until I turn off the TV.", tr: 'Ben televizyonu kapatana kadar çocuklar genelde giyinmez.', cue: 'çocuklar · değil · genelde · giyinmek · -ana kadar · ben · kapatmak · televizyonu' },
        { key: 's50', en: 'Do you usually get dressed after you check your email?', tr: 'Genelde e-postalarına baktıktan sonra mı giyinirsin?', alts: ['Do you usually get dressed after you check your emails?'], cue: 'mi · sen · genelde · giyinmek · -dıktan sonra · sen · bakmak · e-postalarına' },
      ],
    },
  ],
});
