import { routine } from '../types';

// Rutin 10: ise gitmek.
export const GO_TO_WORK = routine({
  id: 'ps-go-to-work',
  title: 'İşe gitmek',
  icon: 'briefcase-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually go to work by bus.', tr: 'Genelde işe otobüsle giderim.', cue: 'ben · genelde · işe gitmek · otobüsle' },
        { key: 's2', en: 'My dad always goes to work at six.', tr: 'Babam her zaman altıda işe gider.', cue: 'babam · her zaman · işe gitmek · saat 6' },
        { key: 's3', en: 'You often go to work on foot.', tr: 'Sık sık işe yürüyerek gidersin.', alts: ['You often walk to work.'], cue: 'sen · sık sık · işe gitmek · yürüyerek' },
        { key: 's4', en: 'She sometimes goes to work by metro.', tr: 'O bazen işe metroyla gider.', alts: ['She sometimes goes to work on the metro.'], cue: 'o · bazen · işe gitmek · metroyla' },
        { key: 's5', en: 'We rarely go to work by car.', tr: 'Nadiren işe arabayla gideriz.', cue: 'biz · nadiren · işe gitmek · arabayla' },
        { key: 's6', en: 'My sister never goes to work on Fridays.', tr: 'Kız kardeşim cuma günleri asla işe gitmez.', cue: 'kız kardeşim · asla · işe gitmek · cuma günleri' },
        { key: 's7', en: 'They occasionally go to work together.', tr: 'Onlar ara sıra işe birlikte gider.', cue: 'onlar · ara sıra · işe gitmek · birlikte' },
        { key: 's8', en: 'My mom hardly ever goes to work on Saturdays.', tr: 'Annem cumartesi günleri neredeyse hiç işe gitmez.', cue: 'annem · neredeyse hiç · işe gitmek · cumartesi günleri' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often go to work early to avoid traffic.', tr: 'Trafikten kaçmak için sık sık işe erken giderim.', alts: ['I often go to work early to avoid the traffic.'], cue: 'ben · sık sık · işe gitmek · erken · trafikten kaçmak için' },
        { key: 's10', en: 'My brother always goes to work by bike.', tr: 'Erkek kardeşim her zaman işe bisikletle gider.', cue: 'erkek kardeşim · her zaman · işe gitmek · bisikletle' },
        { key: 's11', en: 'He usually goes to work at eight thirty.', tr: 'O genelde sekiz buçukta işe gider.', alts: ['He usually goes to work at half past eight.'], cue: 'o · genelde · işe gitmek · saat 8.30' },
        { key: 's12', en: 'You sometimes go to work with your neighbor.', tr: 'Bazen işe komşunla gidersin.', cue: 'sen · bazen · işe gitmek · komşunla' },
        { key: 's13', en: 'We usually go to work by ferry in the summer.', tr: 'Yazın genelde işe vapurla gideriz.', alts: ['We usually go to work by ferry in summer.'], cue: 'biz · genelde · işe gitmek · vapurla · yazın' },
        { key: 's14', en: 'My coworker rarely goes to work by taxi.', tr: 'İş arkadaşım nadiren işe taksiyle gider.', cue: 'iş arkadaşım · nadiren · işe gitmek · taksiyle' },
        { key: 's15', en: 'I hardly ever go to work on weekends.', tr: 'Hafta sonları neredeyse hiç işe gitmem.', cue: 'ben · neredeyse hiç · işe gitmek · hafta sonları' },
        { key: 's16', en: 'My parents always go to work early.', tr: 'Annemle babam her zaman işe erken gider.', cue: 'annemle babam · her zaman · işe gitmek · erken' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually go to work by car.", tr: 'Genelde işe arabayla gitmem.', cue: 'ben · değil · genelde · işe gitmek · arabayla' },
        { key: 's18', en: "She doesn't usually go to work on Mondays.", tr: 'O pazartesi günleri genelde işe gitmez.', cue: 'o · değil · genelde · işe gitmek · pazartesi günleri' },
        { key: 's19', en: "You don't often go to work this early.", tr: 'Pek sık bu kadar erken işe gitmezsin.', cue: 'sen · değil · sık sık · işe gitmek · bu kadar erken' },
        { key: 's20', en: "My brother doesn't always go to work by bus.", tr: 'Erkek kardeşim her zaman işe otobüsle gitmez.', cue: 'erkek kardeşim · değil · her zaman · işe gitmek · otobüsle' },
        { key: 's21', en: "We don't usually go to work together.", tr: 'Genelde işe birlikte gitmeyiz.', cue: 'biz · değil · genelde · işe gitmek · birlikte' },
        { key: 's22', en: "My coworker doesn't often go to work on foot.", tr: 'İş arkadaşım pek sık işe yürüyerek gitmez.', alts: ["My coworker doesn't often walk to work."], cue: 'iş arkadaşım · değil · sık sık · işe gitmek · yürüyerek' },
        { key: 's23', en: "They don't always go to work on Saturdays.", tr: 'Cumartesi günleri her zaman işe gitmezler.', cue: 'onlar · değil · her zaman · işe gitmek · cumartesi günleri' },
        { key: 's24', en: "He doesn't usually go to work before nine.", tr: 'O genelde dokuzdan önce işe gitmez.', cue: 'o · değil · genelde · işe gitmek · saat 9’dan önce' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually go to work by bus?', tr: 'Genelde işe otobüsle mi gidersin?', cue: 'mi · sen · genelde · işe gitmek · otobüsle' },
        { key: 's26', en: 'Does your sister always go to work by car?', tr: 'Kız kardeşin her zaman işe arabayla mı gider?', cue: 'mi · kız kardeşin · her zaman · işe gitmek · arabayla' },
        { key: 's27', en: 'Do they often go to work together?', tr: 'Onlar sık sık işe birlikte mi gider?', cue: 'mi · onlar · sık sık · işe gitmek · birlikte' },
        { key: 's28', en: 'What time do you usually go to work?', tr: 'Genelde saat kaçta işe gidersin?', cue: 'saat kaçta · mi · sen · genelde · işe gitmek' },
        { key: 's29', en: 'How do you usually go to work?', tr: 'Genelde işe nasıl gidersin?', cue: 'nasıl · mi · sen · genelde · işe gitmek' },
        { key: 's30', en: 'Why does your dad always go to work so early?', tr: 'Baban neden hep işe bu kadar erken gidiyor?', cue: 'neden · mi · baban · her zaman · işe gitmek · bu kadar erken' },
        { key: 's31', en: 'Who do you usually go to work with?', tr: 'Genelde işe kiminle gidersin?', cue: 'kim · mi · sen · genelde · işe gitmek · ile' },
        { key: 's32', en: 'Does your coworker sometimes go to work on foot?', tr: 'İş arkadaşın bazen işe yürüyerek gider mi?', alts: ['Does your coworker sometimes walk to work?'], cue: 'mi · iş arkadaşın · bazen · işe gitmek · yürüyerek' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always goes to work by bike, even in winter.', tr: 'Ev arkadaşım kışın bile her zaman işe bisikletle gider.', alts: ['My roommate always goes to work by bike, even in the winter.'], cue: 'ev arkadaşım · her zaman · işe gitmek · bisikletle · kışın bile' },
        { key: 's34', en: "I don't often go to work by taxi.", tr: 'Pek sık işe taksiyle gitmem.', cue: 'ben · değil · sık sık · işe gitmek · taksiyle' },
        { key: 's35', en: 'Does your mom usually go to work on Saturdays?', tr: 'Annen cumartesi günleri genelde işe gider mi?', cue: 'mi · annen · genelde · işe gitmek · cumartesi günleri' },
        { key: 's36', en: 'My boss never goes to work before ten.', tr: 'Patronum asla ondan önce işe gitmez.', cue: 'patronum · asla · işe gitmek · saat 10’dan önce' },
        { key: 's37', en: 'My sister and I occasionally go to work together.', tr: 'Kız kardeşimle ara sıra işe birlikte gideriz.', cue: 'kız kardeşim ve ben · ara sıra · işe gitmek · birlikte' },
        { key: 's38', en: "Why don't you usually go to work by metro?", tr: 'Neden genelde işe metroyla gitmiyorsun?', alts: ["Why don't you usually go to work on the metro?"], cue: 'neden · mi · sen · değil · genelde · işe gitmek · metroyla' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I usually go to work by bus, but I sometimes take the metro.', tr: 'Genelde işe otobüsle giderim ama bazen metroya binerim.', cue: 'ben · genelde · işe gitmek · otobüsle · ama · ben · bazen · metroya binmek' },
        { key: 's40', en: 'My dad always goes to work early, so he never gets stuck in traffic.', tr: 'Babam her zaman işe erken gider, bu yüzden asla trafiğe takılmaz.', cue: 'babam · her zaman · işe gitmek · erken · bu yüzden · o · asla · trafiğe takılmak' },
        { key: 's41', en: 'She usually goes to work on foot because she lives nearby.', tr: 'O genelde işe yürüyerek gider çünkü yakında oturur.', alts: ['She usually walks to work because she lives nearby.', 'She usually goes to work on foot because she lives close by.'], cue: 'o · genelde · işe gitmek · yürüyerek · çünkü · o · oturmak · yakında' },
        { key: 's42', en: 'We often go to work together and have breakfast on the way.', tr: 'Sık sık birlikte işe gider ve yolda kahvaltı yaparız.', cue: 'biz · sık sık · işe gitmek · birlikte · ve · kahvaltı yapmak · yolda' },
        { key: 's43', en: 'My coworker rarely goes to work by car because parking is expensive.', tr: 'İş arkadaşım nadiren işe arabayla gider çünkü otopark pahalı.', cue: 'iş arkadaşım · nadiren · işe gitmek · arabayla · çünkü · otopark · pahalı' },
        { key: 's44', en: 'Do you usually go to work by car, or do you take the bus?', tr: 'Genelde işe arabayla mı gidersin, yoksa otobüse mi binersin?', cue: 'mi · sen · genelde · işe gitmek · arabayla · yoksa · mi · sen · otobüse binmek' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'After I take the kids to school, I usually go to work by metro.', tr: 'Çocukları okula götürdükten sonra genelde işe metroyla giderim.', alts: ['After I take the kids to school, I usually go to work on the metro.'], cue: '-dıktan sonra · ben · götürmek · çocuklar · okula · ben · genelde · işe gitmek · metroyla' },
        { key: 's46', en: 'My mom always checks the traffic before she goes to work.', tr: 'Annem işe gitmeden önce her zaman trafiğe bakar.', cue: 'annem · her zaman · trafiğe bakmak · -madan önce · o · işe gitmek' },
        { key: 's47', en: 'Although my brother has a car, he usually goes to work by bus.', tr: 'Erkek kardeşimin arabası olmasına rağmen genelde işe otobüsle gider.', alts: ['Even though my brother has a car, he usually goes to work by bus.'], cue: '-masına rağmen · erkek kardeşim · sahip olmak · araba · o · genelde · işe gitmek · otobüsle' },
        { key: 's48', en: 'As soon as I finish breakfast, I usually go to work.', tr: 'Kahvaltıyı bitirir bitirmez genelde işe giderim.', alts: ['As soon as I finish my breakfast, I usually go to work.'], cue: '-ar -maz · ben · bitirmek · kahvaltı · ben · genelde · işe gitmek' },
        { key: 's49', en: "My sister doesn't usually go to work until the kids go to school.", tr: 'Kız kardeşim çocuklar okula gidene kadar genelde işe gitmez.', cue: 'kız kardeşim · değil · genelde · işe gitmek · -ana kadar · çocuklar · okula gitmek' },
        { key: 's50', en: 'Do you usually go to work by car when the weather is bad?', tr: 'Hava kötü olduğunda genelde işe arabayla mı gidersin?', cue: 'mi · sen · genelde · işe gitmek · arabayla · -dığında · hava · kötü olmak' },
      ],
    },
  ],
});
