import { routine } from '../types';

// Rutin 8: spora gitmek. Kurallar: docs/SPEAKING_RULES.md.
export const GYM = routine({
  id: 'ps-gym',
  title: 'Spora gitmek',
  icon: 'barbell-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually go to the gym before work.', tr: 'Genelde işten önce spora giderim.', cue: 'ben · genelde · spora gitmek · işten önce' },
        { key: 's2', en: 'My brother always goes to the gym on Mondays.', tr: 'Erkek kardeşim pazartesileri her zaman spora gider.', cue: 'erkek kardeşim · her zaman · spora gitmek · pazartesileri' },
        { key: 's3', en: 'You often go to the gym with a friend.', tr: 'Sık sık bir arkadaşınla spora gidersin.', cue: 'sen · sık sık · spora gitmek · bir arkadaşla' },
        { key: 's4', en: 'She sometimes goes to the gym after work.', tr: 'O bazen işten sonra spora gider.', cue: 'o · bazen · spora gitmek · işten sonra' },
        { key: 's5', en: 'We occasionally go to the gym together.', tr: 'Ara sıra birlikte spora gideriz.', cue: 'biz · ara sıra · spora gitmek · birlikte' },
        { key: 's6', en: 'My roommate rarely goes to the gym in winter.', tr: 'Ev arkadaşım kışın nadiren spora gider.', alts: ['My roommate rarely goes to the gym in the winter.'], cue: 'ev arkadaşım · nadiren · spora gitmek · kışın' },
        { key: 's7', en: 'They never go to the gym on Sundays.', tr: 'Onlar pazar günleri asla spora gitmez.', cue: 'onlar · asla · spora gitmek · pazar günleri' },
        { key: 's8', en: 'He usually goes to the gym at six in the morning.', tr: 'O genelde sabah altıda spora gider.', cue: 'o · genelde · spora gitmek · saat 6 · sabah' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I usually go to the gym three times a week.', tr: 'Genelde haftada üç kez spora giderim.', cue: 'ben · genelde · spora gitmek · haftada 3 kez' },
        { key: 's10', en: 'My sister always goes to the gym with her best friend.', tr: 'Kız kardeşim her zaman en yakın arkadaşıyla spora gider.', cue: 'kız kardeşim · her zaman · spora gitmek · en yakın arkadaşıyla' },
        { key: 's11', en: 'He often goes to the gym during his lunch break.', tr: 'O sık sık öğle arasında spora gider.', alts: ['He often goes to the gym on his lunch break.'], cue: 'o · sık sık · spora gitmek · öğle arasında' },
        { key: 's12', en: 'You sometimes go to the gym late at night.', tr: 'Bazen gece geç saatte spora gidersin.', cue: 'sen · bazen · spora gitmek · gece geç saatte' },
        { key: 's13', en: 'My coworker hardly ever goes to the gym on Fridays.', tr: 'İş arkadaşım cuma günleri neredeyse hiç spora gitmez.', cue: 'iş arkadaşım · neredeyse hiç · spora gitmek · cuma günleri' },
        { key: 's14', en: 'We always go to the gym before work on Mondays.', tr: 'Pazartesileri her zaman işten önce spora gideriz.', cue: 'biz · her zaman · spora gitmek · işten önce · pazartesileri' },
        { key: 's15', en: 'I occasionally go to the gym on weekends.', tr: 'Ara sıra hafta sonları spora giderim.', alts: ['I occasionally go to the gym on the weekend.'], cue: 'ben · ara sıra · spora gitmek · hafta sonları' },
        { key: 's16', en: 'My parents rarely go to the gym.', tr: 'Annemle babam nadiren spora gider.', cue: 'annemle babam · nadiren · spora gitmek' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually go to the gym after work.", tr: 'Genelde işten sonra spora gitmem.', cue: 'ben · değil · genelde · spora gitmek · işten sonra' },
        { key: 's18', en: "My brother doesn't always go to the gym with me.", tr: 'Erkek kardeşim her zaman benimle spora gitmez.', cue: 'erkek kardeşim · değil · her zaman · spora gitmek · benimle' },
        { key: 's19', en: "You don't often go to the gym in the evening.", tr: 'Akşamları pek sık spora gitmezsin.', alts: ["You don't often go to the gym in the evenings."], cue: 'sen · değil · sık sık · spora gitmek · akşamları' },
        { key: 's20', en: "She doesn't usually go to the gym alone.", tr: 'O genelde spora yalnız gitmez.', cue: 'o · değil · genelde · spora gitmek · yalnız' },
        { key: 's21', en: "We don't always go to the gym on Saturdays.", tr: 'Cumartesileri her zaman spora gitmeyiz.', cue: 'biz · değil · her zaman · spora gitmek · cumartesileri' },
        { key: 's22', en: "My roommate doesn't often go to the gym in the morning.", tr: 'Ev arkadaşım sabahları pek sık spora gitmez.', alts: ["My roommate doesn't often go to the gym in the mornings."], cue: 'ev arkadaşım · değil · sık sık · spora gitmek · sabahları' },
        { key: 's23', en: "They don't usually go to the gym in summer.", tr: 'Yazın genelde spora gitmezler.', alts: ["They don't usually go to the gym in the summer."], cue: 'onlar · değil · genelde · spora gitmek · yazın' },
        { key: 's24', en: "He doesn't always go to the gym three times a week.", tr: 'O her zaman haftada üç kez spora gitmez.', cue: 'o · değil · her zaman · spora gitmek · haftada 3 kez' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually go to the gym before work?', tr: 'Genelde işten önce mi spora gidersin?', cue: 'mi · sen · genelde · spora gitmek · işten önce' },
        { key: 's26', en: 'Does your sister often go to the gym?', tr: 'Kız kardeşin sık sık spora gider mi?', cue: 'mi · kız kardeşin · sık sık · spora gitmek' },
        { key: 's27', en: 'Does he always go to the gym with a friend?', tr: 'O her zaman bir arkadaşıyla mı spora gider?', cue: 'mi · o · her zaman · spora gitmek · bir arkadaşla' },
        { key: 's28', en: 'What time do you usually go to the gym?', tr: 'Genelde saat kaçta spora gidersin?', cue: 'saat kaçta · mi · sen · genelde · spora gitmek' },
        { key: 's29', en: 'How often do you usually go to the gym?', tr: 'Genelde ne sıklıkla spora gidersin?', cue: 'ne sıklıkla · mi · sen · genelde · spora gitmek' },
        { key: 's30', en: 'Why does your roommate never go to the gym?', tr: 'Ev arkadaşın neden hiç spora gitmiyor?', cue: 'neden · mi · ev arkadaşın · asla · spora gitmek' },
        { key: 's31', en: 'Who do you usually go to the gym with?', tr: 'Genelde kiminle spora gidersin?', cue: 'kiminle · mi · sen · genelde · spora gitmek' },
        { key: 's32', en: 'Which gym does your coworker usually go to?', tr: 'İş arkadaşın genelde hangi spor salonuna gider?', cue: 'hangi spor salonu · mi · iş arkadaşın · genelde · gitmek' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My dad always goes to the gym before breakfast.', tr: 'Babam her zaman kahvaltıdan önce spora gider.', cue: 'babam · her zaman · spora gitmek · kahvaltıdan önce' },
        { key: 's34', en: "My friends don't usually go to the gym during exams.", tr: 'Arkadaşlarım sınav döneminde genelde spora gitmez.', cue: 'arkadaşlarım · değil · genelde · spora gitmek · sınav döneminde' },
        { key: 's35', en: 'Do your kids sometimes go to the gym with you?', tr: 'Çocukların bazen seninle spora gider mi?', cue: 'mi · çocukların · bazen · spora gitmek · seninle' },
        { key: 's36', en: 'My uncle occasionally goes to the gym after dinner.', tr: 'Amcam ara sıra akşam yemeğinden sonra spora gider.', cue: 'amcam · ara sıra · spora gitmek · akşam yemeğinden sonra' },
        { key: 's37', en: 'I rarely go to the gym without my headphones.', tr: 'Kulaklığım olmadan nadiren spora giderim.', cue: 'ben · nadiren · spora gitmek · kulaklığım olmadan' },
        { key: 's38', en: 'Why do you always go to the gym so early?', tr: 'Neden hep bu kadar erken spora gidiyorsun?', cue: 'neden · mi · sen · her zaman · spora gitmek · bu kadar erken' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'My brother often goes to the gym, but he never stretches.', tr: 'Erkek kardeşim sık sık spora gider ama asla esneme yapmaz.', cue: 'erkek kardeşim · sık sık · spora gitmek · ama · o · asla · esneme yapmak' },
        { key: 's40', en: 'She always goes to the gym before work, so she gets up at five.', tr: 'O her zaman işten önce spora gider, bu yüzden beşte kalkar.', cue: 'o · her zaman · spora gitmek · işten önce · bu yüzden · o · kalkmak · saat 5' },
        { key: 's41', en: 'I usually go to the gym with a friend because I hate working out alone.', tr: 'Genelde bir arkadaşımla spora giderim çünkü yalnız spor yapmaktan nefret ederim.', cue: 'ben · genelde · spora gitmek · bir arkadaşla · çünkü · ben · nefret etmek · spor yapmak · yalnız' },
        { key: 's42', en: 'We sometimes go to the gym and then have breakfast together.', tr: 'Bazen spora gidip sonra birlikte kahvaltı yaparız.', cue: 'biz · bazen · spora gitmek · ve · sonra · kahvaltı yapmak · birlikte' },
        { key: 's43', en: 'They occasionally go to the gym and play basketball.', tr: 'Onlar ara sıra spora gidip basketbol oynar.', cue: 'onlar · ara sıra · spora gitmek · ve · basketbol oynamak' },
        { key: 's44', en: 'Do you usually go to the gym in the morning or in the evening?', tr: 'Genelde sabah mı spora gidersin, yoksa akşam mı?', cue: 'mi · sen · genelde · spora gitmek · sabah · yoksa · akşam' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When I go to the gym with a friend, I always stay longer.', tr: 'Bir arkadaşımla spora gittiğimde her zaman daha uzun kalırım.', cue: '-dığında · ben · spora gitmek · bir arkadaşla · ben · her zaman · kalmak · daha uzun' },
        { key: 's46', en: 'My sister always eats a banana before she goes to the gym.', tr: 'Kız kardeşim spora gitmeden önce her zaman bir muz yer.', alts: ['My sister always eats a banana before going to the gym.'], cue: 'kız kardeşim · her zaman · muz yemek · -madan önce · o · spora gitmek' },
        { key: 's47', en: "Even though he's tired after work, he usually goes to the gym.", tr: 'İşten sonra yorgun olmasına rağmen genelde spora gider.', alts: ["Although he's tired after work, he usually goes to the gym."], cue: '-masına rağmen · o · yorgun olmak · işten sonra · o · genelde · spora gitmek' },
        { key: 's48', en: 'As soon as I finish work, I often go to the gym.', tr: 'İşi bitirir bitirmez sık sık spora giderim.', cue: '-ar -maz · ben · işi bitirmek · ben · sık sık · spora gitmek' },
        { key: 's49', en: "My coworker doesn't usually go to the gym until his shift ends.", tr: 'İş arkadaşım genelde vardiyası bitene kadar spora gitmez.', cue: 'iş arkadaşım · değil · genelde · spora gitmek · -ana kadar · vardiyası · bitmek' },
        { key: 's50', en: 'Do you usually go to the gym after you have breakfast?', tr: 'Kahvaltı yaptıktan sonra genelde spora gider misin?', cue: 'mi · sen · genelde · spora gitmek · -dıktan sonra · sen · kahvaltı yapmak' },
      ],
    },
  ],
});
