import { routine } from '../types';

// Rutin 5: instagramda gezinmek. Kurallar: docs/SPEAKING_RULES.md.
export const INSTAGRAM = routine({
  id: 'ps-instagram',
  title: "Instagram'da gezinmek",
  icon: 'phone-portrait-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually scroll through Instagram in bed.', tr: "Genelde yatakta Instagram'da gezinirim.", cue: "ben · genelde · Instagram'da gezinmek · yatakta" },
        { key: 's2', en: 'My sister always scrolls through Instagram at breakfast.', tr: "Kız kardeşim her zaman kahvaltıda Instagram'da gezinir.", cue: "kız kardeşim · her zaman · Instagram'da gezinmek · kahvaltıda" },
        { key: 's3', en: 'You often scroll through Instagram for an hour.', tr: "Sık sık bir saat boyunca Instagram'da gezinirsin.", cue: "sen · sık sık · Instagram'da gezinmek · bir saat boyunca" },
        { key: 's4', en: 'He sometimes scrolls through Instagram on the bus.', tr: "O bazen otobüste Instagram'da gezinir.", cue: "o · bazen · Instagram'da gezinmek · otobüste" },
        { key: 's5', en: 'We rarely scroll through Instagram in the morning.', tr: "Sabahları nadiren Instagram'da geziniriz.", alts: ['We rarely scroll through Instagram in the mornings.'], cue: "biz · nadiren · Instagram'da gezinmek · sabahları" },
        { key: 's6', en: 'My dad never scrolls through Instagram at work.', tr: "Babam işte asla Instagram'da gezinmez.", cue: "babam · asla · Instagram'da gezinmek · işte" },
        { key: 's7', en: 'They occasionally scroll through Instagram together.', tr: "Onlar ara sıra birlikte Instagram'da gezinir.", cue: "onlar · ara sıra · Instagram'da gezinmek · birlikte" },
        { key: 's8', en: 'My roommate hardly ever scrolls through Instagram at night.', tr: "Ev arkadaşım gece neredeyse hiç Instagram'da gezinmez.", cue: "ev arkadaşım · neredeyse hiç · Instagram'da gezinmek · gece" },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often scroll through Instagram before getting up.', tr: "Sık sık kalkmadan önce Instagram'da gezinirim.", alts: ['I often scroll through Instagram before I get up.'], cue: "ben · sık sık · Instagram'da gezinmek · kalkmadan önce" },
        { key: 's10', en: 'My mom usually scrolls through Instagram after dinner.', tr: "Annem genelde akşam yemeğinden sonra Instagram'da gezinir.", cue: "annem · genelde · Instagram'da gezinmek · akşam yemeğinden sonra" },
        { key: 's11', en: 'She always scrolls through Instagram on her lunch break.', tr: "O öğle arasında her zaman Instagram'da gezinir.", cue: "o · her zaman · Instagram'da gezinmek · öğle arasında" },
        { key: 's12', en: 'You sometimes scroll through Instagram in class.', tr: "Bazen derste Instagram'da gezinirsin.", cue: "sen · bazen · Instagram'da gezinmek · derste" },
        { key: 's13', en: 'We usually scroll through Instagram on the couch.', tr: "Genelde kanepede Instagram'da geziniriz.", alts: ['We usually scroll through Instagram on the sofa.'], cue: "biz · genelde · Instagram'da gezinmek · kanepede" },
        { key: 's14', en: 'My grandma occasionally scrolls through Instagram on her tablet.', tr: "Büyükannem ara sıra tabletinde Instagram'da gezinir.", cue: "büyükannem · ara sıra · Instagram'da gezinmek · tabletinde" },
        { key: 's15', en: 'I rarely scroll through Instagram on weekends.', tr: "Hafta sonları nadiren Instagram'da gezinirim.", alts: ['I rarely scroll through Instagram on the weekend.'], cue: "ben · nadiren · Instagram'da gezinmek · hafta sonları" },
        { key: 's16', en: 'My brother hardly ever scrolls through Instagram before school.', tr: "Erkek kardeşim okuldan önce neredeyse hiç Instagram'da gezinmez.", cue: "erkek kardeşim · neredeyse hiç · Instagram'da gezinmek · okuldan önce" },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually scroll through Instagram for long.", tr: "Genelde uzun süre Instagram'da gezinmem.", cue: "ben · değil · genelde · Instagram'da gezinmek · uzun süre" },
        { key: 's18', en: "He doesn't often scroll through Instagram on his laptop.", tr: "O dizüstü bilgisayarında pek sık Instagram'da gezinmez.", cue: "o · değil · sık sık · Instagram'da gezinmek · dizüstü bilgisayarında" },
        { key: 's19', en: "You don't usually scroll through Instagram at the table.", tr: "Genelde sofrada Instagram'da gezinmezsin.", cue: "sen · değil · genelde · Instagram'da gezinmek · sofrada" },
        { key: 's20', en: "She doesn't always scroll through Instagram before bed.", tr: "O yatmadan önce her zaman Instagram'da gezinmez.", alts: ["She doesn't always scroll through Instagram before going to bed."], cue: "o · değil · her zaman · Instagram'da gezinmek · yatmadan önce" },
        { key: 's21', en: "We don't often scroll through Instagram at the gym.", tr: "Spor salonunda pek sık Instagram'da gezinmeyiz.", cue: "biz · değil · sık sık · Instagram'da gezinmek · spor salonunda" },
        { key: 's22', en: "My mom doesn't usually scroll through Instagram in the evening.", tr: "Annem akşamları genelde Instagram'da gezinmez.", alts: ["My mom doesn't usually scroll through Instagram in the evenings."], cue: "annem · değil · genelde · Instagram'da gezinmek · akşamları" },
        { key: 's23', en: "They don't usually scroll through Instagram during dinner.", tr: "Akşam yemeğinde genelde Instagram'da gezinmezler.", alts: ["They don't usually scroll through Instagram at dinner."], cue: "onlar · değil · genelde · Instagram'da gezinmek · akşam yemeği sırasında" },
        { key: 's24', en: "My sister doesn't often scroll through Instagram on the train.", tr: "Kız kardeşim trende pek sık Instagram'da gezinmez.", cue: "kız kardeşim · değil · sık sık · Instagram'da gezinmek · trende" },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually scroll through Instagram in bed?', tr: "Genelde yatakta Instagram'da gezinir misin?", cue: "mi · sen · genelde · Instagram'da gezinmek · yatakta" },
        { key: 's26', en: 'Does your sister always scroll through Instagram at breakfast?', tr: "Kız kardeşin her zaman kahvaltıda Instagram'da gezinir mi?", cue: "mi · kız kardeşin · her zaman · Instagram'da gezinmek · kahvaltıda" },
        { key: 's27', en: 'Does he often scroll through Instagram at work?', tr: "O sık sık işte Instagram'da gezinir mi?", cue: "mi · o · sık sık · Instagram'da gezinmek · işte" },
        { key: 's28', en: 'Do they sometimes scroll through Instagram in class?', tr: "Onlar bazen derste Instagram'da gezinir mi?", cue: "mi · onlar · bazen · Instagram'da gezinmek · derste" },
        { key: 's29', en: 'What time do you usually scroll through Instagram?', tr: "Genelde saat kaçta Instagram'da gezinirsin?", cue: "saat kaçta · mi · sen · genelde · Instagram'da gezinmek" },
        { key: 's30', en: 'How long do you usually scroll through Instagram?', tr: "Genelde ne kadar süre Instagram'da gezinirsin?", alts: ['How long do you usually scroll through Instagram for?'], cue: "ne kadar süre · mi · sen · genelde · Instagram'da gezinmek" },
        { key: 's31', en: 'Why do you always scroll through Instagram before getting up?', tr: "Neden hep kalkmadan önce Instagram'da geziniyorsun?", alts: ['Why do you always scroll through Instagram before you get up?'], cue: "neden · mi · sen · her zaman · Instagram'da gezinmek · kalkmadan önce" },
        { key: 's32', en: 'Does your roommate usually scroll through Instagram at night?', tr: "Ev arkadaşın genelde gece Instagram'da gezinir mi?", cue: "mi · ev arkadaşın · genelde · Instagram'da gezinmek · gece" },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My best friend always scrolls through Instagram on the way to work.', tr: "En yakın arkadaşım işe giderken her zaman Instagram'da gezinir.", alts: ['My best friend always scrolls through Instagram on his way to work.', 'My best friend always scrolls through Instagram on her way to work.'], cue: "en yakın arkadaşım · her zaman · Instagram'da gezinmek · işe giderken" },
        { key: 's34', en: "I don't usually scroll through Instagram at breakfast.", tr: "Kahvaltıda genelde Instagram'da gezinmem.", cue: "ben · değil · genelde · Instagram'da gezinmek · kahvaltıda" },
        { key: 's35', en: 'Does your grandpa sometimes scroll through Instagram?', tr: "Deden bazen Instagram'da gezinir mi?", cue: "mi · deden · bazen · Instagram'da gezinmek" },
        { key: 's36', en: 'My cousin never scrolls through Instagram after midnight.', tr: "Kuzenim gece yarısından sonra asla Instagram'da gezinmez.", cue: "kuzenim · asla · Instagram'da gezinmek · gece yarısından sonra" },
        { key: 's37', en: 'Our kids rarely scroll through Instagram on weekdays.', tr: "Çocuklarımız hafta içi nadiren Instagram'da gezinir.", cue: "çocuklarımız · nadiren · Instagram'da gezinmek · hafta içi" },
        { key: 's38', en: 'Why does your brother always scroll through Instagram at dinner?', tr: "Erkek kardeşin neden hep akşam yemeğinde Instagram'da geziniyor?", alts: ['Why does your brother always scroll through Instagram during dinner?'], cue: "neden · mi · erkek kardeşin · her zaman · Instagram'da gezinmek · akşam yemeğinde" },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I usually scroll through Instagram in bed, so I often get up late.', tr: "Genelde yatakta Instagram'da gezinirim, bu yüzden sık sık geç kalkarım.", cue: "ben · genelde · Instagram'da gezinmek · yatakta · bu yüzden · ben · sık sık · kalkmak · geç" },
        { key: 's40', en: 'My sister always scrolls through Instagram, but she never posts anything.', tr: "Kız kardeşim hep Instagram'da gezinir ama hiçbir şey paylaşmaz.", cue: "kız kardeşim · her zaman · Instagram'da gezinmek · ama · o · asla · paylaşmak · hiçbir şey" },
        { key: 's41', en: 'He often scrolls through Instagram because he gets bored at work.', tr: "O sık sık Instagram'da gezinir çünkü işte canı sıkılır.", cue: "o · sık sık · Instagram'da gezinmek · çünkü · o · canı sıkılmak · işte" },
        { key: 's42', en: 'We sometimes scroll through Instagram and laugh at funny videos.', tr: "Bazen Instagram'da gezinip komik videolara güleriz.", cue: "biz · bazen · Instagram'da gezinmek · ve · gülmek · komik videolara" },
        { key: 's43', en: 'My mom usually scrolls through Instagram and sends me recipes.', tr: "Annem genelde Instagram'da gezinir ve bana tarif gönderir.", cue: "annem · genelde · Instagram'da gezinmek · ve · göndermek · bana · tarifler" },
        { key: 's44', en: 'Do you usually scroll through Instagram in bed, or do you get up right away?', tr: "Genelde yatakta Instagram'da mı gezinirsin, yoksa hemen mi kalkarsın?", cue: "mi · sen · genelde · Instagram'da gezinmek · yatakta · yoksa · mi · sen · kalkmak · hemen" },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar · -dıktan sonra',
      bank: 'onError',
      sentences: [
        { key: 's45', en: "When I can't sleep, I usually scroll through Instagram for an hour.", tr: "Uyuyamadığımda genelde bir saat Instagram'da gezinirim.", cue: "-dığında · ben · değil · uyuyabilmek · ben · genelde · Instagram'da gezinmek · bir saat boyunca" },
        { key: 's46', en: 'I always scroll through Instagram before I get out of bed.', tr: "Yataktan kalkmadan önce her zaman Instagram'da gezinirim.", alts: ['I always scroll through Instagram before getting out of bed.'], cue: "ben · her zaman · Instagram'da gezinmek · -madan önce · ben · yataktan kalkmak" },
        { key: 's47', en: "Even though he knows it's a waste of time, he often scrolls through Instagram.", tr: "Zaman kaybı olduğunu bilmesine rağmen sık sık Instagram'da gezinir.", alts: ["Although he knows it's a waste of time, he often scrolls through Instagram.", "Even though he knows that it's a waste of time, he often scrolls through Instagram."], cue: "-masına rağmen · o · bilmek · zaman kaybı · o · sık sık · Instagram'da gezinmek" },
        { key: 's48', en: 'As soon as my roommate wakes up, she usually scrolls through Instagram.', tr: "Ev arkadaşım uyanır uyanmaz genelde Instagram'da gezinir.", cue: "-ar -maz · ev arkadaşım · uyanmak · o · genelde · Instagram'da gezinmek" },
        { key: 's49', en: "We don't usually scroll through Instagram until the kids go to bed.", tr: "Çocuklar yatana kadar genelde Instagram'da gezinmeyiz.", cue: "biz · değil · genelde · Instagram'da gezinmek · -ana kadar · çocuklar · yatmak" },
        { key: 's50', en: 'Do you usually scroll through Instagram after you get into bed?', tr: "Yatağa girdikten sonra genelde Instagram'da gezinir misin?", alts: ['Do you usually scroll through Instagram after getting into bed?'], cue: "mi · sen · genelde · Instagram'da gezinmek · -dıktan sonra · sen · yatağa girmek" },
      ],
    },
  ],
});
