import { routine } from '../types';

// Rutin 4: dus almak. Kurallar: docs/SPEAKING_RULES.md.
export const SHOWER = routine({
  id: 'ps-shower',
  title: 'Duş almak',
  icon: 'water-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually take a shower in the morning.', tr: 'Sabahları genelde duş alırım.', alts: ['I usually take a shower in the mornings.'], cue: 'ben · genelde · duş almak · sabahları' },
        { key: 's2', en: 'My dad always takes a cold shower.', tr: 'Babam her zaman soğuk duş alır.', cue: 'babam · her zaman · soğuk duş almak' },
        { key: 's3', en: 'You often take a shower before work.', tr: 'İşten önce sık sık duş alırsın.', cue: 'sen · sık sık · duş almak · işten önce' },
        { key: 's4', en: 'She sometimes takes a shower at night.', tr: 'O bazen gece duş alır.', cue: 'o · bazen · duş almak · gece' },
        { key: 's5', en: 'We rarely take a hot shower in the summer.', tr: 'Yazın nadiren sıcak duş alırız.', alts: ['We rarely take a hot shower in summer.'], cue: 'biz · nadiren · sıcak duş almak · yazın' },
        { key: 's6', en: 'My brother never takes a long shower.', tr: 'Erkek kardeşim asla uzun duş almaz.', cue: 'erkek kardeşim · asla · uzun duş almak' },
        { key: 's7', en: 'They occasionally take a shower at the gym.', tr: 'Onlar ara sıra spor salonunda duş alır.', cue: 'onlar · ara sıra · duş almak · spor salonunda' },
        { key: 's8', en: 'My mom usually takes a quick shower before breakfast.', tr: 'Annem genelde kahvaltıdan önce hızlı bir duş alır.', cue: 'annem · genelde · hızlı duş almak · kahvaltıdan önce' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I always take a shower before bed.', tr: 'Yatmadan önce her zaman duş alırım.', alts: ['I always take a shower before going to bed.'], cue: 'ben · her zaman · duş almak · yatmadan önce' },
        { key: 's10', en: 'My sister often takes a long shower in the morning.', tr: 'Kız kardeşim sabahları sık sık uzun duş alır.', alts: ['My sister often takes a long shower in the mornings.'], cue: 'kız kardeşim · sık sık · uzun duş almak · sabahları' },
        { key: 's11', en: 'He usually takes a shower at seven.', tr: 'O genelde yedide duş alır.', cue: 'o · genelde · duş almak · saat 7' },
        { key: 's12', en: 'You sometimes take a cold shower after a run.', tr: 'Koşudan sonra bazen soğuk duş alırsın.', alts: ['You sometimes take a cold shower after running.'], cue: 'sen · bazen · soğuk duş almak · koşudan sonra' },
        { key: 's13', en: 'We usually take a shower after the gym.', tr: 'Spordan sonra genelde duş alırız.', cue: 'biz · genelde · duş almak · spor salonundan sonra' },
        { key: 's14', en: 'My roommate hardly ever takes a quick shower.', tr: 'Ev arkadaşım neredeyse hiç hızlı duş almaz.', cue: 'ev arkadaşım · neredeyse hiç · hızlı duş almak' },
        { key: 's15', en: 'I rarely take a hot shower.', tr: 'Nadiren sıcak duş alırım.', cue: 'ben · nadiren · sıcak duş almak' },
        { key: 's16', en: 'The kids usually take a shower in the evening.', tr: 'Çocuklar genelde akşamları duş alır.', alts: ['The kids usually take a shower in the evenings.'], cue: 'çocuklar · genelde · duş almak · akşamları' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually take a shower in the evening.", tr: 'Genelde akşamları duş almam.', alts: ["I don't usually take a shower in the evenings."], cue: 'ben · değil · genelde · duş almak · akşamları' },
        { key: 's18', en: "My dad doesn't always take a shower before work.", tr: 'Babam her zaman işten önce duş almaz.', cue: 'babam · değil · her zaman · duş almak · işten önce' },
        { key: 's19', en: "You don't often take a hot shower.", tr: 'Pek sık sıcak duş almazsın.', cue: 'sen · değil · sık sık · sıcak duş almak' },
        { key: 's20', en: "She doesn't usually take a long shower.", tr: 'O genelde uzun duş almaz.', cue: 'o · değil · genelde · uzun duş almak' },
        { key: 's21', en: "We don't always take a shower after the gym.", tr: 'Spordan sonra her zaman duş almayız.', cue: 'biz · değil · her zaman · duş almak · spor salonundan sonra' },
        { key: 's22', en: "My roommate doesn't usually take a shower in the morning.", tr: 'Ev arkadaşım genelde sabahları duş almaz.', alts: ["My roommate doesn't usually take a shower in the mornings."], cue: 'ev arkadaşım · değil · genelde · duş almak · sabahları' },
        { key: 's23', en: "They don't often take a cold shower in the winter.", tr: 'Kışın pek sık soğuk duş almazlar.', alts: ["They don't often take a cold shower in winter."], cue: 'onlar · değil · sık sık · soğuk duş almak · kışın' },
        { key: 's24', en: "He doesn't usually take a shower at the gym.", tr: 'O genelde spor salonunda duş almaz.', cue: 'o · değil · genelde · duş almak · spor salonunda' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually take a shower in the morning?', tr: 'Genelde sabahları mı duş alırsın?', alts: ['Do you usually take a shower in the mornings?'], cue: 'mi · sen · genelde · duş almak · sabahları' },
        { key: 's26', en: 'Does your dad always take a cold shower?', tr: 'Baban her zaman soğuk duş mu alır?', cue: 'mi · baban · her zaman · soğuk duş almak' },
        { key: 's27', en: 'Does she often take a shower at night?', tr: 'O sık sık gece duş alır mı?', cue: 'mi · o · sık sık · duş almak · gece' },
        { key: 's28', en: 'Do they usually take a shower after the gym?', tr: 'Spordan sonra genelde duş alırlar mı?', cue: 'mi · onlar · genelde · duş almak · spor salonundan sonra' },
        { key: 's29', en: 'What time do you usually take a shower?', tr: 'Genelde saat kaçta duş alırsın?', cue: 'saat kaçta · mi · sen · genelde · duş almak' },
        { key: 's30', en: 'How often does your brother take a shower?', tr: 'Erkek kardeşin ne sıklıkla duş alır?', cue: 'ne sıklıkla · mi · erkek kardeşin · duş almak' },
        { key: 's31', en: 'Why do you always take a cold shower?', tr: 'Neden hep soğuk duş alıyorsun?', cue: 'neden · mi · sen · her zaman · soğuk duş almak' },
        { key: 's32', en: 'When do the kids usually take a shower?', tr: 'Çocuklar genelde ne zaman duş alır?', cue: 'ne zaman · mi · çocuklar · genelde · duş almak' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My grandpa always takes a shower before breakfast.', tr: 'Dedem her zaman kahvaltıdan önce duş alır.', cue: 'dedem · her zaman · duş almak · kahvaltıdan önce' },
        { key: 's34', en: "I don't often take a shower before bed.", tr: 'Yatmadan önce pek sık duş almam.', alts: ["I don't often take a shower before going to bed."], cue: 'ben · değil · sık sık · duş almak · yatmadan önce' },
        { key: 's35', en: 'Do you sometimes take a shower twice a day?', tr: 'Bazen günde iki kez duş alır mısın?', cue: 'mi · sen · bazen · duş almak · günde 2 kez' },
        { key: 's36', en: 'My mom never takes a cold shower.', tr: 'Annem asla soğuk duş almaz.', cue: 'annem · asla · soğuk duş almak' },
        { key: 's37', en: 'My uncle occasionally takes a shower in the afternoon.', tr: 'Amcam ara sıra öğleden sonra duş alır.', cue: 'amcam · ara sıra · duş almak · öğleden sonra' },
        { key: 's38', en: 'Why does he rarely take a shower in the morning?', tr: 'O neden sabahları nadiren duş alıyor?', alts: ['Why does he rarely take a shower in the mornings?'], cue: 'neden · mi · o · nadiren · duş almak · sabahları' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: "I usually take a shower at night, but I don't wash my hair.", tr: 'Genelde gece duş alırım ama saçımı yıkamam.', cue: 'ben · genelde · duş almak · gece · ama · ben · değil · saçımı yıkamak' },
        { key: 's40', en: 'My brother always takes a long shower, so he often misses the bus.', tr: 'Erkek kardeşim hep uzun duş alır, bu yüzden sık sık otobüsü kaçırır.', cue: 'erkek kardeşim · her zaman · uzun duş almak · bu yüzden · o · sık sık · otobüsü kaçırmak' },
        { key: 's41', en: 'I always take a cold shower because it wakes me up.', tr: 'Her zaman soğuk duş alırım çünkü beni uyandırır.', cue: 'ben · her zaman · soğuk duş almak · çünkü · bu · uyandırmak · beni' },
        { key: 's42', en: 'She often takes a quick shower and goes straight to work.', tr: 'O sık sık hızlı bir duş alıp doğrudan işe gider.', cue: 'o · sık sık · hızlı duş almak · ve · doğrudan işe gitmek' },
        { key: 's43', en: 'My mom usually takes a shower first and then wakes the kids up.', tr: 'Annem genelde önce duş alır, sonra çocukları uyandırır.', alts: ['My mom usually takes a shower first and then wakes up the kids.'], cue: 'annem · genelde · duş almak · önce · ve sonra · çocukları uyandırmak' },
        { key: 's44', en: 'Do you usually take a shower in the morning or at night?', tr: 'Genelde sabah mı duş alırsın, yoksa gece mi?', cue: 'mi · sen · genelde · duş almak · sabahları · yoksa · gece' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When I get home from the gym, I always take a shower.', tr: 'Spordan eve geldiğimde her zaman duş alırım.', alts: ['When I come home from the gym, I always take a shower.'], cue: '-dığında · ben · eve gelmek · spor salonundan · ben · her zaman · duş almak' },
        { key: 's46', en: 'My dad usually takes a shower before he goes to work.', tr: 'Babam genelde işe gitmeden önce duş alır.', cue: 'babam · genelde · duş almak · -madan önce · o · işe gitmek' },
        { key: 's47', en: "Even though I'm tired, I always take a shower before bed.", tr: 'Yorgun olmama rağmen yatmadan önce her zaman duş alırım.', alts: ["Although I'm tired, I always take a shower before bed."], cue: '-masına rağmen · ben · yorgun olmak · ben · her zaman · duş almak · yatmadan önce' },
        { key: 's48', en: 'As soon as I get back from a run, I usually take a cold shower.', tr: 'Koşudan döner dönmez genelde soğuk duş alırım.', cue: '-ar -maz · ben · dönmek · koşudan · ben · genelde · soğuk duş almak' },
        { key: 's49', en: "My son doesn't usually take a shower until I tell him twice.", tr: 'Oğlum ben iki kez söyleyene kadar genelde duş almaz.', cue: 'oğlum · değil · genelde · duş almak · -ana kadar · ben · söylemek · ona · 2 kez' },
        { key: 's50', en: 'Do you usually take a shower after you get home from work?', tr: 'İşten eve geldikten sonra genelde duş alır mısın?', alts: ['Do you usually take a shower after you come home from work?'], cue: 'mi · sen · genelde · duş almak · -dıktan sonra · sen · eve gelmek · işten' },
      ],
    },
  ],
});
