import { routine } from '../types';

// Rutin 1: uyanmak. Kurallar: docs/SPEAKING_RULES.md.
export const WAKE_UP = routine({
  id: 'ps-wake-up',
  title: 'Uyanmak',
  icon: 'alarm-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually wake up at seven.', tr: 'Genelde yedide uyanırım.', cue: 'ben · genelde · uyanmak · saat 7' },
        { key: 's2', en: 'My dad always wakes up before everyone else.', tr: 'Babam her zaman herkesten önce uyanır.', cue: 'babam · her zaman · uyanmak · herkesten önce' },
        { key: 's3', en: 'You often wake up late on Sundays.', tr: 'Pazar günleri sık sık geç uyanırsın.', cue: 'sen · sık sık · uyanmak · geç · pazar günleri' },
        { key: 's4', en: 'She sometimes wakes up in the middle of the night.', tr: 'O bazen gece yarısı uyanır.', cue: 'o · bazen · uyanmak · gece yarısı' },
        { key: 's5', en: 'We rarely wake up before eight on weekends.', tr: 'Hafta sonları nadiren sekizden önce uyanırız.', cue: 'biz · nadiren · uyanmak · saat 8’den önce · hafta sonları' },
        { key: 's6', en: 'My brother never wakes up on his own.', tr: 'Erkek kardeşim asla kendi kendine uyanmaz.', cue: 'erkek kardeşim · asla · uyanmak · kendi kendine' },
        { key: 's7', en: 'They occasionally wake up at noon.', tr: 'Onlar ara sıra öğlen uyanır.', cue: 'onlar · ara sıra · uyanmak · öğlen' },
        { key: 's8', en: 'My mom usually wakes me up at seven thirty.', tr: 'Annem genelde beni yedi buçukta uyandırır.', alts: ['My mom usually wakes me up at half past seven.'], cue: 'annem · genelde · uyandırmak · beni · saat 7.30' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often wake up before my alarm.', tr: 'Sık sık alarmım çalmadan önce uyanırım.', cue: 'ben · sık sık · uyanmak · alarmımdan önce' },
        { key: 's10', en: 'My sister always wakes up in a good mood.', tr: 'Kız kardeşim her zaman keyifli uyanır.', cue: 'kız kardeşim · her zaman · uyanmak · keyifli' },
        { key: 's11', en: 'He usually wakes up at six on weekdays.', tr: 'O hafta içi genelde altıda uyanır.', cue: 'o · genelde · uyanmak · saat 6 · hafta içi' },
        { key: 's12', en: 'You sometimes wake up with a headache.', tr: 'Bazen baş ağrısıyla uyanırsın.', cue: 'sen · bazen · uyanmak · baş ağrısıyla' },
        { key: 's13', en: 'We usually wake up early in the summer.', tr: 'Yazın genelde erken uyanırız.', alts: ['We usually wake up early in summer.'], cue: 'biz · genelde · uyanmak · erken · yazın' },
        { key: 's14', en: 'My dad hardly ever wakes up late.', tr: 'Babam neredeyse hiç geç uyanmaz.', cue: 'babam · neredeyse hiç · uyanmak · geç' },
        { key: 's15', en: 'I rarely wake up hungry.', tr: 'Nadiren aç uyanırım.', cue: 'ben · nadiren · uyanmak · aç' },
        { key: 's16', en: 'The kids always wake up before us.', tr: 'Çocuklar her zaman bizden önce uyanır.', cue: 'çocuklar · her zaman · uyanmak · bizden önce' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually wake up before seven.", tr: 'Genelde yediden önce uyanmam.', cue: 'ben · değil · genelde · uyanmak · saat 7’den önce' },
        { key: 's18', en: "My brother doesn't always wake up on time.", tr: 'Erkek kardeşim her zaman zamanında uyanmaz.', cue: 'erkek kardeşim · değil · her zaman · uyanmak · zamanında' },
        { key: 's19', en: "You don't often wake up this early.", tr: 'Pek sık bu kadar erken uyanmazsın.', cue: 'sen · değil · sık sık · uyanmak · bu kadar erken' },
        { key: 's20', en: "She doesn't usually wake up at night.", tr: 'O genelde gece uyanmaz.', cue: 'o · değil · genelde · uyanmak · gece' },
        { key: 's21', en: "We don't always wake up at the same time.", tr: 'Her zaman aynı saatte uyanmayız.', cue: 'biz · değil · her zaman · uyanmak · aynı saatte' },
        { key: 's22', en: "My mom doesn't usually wake up late on weekdays.", tr: 'Annem hafta içi genelde geç uyanmaz.', cue: 'annem · değil · genelde · uyanmak · geç · hafta içi' },
        { key: 's23', en: "They don't usually wake up before noon on Sundays.", tr: 'Pazar günleri genelde öğlenden önce uyanmazlar.', cue: 'onlar · değil · genelde · uyanmak · öğlenden önce · pazar günleri' },
        { key: 's24', en: "He doesn't often wake up in a bad mood.", tr: 'O pek sık huysuz uyanmaz.', cue: 'o · değil · sık sık · uyanmak · huysuz' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually wake up early?', tr: 'Genelde erken uyanır mısın?', cue: 'mi · sen · genelde · uyanmak · erken' },
        { key: 's26', en: 'Does your dad always wake up at six?', tr: 'Baban her zaman altıda mı uyanır?', cue: 'mi · baban · her zaman · uyanmak · saat 6' },
        { key: 's27', en: 'Does she often wake up at night?', tr: 'O sık sık gece uyanır mı?', cue: 'mi · o · sık sık · uyanmak · gece' },
        { key: 's28', en: 'Do they usually wake up late on weekends?', tr: 'Hafta sonları genelde geç mi uyanırlar?', cue: 'mi · onlar · genelde · uyanmak · geç · hafta sonları' },
        { key: 's29', en: 'What time do you usually wake up?', tr: 'Genelde saat kaçta uyanırsın?', cue: 'saat kaçta · mi · sen · genelde · uyanmak' },
        { key: 's30', en: 'How often do you wake up before your alarm?', tr: 'Ne sıklıkla alarmın çalmadan önce uyanırsın?', cue: 'ne sıklıkla · mi · sen · uyanmak · alarmından önce' },
        { key: 's31', en: 'Why does your brother always wake up so late?', tr: 'Erkek kardeşin neden hep bu kadar geç uyanıyor?', cue: 'neden · mi · erkek kardeşin · her zaman · uyanmak · bu kadar geç' },
        { key: 's32', en: 'Does your mom usually wake you up in the morning?', tr: 'Annen sabahları genelde seni uyandırır mı?', cue: 'mi · annen · genelde · uyandırmak · seni · sabahları' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always wakes up before sunrise.', tr: 'Ev arkadaşım her zaman gün doğmadan uyanır.', cue: 'ev arkadaşım · her zaman · uyanmak · gün doğmadan' },
        { key: 's34', en: "I don't usually wake up tired.", tr: 'Genelde yorgun uyanmam.', cue: 'ben · değil · genelde · uyanmak · yorgun' },
        { key: 's35', en: 'Do you often wake up before your kids?', tr: 'Çocuklarından önce sık sık uyanır mısın?', cue: 'mi · sen · sık sık · uyanmak · çocuklarından önce' },
        { key: 's36', en: 'My grandma never wakes up after six.', tr: 'Büyükannem asla altıdan sonra uyanmaz.', cue: 'büyükannem · asla · uyanmak · saat 6’dan sonra' },
        { key: 's37', en: "The neighbor's dog often wakes us up.", tr: 'Komşunun köpeği bizi sık sık uyandırır.', alts: ["Our neighbor's dog often wakes us up."], cue: 'komşunun köpeği · sık sık · uyandırmak · bizi' },
        { key: 's38', en: 'How often does your baby wake up at night?', tr: 'Bebeğin gece ne sıklıkla uyanır?', cue: 'ne sıklıkla · mi · bebeğin · uyanmak · gece' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: "I usually wake up at seven, but I don't get up until eight.", tr: 'Genelde yedide uyanırım ama sekize kadar kalkmam.', cue: 'ben · genelde · uyanmak · saat 7 · ama · ben · değil · kalkmak · 8’e kadar' },
        { key: 's40', en: 'My brother always wakes up late, so he never has breakfast.', tr: 'Erkek kardeşim hep geç uyanır, bu yüzden hiç kahvaltı yapmaz.', cue: 'erkek kardeşim · her zaman · uyanmak · geç · bu yüzden · o · asla · kahvaltı yapmak' },
        { key: 's41', en: 'She usually wakes up early because she starts work at eight.', tr: 'O genelde erken uyanır çünkü işe sekizde başlar.', cue: 'o · genelde · uyanmak · erken · çünkü · o · işe başlamak · saat 8' },
        { key: 's42', en: 'We sometimes wake up early and go for a walk.', tr: 'Bazen erken uyanıp yürüyüşe çıkarız.', cue: 'biz · bazen · uyanmak · erken · ve · yürüyüşe çıkmak' },
        { key: 's43', en: 'My dad always wakes up first and makes tea for everyone.', tr: 'Babam her zaman ilk uyanır ve herkese çay yapar.', cue: 'babam · her zaman · uyanmak · ilk · ve · çay yapmak · herkese' },
        { key: 's44', en: 'Do you usually wake up early, or do you sleep in?', tr: 'Genelde erken mi uyanırsın, yoksa geç saate kadar mı uyursun?', cue: 'mi · sen · genelde · uyanmak · erken · yoksa · mi · sen · geç saate kadar uyumak' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When I wake up early, I usually feel better all day.', tr: 'Erken uyandığımda genelde gün boyu daha iyi hissederim.', cue: '-dığında · ben · uyanmak · erken · ben · genelde · hissetmek · daha iyi · gün boyu' },
        { key: 's46', en: 'My mom always wakes up before the sun comes up.', tr: 'Annem her zaman güneş doğmadan önce uyanır.', cue: 'annem · her zaman · uyanmak · -madan önce · güneş · doğmak' },
        { key: 's47', en: 'Even though he goes to bed late, he always wakes up at six.', tr: 'Geç yatmasına rağmen her zaman altıda uyanır.', alts: ['Although he goes to bed late, he always wakes up at six.'], cue: '-masına rağmen · o · yatmak · geç · o · her zaman · uyanmak · saat 6' },
        { key: 's48', en: 'As soon as I wake up, I usually check my phone.', tr: 'Uyanır uyanmaz genelde telefonuma bakarım.', cue: '-ar -maz · ben · uyanmak · ben · genelde · telefona bakmak' },
        { key: 's49', en: "My sister doesn't usually wake up until her alarm goes off twice.", tr: 'Kız kardeşim genelde alarmı iki kez çalana kadar uyanmaz.', cue: 'kız kardeşim · değil · genelde · uyanmak · -ana kadar · alarmı · çalmak · 2 kez' },
        { key: 's50', en: 'Do you usually wake up tired when you go to bed after midnight?', tr: 'Gece yarısından sonra yattığında genelde yorgun mu uyanırsın?', cue: 'mi · sen · genelde · uyanmak · yorgun · -dığında · sen · yatmak · gece yarısından sonra' },
      ],
    },
  ],
});
