import { routine } from '../types';

// Rutin 7: yuruyuse cikmak. Kurallar: docs/SPEAKING_RULES.md.
export const WALK = routine({
  id: 'ps-walk',
  title: 'Yürüyüşe çıkmak',
  icon: 'walk-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually go for a walk after dinner.', tr: 'Akşam yemeğinden sonra genelde yürüyüşe çıkarım.', cue: 'ben · genelde · yürüyüşe çıkmak · akşam yemeğinden sonra' },
        { key: 's2', en: 'My grandpa always goes for a walk in the morning.', tr: 'Dedem her zaman sabahları yürüyüşe çıkar.', alts: ['My grandpa always goes for a walk in the mornings.'], cue: 'dedem · her zaman · yürüyüşe çıkmak · sabahları' },
        { key: 's3', en: 'You often go for a walk in the park.', tr: 'Sık sık parkta yürüyüşe çıkarsın.', cue: 'sen · sık sık · yürüyüşe çıkmak · parkta' },
        { key: 's4', en: 'She sometimes goes for a walk by the sea.', tr: 'O bazen deniz kenarında yürüyüşe çıkar.', cue: 'o · bazen · yürüyüşe çıkmak · deniz kenarında' },
        { key: 's5', en: 'We occasionally go for a walk on Sunday mornings.', tr: 'Pazar sabahları ara sıra yürüyüşe çıkarız.', cue: 'biz · ara sıra · yürüyüşe çıkmak · pazar sabahları' },
        { key: 's6', en: 'My dad always goes for a walk with the dog.', tr: 'Babam her zaman köpekle yürüyüşe çıkar.', alts: ['My dad always goes for a walk with our dog.'], cue: 'babam · her zaman · yürüyüşe çıkmak · köpekle' },
        { key: 's7', en: 'They rarely go for a walk in the evening.', tr: 'Onlar akşamları nadiren yürüyüşe çıkar.', alts: ['They rarely go for a walk in the evenings.'], cue: 'onlar · nadiren · yürüyüşe çıkmak · akşamları' },
        { key: 's8', en: 'He never goes for a walk alone.', tr: 'O asla tek başına yürüyüşe çıkmaz.', cue: 'o · asla · yürüyüşe çıkmak · tek başına' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I often go for a walk at lunchtime.', tr: 'Öğle arasında sık sık yürüyüşe çıkarım.', cue: 'ben · sık sık · yürüyüşe çıkmak · öğle arasında' },
        { key: 's10', en: 'My mom usually goes for a walk for half an hour.', tr: 'Annem genelde yarım saat yürüyüşe çıkar.', cue: 'annem · genelde · yürüyüşe çıkmak · yarım saat' },
        { key: 's11', en: 'He always goes for a walk at six.', tr: 'O her zaman saat altıda yürüyüşe çıkar.', cue: 'o · her zaman · yürüyüşe çıkmak · saat 6' },
        { key: 's12', en: 'You sometimes go for a walk in the rain.', tr: 'Bazen yağmurda yürüyüşe çıkarsın.', cue: 'sen · bazen · yürüyüşe çıkmak · yağmurda' },
        { key: 's13', en: 'We usually go for a walk after lunch on weekends.', tr: 'Hafta sonları öğle yemeğinden sonra genelde yürüyüşe çıkarız.', cue: 'biz · genelde · yürüyüşe çıkmak · öğle yemeğinden sonra · hafta sonları' },
        { key: 's14', en: 'My grandma hardly ever goes for a walk in winter.', tr: 'Büyükannem kışın neredeyse hiç yürüyüşe çıkmaz.', alts: ['My grandma hardly ever goes for a walk in the winter.'], cue: 'büyükannem · neredeyse hiç · yürüyüşe çıkmak · kışın' },
        { key: 's15', en: 'My friends rarely go for a walk on weekdays.', tr: 'Arkadaşlarım hafta içi nadiren yürüyüşe çıkar.', cue: 'arkadaşlarım · nadiren · yürüyüşe çıkmak · hafta içi' },
        { key: 's16', en: 'She occasionally goes for a walk with her sister.', tr: 'O ara sıra kız kardeşiyle yürüyüşe çıkar.', cue: 'o · ara sıra · yürüyüşe çıkmak · kız kardeşiyle' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually go for a walk in the morning.", tr: 'Sabahları genelde yürüyüşe çıkmam.', alts: ["I don't usually go for a walk in the mornings."], cue: 'ben · değil · genelde · yürüyüşe çıkmak · sabahları' },
        { key: 's18', en: "My dad doesn't always go for a walk after dinner.", tr: 'Babam akşam yemeğinden sonra her zaman yürüyüşe çıkmaz.', cue: 'babam · değil · her zaman · yürüyüşe çıkmak · akşam yemeğinden sonra' },
        { key: 's19', en: "You don't often go for a walk alone.", tr: 'Pek sık tek başına yürüyüşe çıkmazsın.', cue: 'sen · değil · sık sık · yürüyüşe çıkmak · tek başına' },
        { key: 's20', en: "She doesn't usually go for a walk in the evening.", tr: 'O akşamları genelde yürüyüşe çıkmaz.', alts: ["She doesn't usually go for a walk in the evenings."], cue: 'o · değil · genelde · yürüyüşe çıkmak · akşamları' },
        { key: 's21', en: "We don't always go for a walk together.", tr: 'Her zaman birlikte yürüyüşe çıkmayız.', cue: 'biz · değil · her zaman · yürüyüşe çıkmak · birlikte' },
        { key: 's22', en: "My aunt doesn't usually go for a walk without her dog.", tr: 'Teyzem genelde köpeği olmadan yürüyüşe çıkmaz.', cue: 'teyzem · değil · genelde · yürüyüşe çıkmak · köpeği olmadan' },
        { key: 's23', en: "They don't usually go for a walk on rainy days.", tr: 'Yağmurlu günlerde genelde yürüyüşe çıkmazlar.', cue: 'onlar · değil · genelde · yürüyüşe çıkmak · yağmurlu günlerde' },
        { key: 's24', en: "He doesn't often go for a walk after work.", tr: 'O iş çıkışı pek sık yürüyüşe çıkmaz.', cue: 'o · değil · sık sık · yürüyüşe çıkmak · işten sonra' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you often go for a walk in the park?', tr: 'Sık sık parkta yürüyüşe çıkar mısın?', cue: 'mi · sen · sık sık · yürüyüşe çıkmak · parkta' },
        { key: 's26', en: 'Does your grandpa always go for a walk in the morning?', tr: 'Deden her zaman sabahları yürüyüşe çıkar mı?', alts: ['Does your grandpa always go for a walk in the mornings?'], cue: 'mi · deden · her zaman · yürüyüşe çıkmak · sabahları' },
        { key: 's27', en: 'Does she usually go for a walk with the dog?', tr: 'O genelde köpekle yürüyüşe çıkar mı?', cue: 'mi · o · genelde · yürüyüşe çıkmak · köpekle' },
        { key: 's28', en: 'Do they sometimes go for a walk by the sea?', tr: 'Onlar bazen deniz kenarında yürüyüşe çıkar mı?', cue: 'mi · onlar · bazen · yürüyüşe çıkmak · deniz kenarında' },
        { key: 's29', en: 'What time do you usually go for a walk?', tr: 'Genelde saat kaçta yürüyüşe çıkarsın?', cue: 'saat kaçta · mi · sen · genelde · yürüyüşe çıkmak' },
        { key: 's30', en: 'How often does your mom go for a walk?', tr: 'Annen ne sıklıkla yürüyüşe çıkar?', cue: 'ne sıklıkla · mi · annen · yürüyüşe çıkmak' },
        { key: 's31', en: 'Why does your brother never go for a walk?', tr: 'Erkek kardeşin neden hiç yürüyüşe çıkmaz?', cue: 'neden · mi · erkek kardeşin · asla · yürüyüşe çıkmak' },
        { key: 's32', en: 'Who do you usually go for a walk with?', tr: 'Genelde kiminle yürüyüşe çıkarsın?', cue: 'kiminle · mi · sen · genelde · yürüyüşe çıkmak' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My roommate always goes for a walk before breakfast.', tr: 'Ev arkadaşım her zaman kahvaltıdan önce yürüyüşe çıkar.', cue: 'ev arkadaşım · her zaman · yürüyüşe çıkmak · kahvaltıdan önce' },
        { key: 's34', en: "I don't usually go for a walk on hot days.", tr: 'Sıcak günlerde genelde yürüyüşe çıkmam.', cue: 'ben · değil · genelde · yürüyüşe çıkmak · sıcak günlerde' },
        { key: 's35', en: 'Where do you usually go for a walk?', tr: 'Genelde nereye yürüyüşe çıkarsın?', cue: 'nereye · mi · sen · genelde · yürüyüşe çıkmak' },
        { key: 's36', en: 'My uncle hardly ever goes for a walk.', tr: 'Amcam neredeyse hiç yürüyüşe çıkmaz.', cue: 'amcam · neredeyse hiç · yürüyüşe çıkmak' },
        { key: 's37', en: 'Does your sister often go for a walk after work?', tr: 'Kız kardeşin iş çıkışı sık sık yürüyüşe çıkar mı?', cue: 'mi · kız kardeşin · sık sık · yürüyüşe çıkmak · işten sonra' },
        { key: 's38', en: 'Our neighbors sometimes go for a walk late at night.', tr: 'Komşularımız bazen gece geç saatte yürüyüşe çıkar.', cue: 'komşularımız · bazen · yürüyüşe çıkmak · gece geç saatte' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I often go for a walk at night because it helps me sleep.', tr: 'Geceleri sık sık yürüyüşe çıkarım çünkü uyumama yardımcı oluyor.', cue: 'ben · sık sık · yürüyüşe çıkmak · geceleri · çünkü · bu · yardımcı olmak · bana · uyumak' },
        { key: 's40', en: 'My mom always goes for a walk in the park and feeds the ducks.', tr: 'Annem her zaman parkta yürüyüşe çıkar ve ördekleri besler.', cue: 'annem · her zaman · yürüyüşe çıkmak · parkta · ve · ördekleri beslemek' },
        { key: 's41', en: 'I sometimes go for a walk with my dad, but he always walks too fast.', tr: 'Bazen babamla yürüyüşe çıkarım ama o hep fazla hızlı yürür.', cue: 'ben · bazen · yürüyüşe çıkmak · babamla · ama · o · her zaman · yürümek · fazla hızlı' },
        { key: 's42', en: 'They live near the sea, so they often go for a walk on the beach.', tr: 'Denize yakın oturuyorlar, bu yüzden sık sık sahilde yürüyüşe çıkarlar.', cue: 'onlar · yaşamak · denize yakın · bu yüzden · onlar · sık sık · yürüyüşe çıkmak · sahilde' },
        { key: 's43', en: 'Do you usually go for a walk alone, or do you take the dog?', tr: 'Genelde tek başına mı yürüyüşe çıkarsın, yoksa köpeği de götürür müsün?', cue: 'mi · sen · genelde · yürüyüşe çıkmak · tek başına · yoksa · mi · sen · köpeği götürmek' },
        { key: 's44', en: 'She hardly ever goes for a walk because she works long hours.', tr: 'O uzun saatler çalıştığı için neredeyse hiç yürüyüşe çıkmaz.', cue: 'o · neredeyse hiç · yürüyüşe çıkmak · çünkü · o · çalışmak · uzun saatler' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -dıktan sonra · -ar -maz · -ana kadar · -masına rağmen',
      bank: 'onError',
      sentences: [
        { key: 's45', en: 'When the weather is nice, we always go for a walk by the sea.', tr: 'Hava güzel olduğunda her zaman deniz kenarında yürüyüşe çıkarız.', cue: '-dığında · hava · güzel olmak · biz · her zaman · yürüyüşe çıkmak · deniz kenarında' },
        { key: 's46', en: 'I usually go for a walk before I start work.', tr: 'Genelde işe başlamadan önce yürüyüşe çıkarım.', cue: 'ben · genelde · yürüyüşe çıkmak · -madan önce · ben · işe başlamak' },
        { key: 's47', en: 'My dad often goes for a walk after he has lunch.', tr: 'Babam öğle yemeğini yedikten sonra sık sık yürüyüşe çıkar.', alts: ['My dad often goes for a walk after he eats lunch.'], cue: 'babam · sık sık · yürüyüşe çıkmak · -dıktan sonra · o · öğle yemeği yemek' },
        { key: 's48', en: 'As soon as I get home from work, I usually go for a walk.', tr: 'İşten eve gelir gelmez genelde yürüyüşe çıkarım.', cue: '-ar -maz · ben · eve gelmek · işten · ben · genelde · yürüyüşe çıkmak' },
        { key: 's49', en: "My kids don't usually go for a walk until I promise them ice cream.", tr: 'Çocuklarım ben dondurma sözü verene kadar genelde yürüyüşe çıkmaz.', cue: 'çocuklarım · değil · genelde · yürüyüşe çıkmak · -ana kadar · ben · söz vermek · onlara · dondurma' },
        { key: 's50', en: 'Does your mom always go for a walk even though her knee hurts?', tr: 'Annen dizi ağrımasına rağmen her zaman yürüyüşe çıkar mı?', alts: ['Does your mom always go for a walk although her knee hurts?'], cue: 'mi · annen · her zaman · yürüyüşe çıkmak · -masına rağmen · onun dizi · ağrımak' },
      ],
    },
  ],
});
