import { routine } from '../types';

// Rutin 9: evden calismak.
export const WORK_FROM_HOME = routine({
  id: 'ps-work-from-home',
  title: 'Evden çalışmak',
  icon: 'laptop-outline',
  levels: [
    {
      id: 'l1',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri açık.',
      bank: 'show',
      sentences: [
        { key: 's1', en: 'I usually work from home on Mondays.', tr: 'Pazartesileri genelde evden çalışırım.', cue: 'ben · genelde · evden çalışmak · pazartesileri' },
        { key: 's2', en: 'My wife always works from home on Fridays.', tr: 'Eşim cuma günleri her zaman evden çalışır.', cue: 'eşim · her zaman · evden çalışmak · cuma günleri' },
        { key: 's3', en: 'You often work from home in the winter.', tr: 'Kışın sık sık evden çalışırsın.', alts: ['You often work from home in winter.'], cue: 'sen · sık sık · evden çalışmak · kışın' },
        { key: 's4', en: 'She sometimes works from the kitchen table.', tr: 'O bazen mutfak masasında çalışır.', alts: ['She sometimes works at the kitchen table.'], cue: 'o · bazen · çalışmak · mutfak masasında' },
        { key: 's5', en: 'We occasionally work from home all week.', tr: 'Ara sıra bütün hafta evden çalışırız.', alts: ['We occasionally work from home the whole week.'], cue: 'biz · ara sıra · evden çalışmak · bütün hafta' },
        { key: 's6', en: 'My boss rarely works from home.', tr: 'Patronum nadiren evden çalışır.', cue: 'patronum · nadiren · evden çalışmak' },
        { key: 's7', en: 'My coworkers never work from home.', tr: 'İş arkadaşlarım asla evden çalışmaz.', cue: 'iş arkadaşlarım · asla · evden çalışmak' },
        { key: 's8', en: 'He hardly ever works from home in the summer.', tr: 'O yazın neredeyse hiç evden çalışmaz.', alts: ['He hardly ever works from home in summer.'], cue: 'o · neredeyse hiç · evden çalışmak · yazın' },
      ],
    },
    {
      id: 'l2',
      title: 'Olumlu',
      note: 'Sıklık kelimeleri gizli, hata yapınca açılır.',
      bank: 'onError',
      sentences: [
        { key: 's9', en: 'I always work from home on rainy days.', tr: 'Yağmurlu günlerde her zaman evden çalışırım.', cue: 'ben · her zaman · evden çalışmak · yağmurlu günlerde' },
        { key: 's10', en: 'My sister usually works from home three days a week.', tr: 'Kız kardeşim genelde haftada üç gün evden çalışır.', cue: 'kız kardeşim · genelde · evden çalışmak · haftada 3 gün' },
        { key: 's11', en: 'He often works from home in the afternoon.', tr: 'O öğleden sonraları sık sık evden çalışır.', alts: ['He often works from home in the afternoons.'], cue: 'o · sık sık · evden çalışmak · öğleden sonra' },
        { key: 's12', en: 'You sometimes work from home in your pajamas.', tr: 'Bazen pijamalarınla evden çalışırsın.', cue: 'sen · bazen · evden çalışmak · pijamalarınla' },
        { key: 's13', en: 'We always work from home during the holidays.', tr: 'Tatillerde her zaman evden çalışırız.', alts: ['We always work from home over the holidays.'], cue: 'biz · her zaman · evden çalışmak · tatillerde' },
        { key: 's14', en: 'My dad occasionally works from home on Wednesdays.', tr: 'Babam çarşamba günleri ara sıra evden çalışır.', cue: 'babam · ara sıra · evden çalışmak · çarşamba günleri' },
        { key: 's15', en: 'I hardly ever work from the couch.', tr: 'Neredeyse hiç kanepede çalışmam.', alts: ['I hardly ever work on the couch.'], cue: 'ben · neredeyse hiç · çalışmak · kanepede' },
        { key: 's16', en: 'Our team never works from home on Tuesdays.', tr: 'Ekibimiz salı günleri asla evden çalışmaz.', cue: 'ekibimiz · asla · evden çalışmak · salı günleri' },
      ],
    },
    {
      id: 'l3',
      title: 'Olumsuz',
      bank: 'onError',
      sentences: [
        { key: 's17', en: "I don't usually work from home on Fridays.", tr: 'Cuma günleri genelde evden çalışmam.', cue: 'ben · değil · genelde · evden çalışmak · cuma günleri' },
        { key: 's18', en: "My boss doesn't often work from home.", tr: 'Patronum pek sık evden çalışmaz.', cue: 'patronum · değil · sık sık · evden çalışmak' },
        { key: 's19', en: "You don't always work from home on Wednesdays.", tr: 'Çarşamba günleri her zaman evden çalışmazsın.', cue: 'sen · değil · her zaman · evden çalışmak · çarşamba günleri' },
        { key: 's20', en: "She doesn't usually work from bed.", tr: 'O genelde yatakta çalışmaz.', alts: ["She doesn't usually work in bed."], cue: 'o · değil · genelde · çalışmak · yatakta' },
        { key: 's21', en: "We don't often work from home in the summer.", tr: 'Yazın pek sık evden çalışmayız.', alts: ["We don't often work from home in summer."], cue: 'biz · değil · sık sık · evden çalışmak · yazın' },
        { key: 's22', en: "My husband doesn't usually work from home on Mondays.", tr: 'Kocam pazartesileri genelde evden çalışmaz.', cue: 'kocam · değil · genelde · evden çalışmak · pazartesileri' },
        { key: 's23', en: "They don't usually work from home more than two days a week.", tr: 'Genelde haftada iki günden fazla evden çalışmazlar.', cue: 'onlar · değil · genelde · evden çalışmak · haftada 2 günden fazla' },
        { key: 's24', en: "He doesn't always work from home on rainy days.", tr: 'O yağmurlu günlerde her zaman evden çalışmaz.', cue: 'o · değil · her zaman · evden çalışmak · yağmurlu günlerde' },
      ],
    },
    {
      id: 'l4',
      title: 'Soru',
      bank: 'onError',
      sentences: [
        { key: 's25', en: 'Do you usually work from home on Mondays?', tr: 'Pazartesileri genelde evden mi çalışırsın?', cue: 'mi · sen · genelde · evden çalışmak · pazartesileri' },
        { key: 's26', en: 'Does your boss often work from home?', tr: 'Patronun sık sık evden çalışır mı?', cue: 'mi · patronun · sık sık · evden çalışmak' },
        { key: 's27', en: 'Do they sometimes work from home on Fridays?', tr: 'Onlar cuma günleri bazen evden çalışır mı?', cue: 'mi · onlar · bazen · evden çalışmak · cuma günleri' },
        { key: 's28', en: 'How many days a week do you usually work from home?', tr: 'Haftada genelde kaç gün evden çalışırsın?', cue: 'haftada kaç gün · mi · sen · genelde · evden çalışmak' },
        { key: 's29', en: 'How often does your wife work from home?', tr: 'Eşin ne sıklıkla evden çalışır?', cue: 'ne sıklıkla · mi · eşin · evden çalışmak' },
        { key: 's30', en: 'Why do you always work from home on Fridays?', tr: 'Neden cuma günleri hep evden çalışıyorsun?', cue: 'neden · mi · sen · her zaman · evden çalışmak · cuma günleri' },
        { key: 's31', en: 'Where do you usually sit when you work from home?', tr: 'Evden çalıştığında genelde nerede oturursun?', cue: 'nerede · mi · sen · genelde · oturmak · -dığında · sen · evden çalışmak' },
        { key: 's32', en: 'What time do you usually start work when you work from home?', tr: 'Evden çalıştığında genelde saat kaçta işe başlarsın?', cue: 'saat kaçta · mi · sen · genelde · işe başlamak · -dığında · sen · evden çalışmak' },
      ],
    },
    {
      id: 'l5',
      title: 'Karışık',
      bank: 'onError',
      sentences: [
        { key: 's33', en: 'My brother usually works from home with the TV on.', tr: 'Erkek kardeşim genelde televizyon açıkken evden çalışır.', cue: 'erkek kardeşim · genelde · evden çalışmak · televizyon açıkken' },
        { key: 's34', en: 'I rarely work from home these days.', tr: 'Bu aralar nadiren evden çalışırım.', cue: 'ben · nadiren · evden çalışmak · bu aralar' },
        { key: 's35', en: "My coworkers don't usually work from home on Mondays.", tr: 'İş arkadaşlarım pazartesileri genelde evden çalışmaz.', cue: 'iş arkadaşlarım · değil · genelde · evden çalışmak · pazartesileri' },
        { key: 's36', en: 'Why does your husband hardly ever work from home?', tr: 'Kocan neden neredeyse hiç evden çalışmıyor?', cue: 'neden · mi · kocan · neredeyse hiç · evden çalışmak' },
        { key: 's37', en: 'Does your team usually work from home on Fridays?', tr: 'Ekibin cuma günleri genelde evden mi çalışır?', cue: 'mi · ekibin · genelde · evden çalışmak · cuma günleri' },
        { key: 's38', en: 'My neighbor never works from home.', tr: 'Komşum asla evden çalışmaz.', cue: 'komşum · asla · evden çalışmak' },
      ],
    },
    {
      id: 'l6',
      title: 'Bağlaçlarla',
      note: 've · ama · çünkü · bu yüzden · yoksa',
      bank: 'onError',
      sentences: [
        { key: 's39', en: 'I usually work from home on Mondays, but I go to the office on Tuesdays.', tr: 'Pazartesileri genelde evden çalışırım ama salı günleri ofise giderim.', cue: 'ben · genelde · evden çalışmak · pazartesileri · ama · ben · ofise gitmek · salı günleri' },
        { key: 's40', en: 'My wife often works from home, so she walks the dog at lunch.', tr: 'Eşim sık sık evden çalışır, bu yüzden öğlen köpeği gezdirir.', alts: ['My wife often works from home, so she walks the dog at lunchtime.'], cue: 'eşim · sık sık · evden çalışmak · bu yüzden · o · köpeği gezdirmek · öğlen' },
        { key: 's41', en: 'He always works from home because his office is far away.', tr: 'O her zaman evden çalışır çünkü ofisi uzakta.', alts: ['He always works from home because his office is far.'], cue: 'o · her zaman · evden çalışmak · çünkü · ofisi · uzakta' },
        { key: 's42', en: 'We sometimes work from home and have lunch together.', tr: 'Bazen evden çalışır ve birlikte öğle yemeği yeriz.', cue: 'biz · bazen · evden çalışmak · ve · öğle yemeği yemek · birlikte' },
        { key: 's43', en: 'My coworkers usually work from home, but we have a meeting every Monday.', tr: 'İş arkadaşlarım genelde evden çalışır ama her pazartesi toplantı yaparız.', cue: 'iş arkadaşlarım · genelde · evden çalışmak · ama · biz · toplantı yapmak · her pazartesi' },
        { key: 's44', en: 'Do you usually work from home, or do you go to the office?', tr: 'Genelde evden mi çalışırsın, yoksa ofise mi gidersin?', cue: 'mi · sen · genelde · evden çalışmak · yoksa · mi · sen · ofise gitmek' },
      ],
    },
    {
      id: 'l7',
      title: 'Uzun cümleler',
      note: '-dığında · -madan önce · -masına rağmen · -ar -maz · -ana kadar',
      bank: 'onError',
      sentences: [
        { key: 's45', en: "My boss doesn't usually work from home when we have a big meeting.", tr: 'Büyük bir toplantımız olduğunda patronum genelde evden çalışmaz.', cue: 'patronum · değil · genelde · evden çalışmak · -dığında · biz · büyük toplantı yapmak' },
        { key: 's46', en: 'I often work from the kitchen table until the kids come home.', tr: 'Çocuklar eve gelene kadar sık sık mutfak masasında çalışırım.', alts: ['I often work at the kitchen table until the kids come home.', 'I often work from the kitchen table until the kids get home.'], cue: 'ben · sık sık · çalışmak · mutfak masasında · -ana kadar · çocuklar · eve gelmek' },
        { key: 's47', en: 'After my husband goes to work, I usually work from the living room.', tr: 'Kocam işe gittikten sonra genelde salonda çalışırım.', alts: ['After my husband goes to work, I usually work in the living room.'], cue: '-dıktan sonra · kocam · işe gitmek · ben · genelde · çalışmak · salonda' },
        { key: 's48', en: 'Even though my wife works from home, she always gets up at seven.', tr: 'Eşim evden çalışmasına rağmen her zaman yedide kalkar.', alts: ['Although my wife works from home, she always gets up at seven.'], cue: '-masına rağmen · eşim · evden çalışmak · o · her zaman · kalkmak · saat 7' },
        { key: 's49', en: 'When I work from home, I often start work as soon as I wake up.', tr: 'Evden çalıştığımda sık sık uyanır uyanmaz işe başlarım.', cue: '-dığında · ben · evden çalışmak · ben · sık sık · işe başlamak · -ar -maz · ben · uyanmak' },
        { key: 's50', en: 'Do you always take a lunch break when you work from home?', tr: 'Evden çalıştığında her zaman öğle arası verir misin?', alts: ['Do you always have a lunch break when you work from home?'], cue: 'mi · sen · her zaman · öğle arası vermek · -dığında · sen · evden çalışmak' },
      ],
    },
  ],
});
