// UYARI: OTOMATIK URETILDI (scripts/gen_lesson_manifest.py). ELLE DUZENLEME.
// assets/lessons taranarak uretilir; yeni ders ekleyince generator'i tekrar calistir.
import type { Lesson } from './db';

// Tum dersler (cumle bazli gramer/kelime app veritabanina buradan girer).
export const ALL_LESSONS: Lesson[] = [
  require('../../assets/lessons/learneng_tv.json') as Lesson,
  require('../../assets/lessons/oxford_self.json') as Lesson,
  require('../../assets/lessons/ted_introvert.json') as Lesson,
  require('../../assets/lessons/zoella_vlog.json') as Lesson,
  require('../../assets/lessons/aliabdaal_eve.json') as Lesson,
  require('../../assets/lessons/davella_routine.json') as Lesson,
  require('../../assets/lessons/easyeng_london.json') as Lesson,
  require('../../assets/lessons/neistat_count.json') as Lesson,
  require('../../assets/lessons/ted_procrast.json') as Lesson,
  require('../../assets/lessons/damon_paris.json') as Lesson,
  require('../../assets/lessons/neistat_vlog.json') as Lesson,
  require('../../assets/lessons/yestheory_yes.json') as Lesson,
  require('../../assets/lessons/bbc6min_food.json') as Lesson,
  require('../../assets/lessons/davella_sugar.json') as Lesson,
  require('../../assets/lessons/foodreview_st.json') as Lesson,
  require('../../assets/lessons/ndrew_sleep.json') as Lesson,
  require('../../assets/lessons/aliabdaal_time.json') as Lesson,
  require('../../assets/lessons/mayuko_day.json') as Lesson,
  require('../../assets/lessons/schooloflife_career.json') as Lesson,
  require('../../assets/lessons/techlead_day.json') as Lesson,
  require('../../assets/lessons/tifo_clubs_money.json') as Lesson,
  require('../../assets/lessons/fireship_ai.json') as Lesson,
  require('../../assets/lessons/mkbhd_ai.json') as Lesson,
  require('../../assets/lessons/wired_blockchain.json') as Lesson,
  require('../../assets/lessons/kurzgesagt_lonely.json') as Lesson,
  require('../../assets/lessons/lesson1.json') as Lesson,
  require('../../assets/lessons/vox_noise.json') as Lesson,
  require('../../assets/lessons/foster_matchday.json') as Lesson,
  require('../../assets/lessons/hitc_risefall.json') as Lesson,
  require('../../assets/lessons/mckinnon_day.json') as Lesson,
  require('../../assets/lessons/skysports_micd.json') as Lesson,
  require('../../assets/lessons/ted_schools.json') as Lesson,
  require('../../assets/lessons/curated_could_have_v3.json') as Lesson,
  require('../../assets/lessons/curated_countable_uncountable.json') as Lesson,
  require('../../assets/lessons/curated_if_had_v3_would_have_v3.json') as Lesson,
  require('../../assets/lessons/curated_if_past_would.json') as Lesson,
  require('../../assets/lessons/curated_if_type1.json') as Lesson,
  require('../../assets/lessons/curated_modal_obligation.json') as Lesson,
  require('../../assets/lessons/curated_past_perfect_had_v3.json') as Lesson,
  require('../../assets/lessons/curated_present_cont_future.json') as Lesson,
  require('../../assets/lessons/curated_present_perfect_cont.json') as Lesson,
  require('../../assets/lessons/curated_should_have_v3.json') as Lesson,
  require('../../assets/lessons/curated_used_to.json') as Lesson,
  require('../../assets/lessons/curated_wish_past.json') as Lesson,
  require('../../assets/lessons/curated_would_have_v3.json') as Lesson,
];

// media_id -> unite no (sources.json'dan). Topic/unite gruplamasi icin.
export const UNIT_BY_MEDIA: Record<string, number> = {
  learneng_tv: 1,
  oxford_self: 1,
  ted_introvert: 1,
  zoella_vlog: 1,
  aliabdaal_eve: 2,
  davella_routine: 2,
  easyeng_london: 2,
  neistat_count: 2,
  ted_procrast: 2,
  damon_paris: 3,
  neistat_vlog: 3,
  yestheory_yes: 3,
  bbc6min_food: 4,
  davella_sugar: 4,
  foodreview_st: 4,
  ndrew_sleep: 4,
  aliabdaal_time: 5,
  mayuko_day: 5,
  schooloflife_career: 5,
  techlead_day: 5,
  tifo_clubs_money: 5,
  fireship_ai: 6,
  mkbhd_ai: 6,
  wired_blockchain: 6,
  kurzgesagt_lonely: 7,
  lesson1: 7,
  vox_noise: 7,
  foster_matchday: 8,
  hitc_risefall: 8,
  mckinnon_day: 8,
  skysports_micd: 8,
  ted_schools: 8,
};

// LOCAL gomulu videolar. Dev'de Metro servis eder; standalone build'de boyut buyur.
export const VIDEO_MODULES: Record<string, number> = {
  aliabdaal_eve: require('../../assets/videos/aliabdaal_eve.mp4'),
  aliabdaal_time: require('../../assets/videos/aliabdaal_time.mp4'),
  bbc6min_food: require('../../assets/videos/bbc6min_food.mp4'),
  damon_paris: require('../../assets/videos/damon_paris.mp4'),
  davella_routine: require('../../assets/videos/davella_routine.mp4'),
  davella_sugar: require('../../assets/videos/davella_sugar.mp4'),
  easyeng_london: require('../../assets/videos/easyeng_london.mp4'),
  fireship_ai: require('../../assets/videos/fireship_ai.mp4'),
  foodreview_st: require('../../assets/videos/foodreview_st.mp4'),
  foster_matchday: require('../../assets/videos/foster_matchday.mp4'),
  hitc_risefall: require('../../assets/videos/hitc_risefall.mp4'),
  kurzgesagt_lonely: require('../../assets/videos/kurzgesagt_lonely.mp4'),
  learneng_tv: require('../../assets/videos/learneng_tv.mp4'),
  lesson1: require('../../assets/videos/lesson1.mp4'),
  mayuko_day: require('../../assets/videos/mayuko_day.mp4'),
  mckinnon_day: require('../../assets/videos/mckinnon_day.mp4'),
  mkbhd_ai: require('../../assets/videos/mkbhd_ai.mp4'),
  ndrew_sleep: require('../../assets/videos/ndrew_sleep.mp4'),
  neistat_count: require('../../assets/videos/neistat_count.mp4'),
  neistat_vlog: require('../../assets/videos/neistat_vlog.mp4'),
  oxford_self: require('../../assets/videos/oxford_self.mp4'),
  schooloflife_career: require('../../assets/videos/schooloflife_career.mp4'),
  skysports_micd: require('../../assets/videos/skysports_micd.mp4'),
  techlead_day: require('../../assets/videos/techlead_day.mp4'),
  ted_introvert: require('../../assets/videos/ted_introvert.mp4'),
  ted_procrast: require('../../assets/videos/ted_procrast.mp4'),
  ted_schools: require('../../assets/videos/ted_schools.mp4'),
  tifo_clubs_money: require('../../assets/videos/tifo_clubs_money.mp4'),
  vox_noise: require('../../assets/videos/vox_noise.mp4'),
  wired_blockchain: require('../../assets/videos/wired_blockchain.mp4'),
  yestheory_yes: require('../../assets/videos/yestheory_yes.mp4'),
  zoella_vlog: require('../../assets/videos/zoella_vlog.mp4'),
};
